<?php if (!defined('APPLICATION')) exit();


/**
 * Renders the widget that displays the recent recipients of an Award.
 */
class RecentAwardRecipientsModule extends ModuleEx {
	// @var Gdn_Dataset Stores the list of the User Awards to display
	private $_UserAwardsDataSet;
	// @var int The ID of the User for whom to display the Awards.
	private $_AwardID;

	// @var int The maximum amount of entries to display
	const MAX_ENTRIES = 15;

	/**
	 * Returns an instance of UserAwardsModel.
	 *
	 * @return AwardsModel An instance of UserAwardsModel.
	 * @see BaseManager::GetInstance()
	 */
	private function UserAwardsModel() {
		return $this->GetInstance('UserAwardsModel');
	}

	/**
	 * Class constructor.
	 *
	 * @return UserAwardsModule.
	 */
	public function __construct($Sender = '') {
		$this->_AssetTarget = 'Content';

		parent::__construct($Sender);
	}

	/**
	 * Loads the list of the Awards obtained by the User.
	 */
	public function LoadData($AwardID, $MaxEntries = self::MAX_ENTRIES) {
		$this->_AwardID = $AwardID;
		if(empty($this->_AwardID)) {
			return;
		}

		$this->_UserAwardsDataSet =	$this->UserAwardsModel()->GetRecentAwardRecipients($AwardID,
																																									 array('DateAwarded desc'),
																																									 $MaxEntries);
	}


	/**
	 * Renders a list of <li> items displaying the Awards earned by a User.
	 *
	 * This method can be used in two ways:
	 * - By UserAwardsModule::ToString(), to render the list inside the User
	 *   Awards widget.
	 * - Externally, to just render the list items, with the purpose of updating
	 *   the widget content via AJAX.
	 *
	 * @return string HTML containing a list of <li> items, displaying User's
	 * Awards, or a single <li> with a message if there aren't any to be displayed.
	 */
	public function RenderUserList() {
		// Do not display anything if User is not logged in
		if(empty($this->_AwardID)) {
			return '';
		}
		// If there are no Awards to display, just show a message
		if($this->_UserAwardsDataSet->NumRows() <= 0) {
			echo Wrap(T('None yet.'), 'li');
		}

		// Show a list of User's Awards
		foreach($this->_UserAwardsDataSet->Result() as $UserAward) {
			//var_dump($UserAward);

			$UserObj = UserBuilder($UserAward);
			$UserPhoto = UserPhoto($UserObj, 'UserPhoto');

			$UserInfoCell = Wrap($UserPhoto .
													 UserAnchor($UserObj, 'UserAnchor') . '&nbsp;' .
													 Wrap(sprintf(T('on %s.'), Gdn_Format::Date($UserAward->DateAwarded, T('Date.DefaultFormat')))),
													 'li',
													 array('class' => 'AwardRecipient clearfix',));

			echo $UserInfoCell;
		}
	}

	/**
	 * Renders the output for the module.
	 *
	 * @return string The HTML generated by the module.
	 */
	public function ToString() {
		// Do not display anything if User is not logged in
		if(empty($this->_AwardID)) {
			return '';
		}
		ob_start();
		?>
		<div id="RecentAwardRecipients">
			<?php
				echo Wrap(T('Most recent recipients'), 'h2');
			?>
			<div>
				<ul id="UserList" class="PanelInfo clearfix">
				<?php
					$this->RenderUserList();
				?>
				</ul>
			</div>
			<div class="Footer">
				<?php
					// Dummy
				?>
			</div>
		</div>
		<?php
		$Output = ob_get_contents();
		@ob_end_clean();
		return $Output;
	}
}
