<?php
# Afrikaans
# language dependent text used in the interface for users (not admin)


$strCharSet             = 'UTF-8';
$strName                = 'Naam';
$strAddress             = 'Addres';
$strEmail               = 'Vonk-pos';
$strTown                = 'Dorp';
$strPostcode            = 'Poskode';
$strSubscribeInfo       = 'Sluit aan by een van ons nuusbriewe deur een van die die vorms hieronder';
$strRequired            = 'voorgeskrewe veld';
$strSubscribeTitle      = 'Sluit aan by ons Nuusbriewe';
$strPleaseSelect        = 'Kies die nuusbriewe jy will aansluit';
$strSubmit              = 'Sluit aan by die geslekteerde NuusBriewe';
$strNotAvailable        = 'Jammer, daar is huidiglik geen NuusBriewe beskikbaar';
$strEnterName           = 'Sleutel in jou naam Asb';
$strEnterEmail          = 'Sleutel in you vonk-pos adres';
$strInvalidHostInEmail  = 'Jammer, vonk-pos aan daardie domain is nie aflewerbaar nie, maak seker jy het die korekte adres ingesleutel';
$strEnterList           = 'Selkteer die Nuus Brief om aan te teken';
$strPleaseEnter         = 'Sleutel in jou';
# the thanks message can contain placeholders
#$strThanks              = 'Beste [FIRST NAME], <br/>Dankie dat u aangeteken het by ons Nuusbrief.';
$strThanks              = 'Dankie dat u aangeteken het by ons Nuusbriewe.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Jou Vonkpos adres [email] was bygevoeg by ons sisteem. Jy sal binnekort n vonkpos kry met bevestiging van die lyste by wie jy aangeteken het.';
$strEmailConfirmation   = 'Jou Vonpos was bygevoeg op ons sisteem. Jy sal binnekort n aanvraag kry om jou lidmaatskap te bevestig. Selekteer die link in die boodskap wat jy ontvang om jou lidmaatskap te bevestig.';
$strEmailFailed          = 'Jammer. Ons poging on vonkpos te stuur om jou lidmaatskap te bevestig het nie gewerk nie. Selekteer "Reload" om weer te probeer. As dit nog nie werk nie, dit kan wees dat jy is op ons "Swart-Lys", wat beteken dat jy nie vonkpos van ons stelsel kan ontvang. In daardie geval, kontak asb die stelsel eienaar.';
$strUnsubscribeTitle    = 'Teken af van ons Nuusbriewe';
$strUnsubscribeDone     = 'U is afgeteken van ons Nuusbriewe en sal binnekort vonpos konfirmasie ontvang.';
$strBack                = 'Terug';
$strUnsubscribeInfo     = 'Teken af van ons Nuusbriewe';
$strContinue            = 'Gaan Voort';
$strUnsubscribeSelect   = 'Kies die Nuusbriewe om af te teken.';
$strAllLists            = 'Alle Lyste';
$strNoLists             = 'Geen Lyste';
$strUnsubscribeRequestForReason = 'Ons is jammer dat u wil nie meer ons nuusbrief ontvang nie. Om ons diens te verbeter, vra ons asb dat u ons vertel wat u rede is:';
$strUnsubscribeFinalInfo = '<br/><b>Kennis Asb</b>: Hierdie bladsy is bedoel om vonkpos van ons sisteem <b>vir ewig</b> te verhoed. As jy net jou vonkpos adres wil verander, of jy wil verander watter nuusbrief u wil ontvang, gebruik asb <a href="[PREFERENCESURL]"> opdateer jou keuse</a>';
$strNoListsFound        = 'Jammer, jy is nie aangeteken by enige van ons Nuusbriewe met hierdie Vonpos adres.';
$strResubmit            = 'Her-stuur Vonpos';
$strUnsubscribeSubmit   = 'Teken af van die geselekteerde Nuusbriewe';
$strValuesMissing       = 'Die volgende waardes is nog nodig';
$strConfirmInfo         = 'Dankie vir u aantekening by ons Nuusbriewe. Die Nuusbriewe waaraan u hoort is onder gelys.';
$strConfirmTitle        = 'PHPlist Aantekening bevestigings bladsy';
$strUserNotFound        = 'Gebruiker nie gevind nie';
$strUserAlreadyInitialised = 'Jammer, u wagwoord was klaar gestel';
$strConfirmFailInfo     = 'Jammer, u versoek vir bevestiging was nie herken nie. Gebruik asb die voledige web-adres soos aangedui in die vonkpos wat u ontvang het. Soms loop hierdie adres oor meervodige lyne.';
$strPreferHTMLEmail     = 'Ek verkies on vonkposte in HTML formaat te ontvang';
$strPreferTextEmail     = 'Ek verkies on vonkposte in TEXT formaat te ontvang';
$strPreferredFormat      = 'Verkiesde formaat vir vonkposte:';
$strText                 = 'Text';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Opdateer u keuses';
$strPreferencesInfo     = 'Bevestig asb dat die inligting hieronder korek is, en selecteer die "opdateer" knoppie';
$strUpdatePreferences   = 'Opdateer';
$strPreferencesEmailChanged = 'U vonkpos het verander. Kuier asb by die skakel in die vonkpos wat u sal ontvang m u nuwe epos adres te bevestig';
$strYouAreBlacklisted = 'U vonpos is gelys in ons "Swart-Lys" wat beteken dat u het gevraom nooit weer vonkpos van ons te ontvang nie.<br/>
As u weer vonkposte wil ontang, moet die webwerf eienaar per hand u adres weer byvoeg. Kontak ons direk as u weer nuusbriewe will ontvang en ons sal 
van ons Swart-Lys verwyder.. ';
$strPreferencesNotificationSent = 'U sal n vonkpos ontvang my u veranderings';
$strPreferencesUpdated = 'Dankie. Ons het u inligting opgedateer.';
$strClickHere          = 'Klick Heer';
$strThisLink           = 'hierdie skakel';
$strToUnsubscribe      = 'As jy glad nie meer nuusbriewe wil ontvang nie, ';
$strToUpdate           = 'Om u stellings optedateer en/of om af te teken besoek';
$strSendHTML           = 'Stuur HTML vonkpos';
$strYes                = 'Ja';
$strNo                 = 'Nee';
$strUnsubscribe        = 'Teken Af';
$strAllMailinglists    = 'Alle nuusbriewe';
$strAttachmentIntro     = 'Hierdie boodskap bevat byvoegsels wat met n web "browser" gesien kan word.:';
$strLocation           = 'Location';
$strFrequency           = 'Hoe gereeld stuur ons u boodskappe';
$strHourly             = 'Huurliks';
$strDaily               = 'Daagliks';
$strWeekly             = 'Weekliks';
$strMonthly             = 'maandeliks';
$strChoosePassword      = 'Kies asb n wagwoord';
$strConfirmPassword    = 'Bevestig u wagwoord';
$strEnterPassword       = 'Sleutel asb u wagwoord in';
$strForgotPassword     = 'Wagwoord vergeet';
$strPassword           = 'Wagwoord';
$strPassword2           = 'Bevestig Wagwoord';
$strPasswordsNoMatch    = 'Wagwoord is nie dieselfde nie';
$strEmailsNoMatch     = 'Vonpos Adresse is nie dieselfde nie';
$strInvalidPassword     = 'Vout: ongeldige vonkpos of wagwoord';
$strPasswordSent        = 'U wagwoord is aan u gestuur dmw vonkpos. U behoort dit in die volgende paar minuute te ontvang';
$strPasswordRemindSubject = 'U Wagwoord vir ons Nuusbriewe';
$strPasswordRemindMessage = 'U Wagwoord is ';
$strPasswordRemindInfo = 'Om u wagwoord deur vonkpos te ontvang, sleutel asb u vonkpos adres in and klick op die "'.$strForgotPassword.'" knoppie.';
$strLogin               = 'Inteken';
$strLoginTitle          = 'Sleutel in asb vonkpos adres en wagwoord';
$strLoginInfo           = 'Hierdie bladsye veruys in wagwoord. Sleutel in asb vonkpos adres en wagwoord';
$strPersonalLocationInfo = '
  <p>Hierdie bladsy vereis persoonlike identifikasiewat bekrygbaar is in elke vonkpos wat ons vir u stuur.<br/>
  As u op hierdie skakel geklik het, en jy kry hierdie vout boodskap, maak asb seker om die hele lyne in to tik/paste by die 
  location box van u web browser. Soms is skakel gevou oor veelvoudige lyne.</p>
  <p>As u nie die skakel ken nie, u kan n aanvraag stuur om dit te ontvang.
  Sleutel asb u vonkpos adres in die box en selecteer "Voortgaan" ';
$strPersonalLocationSent = '<h1>Success! U behoort n boodskap te kry met u persoonlike inligting binnekort.</h1>';
$strUserExists   = '<br/>n Gebruiker met daardie vonkpos adres bestaan al reeds, en ons databasis bevat n verskillende wagwoord';
$strUserExistsExplanationStart = '<br/>Om u wagwoord to kry, klick ';
$strUserExistsExplanationLink = 'hier';
$strUserExistsExplanationEnd = ' om na die bladsy te gaan waar u u persoonlike inligting kan kry';
$strForwardTitle = 'Forward n boodskap aan iemand';
$strForwardSubtitle = 'Forwarding die boodskap met onderwerp ';
$strForwardEnterEmail = 'Sleutel in n geldige vonpos adres waarna die boodskap gestuur kan word';
$strForwardSuccessInfo ='Die boodskap was aangestuur';
$strForwardFailInfo = 'Aaanstuur van die boodskap was nie sussesvol nie';
$strForwardAlreadyDone = 'Hierdie boodskap was alreeds aan daardie vonkpos adres aangestuur.';
$strForwardFooter = 'Hierdie boodskap is aangestuur aan u vanaf [FORWARDEDBY].
  U is nie automaties aangeteken by hierdie nuusbrief.
  Om aanteteken gaan na';
$strForward = 'Aanstuur';
$strFwd = 'Fwd'; # short version of forward for email subject
?>
