<?php

# language dependent text used in the interface for users (not admin)
# Original translation by Gijsbert Rochat, update by Mike Rijken, 18/11/2002, review by Rudi Van Overloop, ruda@skynet.be 27/2/2004
# Changed to current phplist version by SaWey 25/02/2007
# Reviewed and changed by Dennis Lutz Oct 4, 2007
# Reviewed and updated for v2.10.7 - v2.10.10 on 21-12-2009

$strCharSet             = 'UTF-8';
$strName                = 'Naam';
$strAddress             = 'Adres';
$strEmail               = 'E-mail';
$strTown                = 'Plaats';
$strPostcode            = 'Postcode';
$strSubscribeInfo       = 'Meld u aan voor een van onze nieuwsbrieven door onderstaand formulier in te vullen';
$strRequired            = 'verplicht veld';
$strSubscribeTitle      = 'Meld u aan voor een nieuwsbrief';
$strPleaseSelect        = 'Selecteer de nieuwsbrief waarvoor u zich wilt aanmelden';
$strSubmit              = 'Aanmelden voor de geselecteerde nieuwsbrieven';
$strNotAvailable        = 'Er zijn momenteel geen nieuwsbrieven beschikbaar';
$strEnterName           = 'Vul uw naam in';
$strEnterEmail          = 'Vul een geldig e-mailadres in';
$strConfirmEmail        = 'Bevestig uw emailadres';
$strInvalidHostInEmail  = 'Sorry, e-mail naar dat domain kan niet worden verzonden, controleer a.u.b. of u het juiste e-mail adres heeft ingevuld';
$strEnterList           = 'Selecteer een nieuwsbrief waarop u zich wil aanmelden';
$strPleaseEnter         = 'Vul het volgende in';
# the thanks message can contain placeholders
$strThanks              = 'Bedankt dat u zich inschreef bij onze lijst.';
# the EmailConfirmation message can contain placeholders
$strEmailConfirmation   = 'Binnen enkele ogenblikken ontvangt u een e-mailbericht ter bevestiging van uw aanmelding. Vergeet niet op de link in het bericht te klikken, om uw inschrijving te bevestigen.';
$strEmailFailed         = 'Het verzenden van de bevestigingsmail is helaas mislukt, klik aub op "Reload" om het opnieuw te proberen. Als het dan nog niet lukt, dan kan het zijn dat u op de "Black List" staat, wat betekent dat u geen mails van onze nieuwsbrief kunt ontvangen. Neem in dat geval contact op met de beheerder.';
$strUnsubscribeTitle    = 'Afmelden op onze nieuwsbrief';
$strUnsubscribeDone     = 'U bent afgemeld voor de geselecteerde nieuwsbrief en u ontvangt binnen enkele ogenblikken een e-mailbericht ter bevestiging.';
$strBack                = 'Terug';
$strUnsubscribeInfo     = 'Afmelden voor een van onze nieuwsbrieven';
$strContinue            = 'Volgende';
$strUnsubscribeSelect   = 'Selecteer de nieuwsbrief waarop u zich wilt afmelden.';
$strAllLists            = 'Alle nieuwsbrieven';
$strNoLists             = 'Geen enkele nieuwsbrief';
$strUnsubscribeRequestForReason = 'Het spijt ons dat u onze nieuwsbrief niet langer wilt ontvangen. Om onze dienstverlening te helpen verbeteren zouden we het op prijs stellen als u ons wilt vertellen waarom u besloten heeft zich af te melden:';
$strUnsubscribeFinalInfo = '<br/><strong>Opgepast</strong>: deze pagina dient om <strong>nooit</strong> meer onze nieuwsbrief te ontvangen. Als u uw email wilt wijzigen of als je een andere nieuwsbrief wilt ontvangen, klik dan aub <a href="[PREFERENCESURL]">hier</a> om uw persoonlijke instellingen te wijzigen';
$strNoListsFound        = 'Sorry, u heeft met dit e-mailadres geen abonnement op een van onze nieuwsbrieven.';
$strResubmit            = 'Nogmaals e-mailadres';
$strUnsubscribeSubmit   = 'Afmelden op de geselecteerde nieuwsbrieven';
$strValuesMissing       = 'De volgende verplichte velden zijn niet ingevuld';
$strConfirmInfo         = 'Dank u voor het bevestigen van uw aanmelding. De nieuwsbrief waarop u bent geabonneerd wordt hieronder weergegeven';
$strConfirmTitle        = 'Bevestiging';
$strUserNotFound        = 'Gebruiker niet gevonden';
$strUserAlreadyInitialised = 'Sorry, uw wachtwoord is al ingesteld';
$strConfirmFailInfo     = 'Sorry, uw bevestiging werd niet herkend. Zorg er a.u.b. voor dat u het volledige web-adres volgt zoals vermeld in de email die u heeft ontvangen. Soms beslaat deze URL meerdere regels. Plak in dat geval de twee lijnen aan elkaar in de adresbalk van uw browser.';
$strPreferHTMLEmail     = 'Ik geef de voorkeur aan het ontvangen van e-mails in HTML-formaat.';
$strPreferTextEmail     = 'Ik geef de voorkeur aan het ontvangen van e-mails in Tekst=formaat.';
$strPreferredFormat     = 'Formaat van uw voorkeur voor e-mails:';
$strText                = 'Tekst';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Vernieuw uw instellingen';
$strPreferencesInfo     = 'Als de informatie hieronder correct is kunt u gewoon op de "wijzig" knop klikken om te bewaren';
$strUpdatePreferences   = 'wijzig';
$strPreferencesEmailChanged = 'Uw e-mail is gewijzigd. Klik op de link in de e-mail die u zo meteen ontvangt om de wijziging te bevestigen.';
$strYouAreBlacklisted = 'Uw e-mail staat op onze "Black List", dit betekent dat u ons gevraagd heeft nooit meer een nieuwsbrief op te sturen. <br/>
Om opnieuw e-mails te ontvangen is handmatige tussenkomst van de beheerder vereist. Neem contact met ons op en vermeld dat u onze nieuwsbrief opnieuw wilt ontvangen en wij zullen u dan van onze blacklist halen. ';
$strPreferencesNotificationSent = 'u ontvangt een e-mail met de wijzigingen';
$strPreferencesUpdated = 'Wij hebben uw instellingen aangepast.';
$strClickHere          = 'Klik hier';
$strThisLink           = 'deze link';
$strToUnsubscribe      = 'Om u van deze nieuwsbrief af te melden bezoek: ';
$strToUpdate           = 'Om uw voorkeuren te wijzigen bezoek: ';
$strSendHTML           = 'Verstuur HTML e-mail';
$strYes                = 'Ja';
$strNo                 = 'Nee';
$strUnsubscribe        = 'Afmelden';
$strAllMailinglists    = 'Alle nieuwsbrieven';
$strAttachmentIntro    = 'Dit bericht bevat bijlagen die in een webbrowser kunnen worden weergegeven:';
$strLocation           = 'Locatie';
$strFrequency          = 'Hoe vaak zenden wij u berichten';
$strHourly             = 'Ieder uur';
$strDaily              = 'Dagelijks';
$strWeekly             = 'Weekelijks';
$strMonthly            = 'Maandelijks';
$strChoosePassword     = 'Kies a.u.b. een wachtwoord';
$strConfirmPassword    = 'Bevestig uw wachtwoord';
$strEnterPassword      = 'Voer a.u.b. uw wachtwoord in';
$strForgotPassword     = 'Wachtwoord vergeten';
$strPassword           = 'Wachtwoord';
$strPassword2          = 'Bevestig wachtwoord';
$strPasswordsNoMatch   = 'Wachtwoorden komen niet overeen';
$strEmailsNoMatch      = 'De opgegeven e-mailadressen komen niet overeen';
$strInvalidPassword    = 'FOUT: ongeldig e-mail of wachtwoord';
$strPasswordSent       = 'Uw wachtwoord is naar uw e-mailadres verzonden. U zult het over enkele ogenblikken ontvangen';
$strPasswordRemindSubject = 'Uw wachtwoord voor onze nieuwsbrief';
$strPasswordRemindMessage = 'Uw wachtwoord is';
$strPasswordRemindInfo = 'Om uw wachtwoord per mail te ontvangen, vul a.u.b. uw e-mail in en klik op de "'.$strForgotPassword.'" knop.';
$strLogin              = 'Inloggen';
$strLoginTitle         = 'Vul uw e-mailadres en wachtwoord in a.u.b.';
$strLoginInfo          = 'Voor deze pagina is een wachtwoord vereist. Vul Uw e-mailadres en wachtwoord in a.u.b.';
$strPersonalLocationInfo = '
  <p>Deze pagina vereist een persoonlijke identificatie die u kan terugvinden in elke e-mail die we u sturen.<br/>
  Kijk nog eens goed de juiste URL in je browser na wanneer u een foutmelding ontvangt.
  De URL kan soms over 2 tekstlijnen verdeeld zijn.</p>
  <p>Wanneer u de URL niet kunt terugvinden, kunt u deze eenvoudig per e-mail aanvragen.
  Vul uw e-mailadres in a.u.b. en klik op "Continue"';
$strPersonalLocationSent = '<h1>Gefeliciteerd! U zult binnen enkele ogenblikken een bericht ontvangen met een overzicht van uw persoonlijke instellingen.</h1>';
$strUserExists   = '<br/>Een gebruiker met dit e-mailadres bestaat reeds, met een anderwachtwoord';
$strUserExistsExplanationStart = '<br/>Om uw wachtwoord te verkrijgen, klik';
$strUserExistsExplanationLink = 'hier';
$strUserExistsExplanationEnd = ' om naar de pagina te gaan waar u uw persoonlijke locatie kunt aanvragen';
$strExplainBlacklist = 'Het e-mailadres dat u hier opgeeft wordt in onze database geregistreerd uitsluitend met het doel de verzending van e-mailberichten naar uw adres te blockeren.';
$strForwardTitle = 'Stuur een bericht door aan iemand';
$strForwardSubtitle = 'Bericht wordt doorgestuurd met het volgend onderwerp';
$strForwardEnterEmail = 'Geef a.u.b. een geldig e-mailadres op om het bericht naar door te sturen';
$strForwardSuccessInfo ='Het bericht is doorgestuurd';
$strForwardFailInfo = 'Het doorsturen van het bericht is mislukt';
$strForwardInvalidEmail = '%s is geen geldig e-mailadres';
$strForwardBlacklistedEmail = 'De ontvanger heeft eerder aangegeven geen e-mailberichten te willen ontvangen van dit systeem.';
$strForwardEnterEmails = 'Vul hier a.u.b. niet meer dan %s geldige e-mailadressen in voor het doorsturen, een e-mailadres per regel';
$strForwardPersonalNote = 'U kunt een tekstbericht (van maximaal %d tekens) bijvoegen, dat bovenaan de doorgestuurde e-mail wordt toegevoegd';
$strForwardAlreadyDone = 'Dit bericht is met succes doorgestuurd naar het opgegeven adres';
$strForwardCountReached = 'Maximale toegestane aantal doorgestuurde e-mails bereikt';
$strForwardNoteLimitReached = 'Maximale lengte van uw persoonlijke bericht bereikt';
$strForwardFooter = 'Dit bericht is naar u doorgestuurd door [FORWARDEDBY].
  U bent niet automatisch toegevoegd aan onze abonnementenbestand.
  Om u te abonneren op deze nieuwsbrief, ga naar';
$strForward = 'Stuur door';
$strFwd = 'Fwd'; # short version of forward for email subject
?>