<?php
# language dependent text used in the interface for users (not admin)

# Bulgarian translation 1.3 for phplist 2.10.10
# Date: 26 December 2009
# Author: Petko Stoyanov
# Email: MasterAIP@gmail.com

$strCharSet             = 'UTF-8';
$strName                = 'Име';
$strAddress             = 'Адрес';
$strEmail               = 'Email';
$strTown                = 'Град';
$strPostcode            = 'Пощенски код';
$strSubscribeInfo       = 'Запишете се за един или повече бюлетини с новини като използвате формата по-долу';
$strRequired            = 'задължително поле';
$strSubscribeTitle      = 'Запишете се за бюлетин с новини';
$strPleaseSelect        = 'Моля изберете бюлетин/ите с новини, за които искате да се запишете';
$strSubmit              = 'Запишете се за избраните бюлетини';
$strNotAvailable        = 'В момента няма активни бюлетини с новини';
$strEnterName           = 'Моля въведете Вашето име';
$strEnterEmail          = 'Моля въведете валиден email адрес';
$strConfirmEmail        = 'И отново email адреса';
$strInvalidHostInEmail  = 'Съжаляваме, но не може да се достави писмо до този домейн, проверете дали сте въвели коректен email адрес';
$strEnterList           = 'Изберете бюлетин/ите с новини, за които искате да се запишете';
$strPleaseEnter         = 'Моля въведете Вашето';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Благодарим Ви, че се записахте за нашият бюлетин с новини.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Вашият email адрес бе добавен успешно. В рамките на няколко минути ще получите писмо със заявка за потвърждение на Вашият избор. Посетете адреса в писмото, за да потвърдите заявката си.';
$strEmailFailed          = 'Изпращането на писмото за потвърждение беше неуспешно, моля натиснете "Опитай отново" за да опитате отново. Ако все още получавате това съобщение, опишете проблема в писмо на адрес admin@venci.bg или използвайте <a href="http://news-blog.venci.bg/contact-us/">формата за контакти</a>.';
$strUnsubscribeTitle    = 'Отпишете се от бюлетин с новини';
$strUnsubscribeDone     = 'Вие се отписахте от бюлетин с новини и ще получите потвърждение на Вашият email адрес в рамките на няколко минути.';
$strBack                = 'Назад';
$strUnsubscribeInfo     = 'Отпишете се от бюлетин с новини';
$strContinue            = 'Продължи';
$strUnsubscribeSelect   = 'Изберете бюлетин с новини, от който искате да се отпишете';
$strAllLists            = 'Всички бюлетини';
$strNoLists             = 'Николко бюлетини';
$strUnsubscribeRequestForReason = 'Със съжаление разбираме, че вече не се интересувате от нашите бюлетини с новини. За да ни помогнете да подобрим услугата, ще Ви бъдем благодарни, ако ни кажете защо:';
$strUnsubscribeFinalInfo = '<br/><b>Обърнете внимание</b>: тази страница Ви дава възможност да спрете да получавате новини от нас <b>завинаги</b>. Ако искате да промените email адреса си или ако искате да промените (добавите нов или изтриете съществуващ) бюлетин с новини, <a href="[PREFERENCESURL]">променете предпочитанията си</a>.';
$strNoListsFound        = 'Този email адрес не е абониран за нито един бюлетин с новини';
$strResubmit            = 'Изпрати отново email';
$strUnsubscribeSubmit   = 'Отпишете се от избраните бюлетини с новини';
$strValuesMissing       = 'Следните задължителни полета липсват';
$strConfirmInfo         = 'Благодарим Ви, че потвърдихте абонамента си. Бюлетините с новини, за които сте се записали, са показани по-долу';
$strConfirmTitle        = 'Потвърждение на абонамент за бюлетини с новини';
$strUserNotFound        = 'Потребителят не е намерен';
$strUserAlreadyInitialised = 'Вече имате зададена паролаt';
$strConfirmFailInfo     = 'Заявката Ви за потвърждение на абонамент не може да бъде изпълнена. Уверете се, че използвате целият адрес, който сте получили в писмото като връзка. Понякога този адрес може да бъде на няколко реда.';
$strPreferHTMLEmail     = 'Предпочитам да получавам писма в HTML формат (препоръчително)';
$strPreferTextEmail     = 'Предпочитам да получавам писма в Текстов формат';
$strPreferredFormat      = 'Предпочитан формат на писмата:';
$strText                 = 'Текст';
$strHTML                = 'HTML (препоръчително)';
$strPreferencesTitle    = 'Обновете предпочитанията си';
$strPreferencesInfo     = 'Уверете се, че информацията по-долу е правилна и натиснете бутона "Обнови"';
$strUpdatePreferences   = 'Обнови';
$strPreferencesEmailChanged = 'Вашият email адрес бе сменен. Моля посетете адреса в писмото, което ще получите до няколко минути, за да потвърдите новият email адрес';
$strYouAreBlacklisted = 'Вашият email адрес е в "Черният списък", което означава, че Вие сте пожелали никога повече да не получавате писма с новини от нас.<br/>
За да имате възможност да получавате писма отново, се изисква ръчна настройка от нашият администратор. Изпратете писмо на адрес admin@venci.bg или използвайте <a href="http://news-blog.venci.bg/contact-us/">формата за контакти</a>, за да ни кажете, че искате да получавате писма отново, и ние ще Ви премахнем от черният списък. ';
$strPreferencesNotificationSent = 'Ще получите писмо с направените промени';
$strPreferencesUpdated = 'Благодарим Ви. Обновихме вашата информация.';
$strClickHere          = 'Натиснете тук';
$strThisLink           = 'този адрес';
$strToUnsubscribe      = 'Ако не желаете да получавате повече писма с новини, ';
$strToUpdate           = 'За да обновите предпочитанията си или за да се отпишете, посетете';
$strSendHTML           = 'Изпращане на HTML писма';
$strYes                = 'Да';
$strNo                 = 'Не';
$strUnsubscribe        = 'Отпишете се';
$strAllMailinglists    = 'Всички бюлетини с новини';
$strAttachmentIntro     = 'Това писмо съдържа прикачени файлове, които могат да бъдат разгледани с браузър-а:';
$strLocation           = 'Местоположение';
$strFrequency           = 'Колко често да Ви изпращаме съобщения';
$strHourly             = 'Всеки час';
$strDaily               = 'Всеки ден';
$strWeekly             = 'Всяка седмица';
$strMonthly             = 'Всеки месец';
$strChoosePassword      = 'Моля въведете парола';
$strConfirmPassword    = 'И отново паролата';
$strEnterPassword       = 'Моля въведете паролата си';
$strForgotPassword     = 'Забравена парола';
$strPassword           = 'Парола';
$strPassword2           = 'Потвърдете паролата';
$strPasswordsNoMatch    = 'Паролите не са еднакви';
$strEmailsNoMatch     = 'Email адресите, които сте въвели, не съвпадат';
$strInvalidPassword     = 'Грешка: невалиден email адрес или парола';
$strPasswordSent        = 'Паролата бе изпратена на Вашият email адрес. Ще я получите в следващите няколко минути';
$strPasswordRemindSubject = 'Вашата парола за бюлетини с новини';
$strPasswordRemindMessage = 'Вашата парола е ';
$strPasswordRemindInfo = 'За да получите паролата си, въведете Вашият email адрес и натиснете "'.$strForgotPassword.'" бутона.';
$strLogin               = 'Вход';
$strLoginTitle          = 'Въведете Вашият email адрес и парола';
$strLoginInfo           = 'Тази страница изисква парола за достъп. Въведете Вашият email адрес и парола';
$strPersonalLocationInfo = '
  <p>Тази страница изисква персонална идентификация, която може да бъде намерена във всяко писмо, което сме Ви изпратили.<br/>
  Ако сте натиснали на връзка, за да попаднете на тази страница, и виждате тази грешка, уверете се, че копирате целият адрес от писмото и го поставете в полето за адрес на Вашият браузър.
  Понякога този адрес може да бъде на няколко реда.</p>
  <p>Ако не знаете точният адрес-връзка към тази страница, можете да поискате да Ви го изпратим.
  Въведете Вашият email адрес в полето и натиснете "Продължи"
';
$strPersonalLocationSent = '<h1>Заявката е изпълнена успешно! Ще получите писмо с Вашата персонална идентификация в близките няколко минути</h1>';
$strUserExists   = '<br/>Потребител с този email адрес вече съществува и паролата е различна от тази в нашата система';
$strUserExistsExplanationStart = '<br/>За да получите паролата си, натиснете ';
$strUserExistsExplanationLink = 'тук';
$strUserExistsExplanationEnd = ' за да отидете на страницата, от която можете да поискате да Ви изпратим персоналата Ви идентификация';
$strExplainBlacklist = 'Email адресът, който въведете тук, ще бъде записан в базата данни само с цел да не се изпращат писма от системата към него.';
$strForwardTitle = 'Препратете съобщението на приятел';
$strForwardSubtitle = 'Препращане на съобщение с тема ';
$strForwardEnterEmail = 'Моля въведете валиден email адрес, на който искате да препратите това съобщение';
$strForwardInvalidEmail = '%s не е валиден email адрес';
$strForwardBlacklistedEmail = 'Получателят не желае да получава съобщения от системата.';
$strForwardEnterEmails = 'Въведете максимум %s валидни email адреса, до които искате да препратите това съобщение, по един на ред';
$strForwardPersonalNote = 'Можете да въведете текст (максимум %d символа), който ще бъде прикрепен към препратеното съобщение';
$strForwardSuccessInfo ='Съобщението бе препратено успешно';
$strForwardFailInfo = 'Препращането на съобщението бе неуспешно';
$strForwardAlreadyDone = 'Това съобщение вече е било успешно препратено на този email адрес';
$strForwardCountReached = 'Достигнат е лимита от максимално препратени съобщения';
$strForwardNoteLimitReached = 'Достигнат е лимита символи за допълнителен текст';
$strForwardFooter = 'Това съобщение е препратено до Вас от [FORWARDEDBY].
  Вие НЕ СТЕ автоматично абонирани да получавате писма от нашият информационен бюлетин.
  За да се абонирате за бюлетин с новини от нас, отидете на ';
$strForward = 'Препрати';
$strFwd = 'Препратено:'; # short version of forward for email subject
?>
