    <?php

    # language dependent text used in the public interface for users (not admin)
    # Updated up till v2.10.10

    $strCharSet             = 'UTF-8';
    $strName                = 'Nom';
    $strAddress             = 'Direcció';
    $strEmail               = 'Correu electrònic';
    $strTown                = 'Ciutat';
    $strPostcode            = 'Codi Postal';
    $strSubscribeInfo       = 'Subscripció a un o més dels nostres butlletins de notícies mitjançant el següent formulari';
    $strRequired            = 'Camp obligatori';
    $strSubscribeTitle      = 'Subscripció als nostres butlletins de notícies';
    $strPleaseSelect        = 'Si us plau, seleccioneu les llistes a les que voleu subscriure-us';
    $strSubmit              = 'Subscriure';
    $strNotAvailable        = 'Lamentablement, actualment no hi ha llistes disponibles';
    $strEnterName           = 'Si us plau, introduïu el vostre nom';
    $strEnterEmail          = 'Si us plau, introduïu la vostra adreça de correu electrònic';
    $strConfirmEmail        = 'Confirmeu la vostra adreça de correu electrònic';
    $strInvalidHostInEmail  = 'Ho sentim, però no trobem el vostre servidor. Si us plau, comproveu la vostra adreça de correu electrònic';
    $strEnterList           = 'Si us plau, seleccioneu la llista a la que desitgeu subscriure-us';
    $strPleaseEnter         = 'Si us plau, introduïu el vostre';
    # the thanks message can contain placeholders
    #$strThanks              = 'Benvolgut/da [FIRST NAME], <br/>Gràcies per la vostra subscripció als nostres butlletins de notícies.';
    $strThanks              = 'Benvolgut/da [Nom i Cognoms], <br/>Gràcies per la vostra subscripció als nostres butlletins de notícies.';
    # the EmailConfirmation message can contain placeholders
    #$strEmailConfirmation   = 'Your e-mail [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
    $strEmailConfirmation   = 'La vostra adreça de correu electrònic ([email]) ha estat afegida a la nostra base de dades. En breu rebreu un correu electrònic sol·lictant la confirmació. Si us plau, feu clic a l\'enllaç del missatge per a confirmar la subscripció.';
    $strEmailFailed         = 'Malauradament hi ha hagut un error en enviar la vostra confirmació. Si us plau, premeu "Actualitzar" per a intentar-ho de nou';
    $strUnsubscribeTitle    = 'Cancel·lar la subscripció als nostres butlletins de notícies';
    $strUnsubscribeDone     = 'Heu cancel·lat la subscripció al butlletí de notícies que heu seleccionat i rebreu una confirmació per correu electrònic.';
    $strBack                = 'Enrere';
    $strUnsubscribeInfo     = 'Cancel·lar la subscripció als nostres butlletins de notícies';
    $strContinue            = 'Continuar';
    $strUnsubscribeSelect   = 'Si us plau, seleccioneu el butlletí del que voleu cancel·lar la subscripció';
    $strAllLists            = 'Tots els butlletins';
    $strNoLists             = 'Cap';
    $strUnsubscribeRequestForReason = 'Lamentem que no estigueu interessat en els nostres butlletins de notícies. Per a ajudar-nos a millorar, us agraïríem que ens indiquéssiu el motiu per al que desitgeu deixar de rebre les nostres notícies:';
    $strUnsubscribeFinalInfo = '<br/><b>Nota important</b>: Aquesta pàgina és per deixar de rebre els nostres butlletins de notícies <b>de forma permanent</b>. Si voleu canviar la vostra adreça de correu electrònic, o bé si voleu canviar el butlletí al qual esteu subscrit, si us plau <a href="[PREFERENCESURL]">actualitzi les seves preferències.</a>';
    $strNoListsFound        = 'Actualment no esteu subscrit a cap dels nostres butlletins de notícies amb aquesta adreça de correu electrònic';
    $strResubmit            = 'Reenviar correu electrònic';
    $strUnsubscribeSubmit   = 'Cancel·lar subscripció dels butlletins de noticies seleccionats';
    $strValuesMissing       = 'El següent valor obligatori no ha estat introduït';
    $strConfirmInfo       = 'Gràcies per confirmar la vostra subscripció als nostres butlletins de notícies. Els butlletins de notícies als que ha estat subscrit es mostren a continuació';
    $strConfirmTitle       = 'Pàgina de confirmació per als membres';
    $strUserNotFound      = 'Usuari no trobat';
    $strUserAlreadyInitialised = 'Lamentablement, la vostra contrasenya ja ha estat configurada';
    $strConfirmFailInfo      = 'Hi ha hagut un error en intentar confirmar la vostra subscripció. El missatge d\'error es mostra a continuació.';
    $strPreferHTMLEmail     = 'Prefereixo rebre els correus electrònics en format HTML';
    $strPreferTextEmail     = 'Prefereixo rebre els correus electrònics en format Text';
    $strPreferredFormat      = 'Format preferit per a rebre els correus electrònics:';
    $strText             = 'Text';
    $strHTML            = 'HTML';
    $strPreferencesTitle    = 'Actualitzeu les vostres preferències';
    $strPreferencesInfo     = 'Si us plau, confirmeu que l\'informació és correcte i premeu el botó "Actualitzar informació"';
    $strUpdatePreferences   = 'Actualitzar informació';
    $strPreferencesEmailChanged = 'La vostra adreça de correu electrònic ha canviat. Si us plau, visiteu l\'enllaç del correu electrònic que rebreu per a confirmar la vostra nova adreça.';
    $strYouAreBlacklisted    = 'La vostra adreça ha estat inclosa a la nostra "Llista negra", la qual cosa significa que heu sol·licitat no rebre més els nostres butlletins de notícies. <br/> Per a rebre els nostres butlletins de notícies és necessària la intervenció manual de l\'administrador. Si us plau, contacteu amb l\'administrador i comenteu-li la situació per tal que l\'elimini de la llista negra.';
    $strPreferencesNotificationSent = 'Rebreu un correu electrònic amb els canvis';
    $strPreferencesUpdated = 'Gràcies. Hem actualizat la vostra informació.';
    $strClickHere          = 'Feu clic aquí';
    $strThisLink           = 'aquest enllaç';
    $strToUnsubscribe      = 'Per a deixar de rebre el nostre butlletí de notícies visiteu';
    $strToUpdate           = 'Per a actualitzar les vostres preferències visiteu';
    $strSendHTML           = 'Enviar correu electrònic en format HTML';
    $strYes                = 'Sí';
    $strNo                 = 'No';
    $strUnsubscribe        = 'Donar de baixa';
    $strAllMailinglists    = 'Totes les llistes';
    $strAttachmentIntro      = 'Aquest missatge conté caràcters que poden ser vistos amb un navegador:';
    $strLocation         = 'Ubicació';
    $strFrequency         = 'Cada quan us enviem els nostres butlletins de notícies';
    $strHourly            = 'Cada hora';
    $strDaily            = 'Diàriament';
    $strWeekly            = 'Setmanalment';
    $strMonthly            = 'Mensualment';
    $strChoosePassword       = 'Si us plau, trieu una contrasenya';
    $strConfirmPassword    = 'Confirmeu la vostra contrasenya';
    $strEnterPassword      = 'Si us plau, introduïu la vostra contrasenya';
    $strForgotPassword      = 'Ha oblidat la vostra contrasenya?';
    $strPassword         = 'Contrasenya';
    $strPassword2         = 'Confirmeu la vostra contrasenya';
    $strPasswordsNoMatch    = 'Les contrasenyes no són iguals ';
    $strEmailsNoMatch        = 'Les adreces de correu electrònic no són iguals';
    $strInvalidPassword      = 'Error: adreça de correu electrònic o contrasenya incorrectes';
    $strPasswordSent       = 'La vostra contrasenya ha estat enviada a la vostra adreça de correu electrònic. L\'hauríeu de rebre en els propers minuts.';
    $strPasswordRemindSubject = 'La vostra contrasenya en la nostra llista';
    $strPasswordRemindMessage = 'La vostra contrasenya és ';
    $strPasswordRemindInfo    = 'per a rebre la vostra contrasenya per correu electrònic, si us plau, introduïu la seva adreça de correu electrònic i feu clic al botó de  "'.$strForgotPassword.'".';
    $strLogin            = 'Iniciar sessió';
    $strLoginTitle          = 'Si us plau, introduïu la vostra adreça de correu electrònic i contrasenya.';
    $strLoginInfo         = 'Aquesta pàgina requereix una contrasenya. Si us plau, introduïu la vostra adreça de correu electrònic i contrasenya.';
    $strPersonalLocationInfo = '
       <p>Aquesta pàgina requereix una identificació personal que pot trobar en cada un dels butlletins que us hem enviat.<br/>
      Si veieu aquest missatge, si us plau reviseu que ha copiat i enganxat TOT l\'enllaç que heu rebut per correu electrònic. A vegades l\'enllaç salta de línia i no és copiat COMPLETAMENT.</p>
      <p>Si heu perdut el correu, podeu sol·licitar-ne un de nou.
      Si us plau, introduïu la vostra adreça de correu electrònic i feu clic a "Continuar" ';
    $strPersonalLocationSent = '<h1>Enhorabona! Aviat rebreu un correu electrònic amb la vostra ubicació personal</h1>';
    $strUserExists         = '<br/>Existeix un usuari amb aquesta adreça de correu electrònic, però té una contrasenya diferent.';
    $strUserExistsExplanationStart = '<br/>per obtenir la seva contrasenya, feu clic aquí ';
    $strUserExistsExplanationLink = 'aquí';
    $strUserExistsExplanationEnd = ' per anar a la pàgina on podeu demanar la vostra ubicació personal';
    $strExplainBlacklist    = 'L\'adreça de correu electrònic que introduïu aquí serà registrada a la nostra base de dades amb l\'únic proposit de bloquejar qualsevol correu electrònic enviat des d\'aquest sistema.';
    $strForwardTitle       = 'Reenviar el missatge a una altra persona';
    $strForwardSubtitle    = 'Reenviant el missatge amb assumpte ';
    $strForwardEnterEmail    = 'Si us plau, introduïu una adreça de correu electrònic vàlida a la qual reenviar aquest missatge';
    $strForwardInvalidEmail = '%s no és una adreça de correu electrònic vàlida';
    $strForwardBlacklistedEmail = 'El receptor ha sol·licitat NO rebre correus electrònics d\'aquest sistema.';
    $strForwardEnterEmails    = 'Si us plau, introduïu un màxim de %s adreces de correu electrònic vàlides per a reenviar en aquest quadre, una per línia';
    $strForwardPersonalNote = 'Podeu introduir un missatge de text (de % caracters màxim) que s\'afegirà al correu electrònic enviat.';
    $strForwardSuccessInfo    ='El missatge ha estat reenviat';
    $strForwardFailInfo    = 'El reenviament del missatge ha fallat';
    $strForwardAlreadyDone    = 'Aquest missatge ha estat reenviat satisfactòriament al correu electrònic';
    $strForwardCountReached = 'Ha arribat al número màxim de reenviaments';
    $strForwardNoteLimitReached = 'Ha arribat a la capacitat màxim de la nota personal';
    $strForwardFooter       = 'Aquest misstage ha estat enviat per [FORWARDEDBY].
      No serèu subscrit de forma autòmatica als nostres butlletins de notícies.
      Per a subscriure\'s heu d\'anar a ';
    $strForward          = 'Reenviar';
    $strFwd             = 'Fwd'; # short version of forward for e-mail subject
    ?>