<?php

# language dependent text used in the interface for users (not admin)
# Croatian translation by Mato Špekuljak mato.spekuljak@post.t-com.hr
# alternative coding iso-8859-2
# V. 11.03.06-01 /PHPlist 2.10.2
$strCharSet             = 'UTF-8';
$strName                = 'Ime i prezime';
$strAddress             = 'Adresa';
$strEmail               = 'E-mail adresa';
$strTown                = 'Mjesto';
$strPostcode            = 'Poštanski broj';
$strSubscribeInfo       = 'Pomoću donjeg obrasca možete se pretplatiti na sadržaje naših mailing-lista.';
$strRequired            = 'Podaci koje treba obavezno unijeti (pripazite da u obje rubrike za E-mail adresu bude ista adresa):';
$strSubscribeTitle      = 'Pretplata na sadržaje naših mailing-lista';
$strPleaseSelect        = 'Izaberite mailing-liste u koje se želite upisati.';
$strSubmit              = 'Upis u mailing-liste';
$strNotAvailable        = 'Trenutno ne nudimo ni jednu mailing-listu.';
$strEnterName           = 'Molimo Vas da unesete Vaše ime i prezime (ili nadimak).';
$strEnterEmail          = 'Molimo Vas da unesete Vašu E-mail adresu';
$strInvalidHostInEmail  = 'Na žalost, E-mail adresu koju ste unijeli ne možemo prihvatiti; molimo Vas da je još jedanput provjerite jeste li upisali ispravnu E-mail adresu.';
$strEnterList           = 'Molimo Vas da izaberete mailing-listu u koju se želite upisati';
$strPleaseEnter         = 'Nedostaje';
# the thanks message can contain placeholders
#$strThanks              = 'Poštovanje, [FIRST NAME], <br/>hvala što ste se upisali u jednu ili više naših mailing-lista.';
$strThanks              = 'Hvala što ste se pretplatitli na sadržaje koje nudimo preko naših mailing-lista.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Vaša adresa [email] upisana je u našu bazu podataka. Sada će Vam biti poslan zahjev da pretplatu potvrdite.';
$strEmailConfirmation   = 'Adresa [email] upisana je u našu bazu podataka. Sada će Vam biti poslan zahtjev da pretplatu potvrdite. Da biste pretplatu potvrdili, molimo Vas da kliknete na njen link u obavijesti.';
$strEmailFailed					= 'Na žalost, zahtjev da potvrdite pretplatu nije Vam otišao. Pokušajte ponovno klikom na ikonu "Osvježi". Ako to nije pomoglo možda je Vaša E-mail adresa na popisu adresa koje ne mogu primati E-mailove iz sustava naših mailing-lista. Ako je tako, molimo Vas da kontaktirate administratora.';
$strUnsubscribeTitle    = 'Odustajanje od pretplate';
$strUnsubscribeDone     = 'Pretplata na odabrane sadržaje je poništena. Obavijest o poništenju pretplate poslana Vam je E-mailom .';
$strBack                = 'Natrag';
$strUnsubscribeInfo     = 'Odustajanje od pretplate';
$strContinue            = 'Nastavak';
$strUnsubscribeSelect   = 'Molimo Vas da odaberete mailing-liste u koje više ne želite biti upisani';
$strAllLists            = 'Sve liste';
$strNoLists             = 'Nijedna lista';
$strUnsubscribeRequestForReason = 'Žao nam je što više niste zainteresirani za pretplatu na sadržaje naših mailing-lista. Upisivanjem razloga Vašeg odustajanja od pretplate možete pridonijeti da sadržaji koje nudimo postanu kvalitetniji:';
$strUnsubscribeFinalInfo = '<br/><b>Molimo Vas da uzmete u obzir</b>: preko ove web-stranice Vaša pretplata na sadržaje naših mailing-lista poništava se <b>definitivno</b>. Želite li možda samo promijeniti Vašu E-mail adresu ili sadržaje pretplate <a href="[PREFERENCESURL]">ovdje možete unijeti željene promjene</a> umjesto da poništite pretplatu';
$strNoListsFound        = 'Na žalost, ova E-mail adresa nije prisutna ni u jednog pretplati na naše sadržaje.';
$strResubmit            = 'Upišite ponovno E-mail adresu';
$strUnsubscribeSubmit   = 'Odustajanje od pretplate na izabrane sadržaje';
$strValuesMissing       = 'Nedostaju ili nisu aktualni ovi podaci';
$strConfirmInfo         = 'Hvala što ste se potvrdili upis u jednu ili više naših mailing-lista. Upisani ste u ove mailing-liste:';
$strConfirmTitle        = 'Web-stranica za potvrdu pretplate';
$strUserNotFound        = 'Korisnika/Korisnice s tim podacima nema';
$strUserAlreadyInitialised = 'Na žalost, ovu zaporku ne možemo prihvatiti';
$strConfirmFailInfo     = 'Na žalost, Vaš zahtjev za potvrdu pretplate nije prepoznat. Jeste li sigurni da ste unijeli cijelu web-adresu koju smo Vam poslali E-mailom kao link? U nekim programima za poštu web-adresa može biti prelomljena u dva ili više redaka.';
$strPreferHTMLEmail     = 'Želim primati E-mailove u formatu HTML.';
$strPreferTextEmail     = 'Želim primati E-mailove u formatu TEXT.';
$strPreferredFormat			= 'Izabrani format E-mailova:';
$strText 								= 'TEXT';
$strHTML								= 'HTML';
$strPreferencesTitle    = 'Promjena podataka o pretplati';
$strPreferencesInfo     = 'Molimo Vas da potvrdite unesene promjene klikom na gumb "Promijeni".';
$strUpdatePreferences   = 'Promijeni';
$strPreferencesEmailChanged = 'Promijenjena je E-mail adresa. Molimo Vas da kliknete na link u E-mailu što smo Vam ga poslali kako biste potvrdili Vašu novu E-mail adresu.';
$strYouAreBlacklisted = 'Vaša E-mail adresa na popisu adresa koje ne primaju E-mailove iz sustava naših mailing-lista, što znači da ste zatražili poništenje svih pretplata. <br/>
Da biste mogli ponovno primati od nas sadržaje, molimo Vas da nas kontaktirate i zatražite da Vam administrator obnovi pretplatu. On može
Vašu adresu ponovno aktivirati. ';
$strPreferencesNotificationSent = 'Koji su podaci ažurirani možete vidjeti iz obavijesti koja Vam je upravo poslana E-mailom.';
$strPreferencesUpdated = 'Zahvaljujemo na ažuriranju podataka. Podaci su ažurirani.';
$strClickHere          = 'Kliknite ovdje';
$strThisLink           = 'ovaj link';
$strToUnsubscribe      = 'Ako više ne želite primati naše sadržaje';
$strToUpdate           = 'Ako želite promijeniti podatke o Vašoj pretplati ili poništiti Vašu pretplatu molimo Vas da otvorite web-stranicu';
$strSendHTML           = 'E-mail u formatu HTML';
$strYes                = 'Da';
$strNo                 = 'Ne';
$strUnsubscribe        = 'Poništavam pretplatu';
$strAllMailinglists    = 'Sve liste';
$strAttachmentIntro		 = 'Ovaj E-mail sadrži likove koji koji se mogu vidjeti tj. aktivirati web-tražilicom (browserom):';
$strLocation					 = 'Lokacija';
$strFrequency					 = 'U kojim vremenskim razmacima želite primati E-mailove s našim sadržajima?';
$strHourly						 = 'Svaki sat';
$strDaily							 = 'Svaki dan';
$strWeekly						 = 'Jedanput tjedno';
$strMonthly						 = 'Jedanput mjesečno';
$strChoosePassword 		 = 'Molimo Vas da izaberete zaporku';
$strConfirmPassword 	 = 'Potvrda zaporke';
$strEnterPassword			 = 'Molimo Vas da unesete zaporku';
$strForgotPassword		 = 'Zaboravio/Zaboravila sam zaporku';
$strPassword					 = 'Zaporka';
$strPassword2					 = 'Potvrda zaporke';
$strPasswordsNoMatch 	 = 'Unesene zaporke nisu istovjetne.';
$strEmailsNoMatch     = 'Unesene E-mail adrese nisu istovjetne.';
$strInvalidPassword		 = 'Pogrešna E-mail adresa ili zaporka';
$strPasswordSent 		   = 'Zaporka je poslana E-mailom. Trebali biste je dobiti za najviše nekoliko minuta.';
$strPasswordRemindSubject = 'Zaporka za naše mailing-liste';
$strPasswordRemindMessage = 'Vaša je zaporka:';
$strPasswordRemindInfo = 'Da biste dobili zaporku E-mailom, molimo Vas da unesete Vašu E-mail adresu i kliknete na "'.$strForgotPassword.'" gumb.';
$strLogin							 = 'Prijava';
$strLoginTitle 				 = 'Molimo Vas da upišete E-mail adresu i zaporku';
$strLoginInfo	           = 'Ova web-stranica zahtijeva zaporku. Molimo Vas da unesete E-mail adresu i zaporku';
$strPersonalLocationInfo = '
	<p>Ova stranica zahtijeva unošenje u web-tražilicu (browser) web-adrese s Vašom identifikacijskom oznakom. Web-adresa s Vašom identifikacijskom oznakom nalazi se u svakom E-mailu koji od nas primite.<br/>
  Ako Vam nakon unosa u web-tražilicu (browser) adrese iz našeg E-maila bude javljena pogreška, provjerite da li ste unijeli cijeli redak u
 rubriku za web-adresu na web-tražilici (browseru). Katkad je web-adresa primljena preko nekih programa za poštu prelomljena u dva ili više redaka pa ste možda u web-tražilicu (browser) unijeli samo dio adrese.</p>
  <p>Ako ne znate web-adresu s Vašom identifikacijskom oznakom korisnika/korisnice naših mailing-lista možete od nas zatražiti E-mail s takvom adresom.
 Unesite Vašu E-mail adresu u rubriku za adresu i kliknite na gumb "Nastavak"
';
$strPersonalLocationSent = '<h1>Uspjeli ste! Obavijest s Vašom identifikacijskom oznakom poslana je na Vašu E-mail adresu. </h1>';
$strUserExists   = '<br/>Korisnik s unesenom E-mail adresom registriran je pod drugom zaporkom';
$strUserExistsExplanationStart = '<br/>Želite li dobiti Vašu zaporku kliknite ';
$strUserExistsExplanationLink = 'ovdje';
$strUserExistsExplanationEnd = 'da biste došli na web-stranicu na kojoj možete zatražiti Vašu lokaciju';
$strForwardTitle = 'Proslijedi E-mail drugoj osobi';
$strForwardSubtitle = 'Proslijedi E-mail s naznakom predmeta ';
$strForwardEnterEmail = 'Unesite E-mail adresu na koju želite proslijediti E-mail';
$strForwardSuccessInfo ='E-mail je poslan na drugu adresu';
$strForwardFailInfo = 'E-mail nije poslan na drugu E-mail adresu';
$strForwardAlreadyDone = 'Ovaj E-mail je vec poslan na drugu E-mail adresu';
$strForwardFooter = 'Ovaj E-mail ste dobili od [FORWARDEDBY].
  Vi nemate pretplatu na takve sadržaje.
  Želite li se pretplatiti na takve sadržaje idite na';
$strForward = 'Forward';
$strFwd = 'Fwd'; # short version of forward for email subject
?>