<?php
# language dependent text used in the interface for users (not admin)
# translation started by Steen Rabøl <srabol@mail.tele.dk>
# translation corrected and continued by Carsten Gehling <carsten@sarum.dk>
# 2011.05.12 - translation corrected and continued by Reynir Kristbjörnsson <rk(@)northtravel.dk>.
#     The danish words Postliste and opsige have been replaced with the danish words 
#     nyhedsbrev and afmelde respectively.
# translated for version 2.6.5
# translation corrected and updated for version 2.8.11
# 2011.05.22 - translation from english to danish for following missing variables added by Reynir Kristbjörnsson <rk(@)northtravel.dk>:
# $strYouAreBlacklisted, $strExplainBlacklist, $strForwardInvalidEmail, $strForwardBlacklistedEmail, $strForwardEnterEmails
# and $strForwardPersonalNote
$strCharSet             = 'UTF-8';
$strName                = 'Navn ';
$strAddress             = 'Adresse ';
$strEmail               = 'E-mail ';
$strTown                = 'By ';
$strPostcode            = 'Postnr ';
$strSubscribeInfo       = 'Tilmeld dig nyhedsbrev(e) ved at udfylde formularen nedenfor.';
$strRequired            = 'Obligatorisk felt';
$strSubscribeTitle      = 'Tilmelding til nyhedsbrev';
$strPleaseSelect        = 'Vælg nyhedsbrev(e) du ønsker at tilmelde dig';
$strSubmit              = 'Tilmeld valgt(e) nyhedsbrev(e)';
$strNotAvailable        = 'Beklager - der er ingen tilgængelige nyhedsbreve';
$strEnterName           = 'Indtast dit navn';
$strEnterEmail          = 'Indtast din e-mail adresse';
$strConfirmEmail        = 'Gentag e-mail ';
$strInvalidHostInEmail  = 'Der kan ikke leveres e-mails til dette domæne. Kontrollér at du har indtastet en korrekt e-mail adresse.';
$strEnterList           = 'Vælg et nyhedsbrev du ønsker at tilmelde dig';
$strPleaseEnter         = 'Indtast';
# the thanks message can contain placeholders
#$strThanks              = 'Kære [FIRST_NAME], <br/>Tak fordi du har tilmeldt dig vores nyhedsbrev(e).';
$strThanks              = 'Tak for din tilmelding til vores nyhedsbrev(e).';
# the EmailConfirmation message can contain placeholders
$strEmailConfirmation   = 'Du vil inden for kort tid modtage en e-mail med bekræftelse på de nyhedsbrev(e) du har tilmeldt dig';
$strEmailFailed		= 'Der skete en fejl i afsendelsen af en bekræftelse til dig. Tryk "Opdater" for at prøve igen.';
$strUnsubscribeTitle    = 'Afmeld nyhedsbrev';
$strUnsubscribeDone     = 'Du er blevet afmeldt valgt(e) nyhedsbrev(e). Du vil modtage en bekræftelse inden kort tid.';
$strBack                = 'Tilbage';
$strUnsubscribeInfo     = 'Afmeld nyhedsbrev';
$strContinue            = 'Fortsæt';
$strUnsubscribeSelect   = 'Vælg nyhedsbrev(e) du ønsker at afmelde';
$strAllLists            = 'Alle nyhedsbreve';
$strNoLists             = 'Ingen af dem';
$strUnsubscribeRequestForReason = 'Vi er kede af, at du ikke længere ønsker at modtage vores nyhedsbrev. Vi vil være taknemmelige for at modtage en begrundelse.';
$strUnsubscribeFinalInfo = '<br/><b>Bemærk</b>: Denne side er vedrørende <b>afmelding</b> af nyhedsbrev. Hvis du ønsker at ændre din e-mail adresse, eller hvis du ønsker at ændre din tilmelding, bedes du ændre dine <a href="[PREFERENCESURL]">præferencer</a>';
$strNoListsFound        = 'Beklager, du er ikke tilmeldt nogen af vores nyhedsbrev(e) med denne e-mail adresse';
$strResubmit            = 'Gensend e-mail';
$strUnsubscribeSubmit   = 'Afmeld valgt(e) nyhedsbrev(e)';
$strValuesMissing       = 'De følgende obligatoriske værdier mangler';
$strConfirmInfo		= 'Tak for bekræftelse på tilmelding til vores nyhedsbrev(e). De nyhedsbrev(e) du er tilmeldt er vist nedenfor';
$strConfirmTitle	= 'Nyhedsbrevs tilmeldingsbekræftelse';
$strUserNotFound        = 'Bruger ikke fundet';
$strUserAlreadyInitialised = 'Din adgangskode er allerede sendt.';
$strConfirmFailInfo     = 'Denne bekræftelse kunne ikke gennemføres. Kontroller at du har anvendt den komplette adresse i e-mail\'en. Visse e-mail programmer deler lange linier, og linket fylder derfor to eller flere linier.';
$strPreferHTMLEmail     = 'Jeg ønsker at modtage e-mails i HTML format';
$strPreferTextEmail     = 'Jeg ønsker at modtage e-mails i rent tekst format';
$strPreferredFormat	= 'Foretrukken e-mail format:';
$strText		= 'Tekst';
$strHTML		= 'HTML';
$strPreferencesTitle    = 'Opdater dine indstillinger';
$strPreferencesInfo     = 'Kontroller at nedenstående information er korrekt. Ret hvis nødvendigt og klik derefter på knappen "Opdater".';
$strUpdatePreferences   = 'Opdater';
$strPreferencesEmailChanged = 'Din e-mail adresse er blevet ændret. Du modtager nu en e-mail med et link. Klik på dette link, for at bekræfte din nye e-mail adresse.';
$strYouAreBlacklisted = 'Du får denne besked, fordi du tidligere har afmeldt modtagesle af vores nyhedbreve. <br/>
Såfremt du igen ønsker, at modtage vores nyhedsbreve, bedes du at kontakte os med et klart ønske om  tilmelding. ';
$strPreferencesNotificationSent = 'Du modtager nu en e-mail med ændringerne.';
$strPreferencesUpdated = 'Tak for dine ændringer, vi har opdateret dine indstillinger.';
$strClickHere          = 'Klik her';
$strThisLink           = 'dette link';
$strToUnsubscribe      = 'For at afmelde nyhedsbrevet klik';
$strToUpdate           = 'For at ændre dine personlige indstillinger klik';
$strSendHTML           = 'Send HTML e-mail';
$strYes                = 'Ja';
$strNo                 = 'Nej';
$strUnsubscribe        = 'Afmeld nyhedsbrev';
$strAllMailinglists    = 'Alle nyhedsbreve';
$strAttachmentIntro    = 'Denne e-mail indeholder vedhæftede filer, der kan ses i en webbrowser:';
$strLocation		 = 'Lokalitet';
$strFrequency		 = 'Hvor tit sender vi e-mails til dig';
$strHourly		 = 'En gang i timen';
$strDaily		 = 'Dagligt';
$strWeekly		 = 'Ugenligt';
$strMonthly		 = 'Månedligt';
$strChoosePassword	 = 'Vælg en adgangskode';
$strConfirmPassword	 = 'Bekræft din adgangskode';
$strEnterPassword	 = 'Indtast din adgangskode';
$strForgotPassword	 = 'Glemt adgangskode';
$strPassword		 = 'Adgangskode';
$strPassword2  		= 'Bekræft adgangskode';
$strPasswordsNoMatch 	 = 'De to adgangskoder er ikke ens';
$strEmailsNoMatch     = 'De indtastede e-mail adresser er ikke ens';
$strInvalidPassword	 = 'Forkert e-mail eller adgangskode';
$strPasswordSent  	 = 'Vi har sendt en e-mail med din adgangskode, som du modtager indenfor kort tid.';
$strPasswordRemindSubject = 'Din adgangskode for vores nyhedsbrev(e)';
$strPasswordRemindMessage = 'Din adgangskode er ';
$strPasswordRemindInfo 	= 'For at få din adgangskode tilsendt, skal du skrive din e-mail adresse og derefter trykke på knappen "'.$strForgotPassword.'".';
$strLogin		 = 'Login';
$strLoginTitle		 = 'Indtast din e-mail adresse og adgangskode';
$strLoginInfo		 = 'Denne side kræver en adgangskode. Indtast din e-mail adresse og adgangskode';
$strPersonalLocationInfo = '
<p>
	Denne side kræver en personlig identifikation, som du finder i hver eneste e-mail, vi sender.
	<br/>
	Hvis du er nået hertil ved at klikke på et link i e-mailen, er der muligvis en fejl i det link,
	som du bruger. Visse e-mail programmer deler lange linier, og linket fylder derfor to eller
	flere linier.
</p>
<p>
	Hvis du ikke kender den rigtige adresse, kan du anmode om at få tilsendt en e-mail, som
	indeholder den rigtige adresse.
	Indtast din e-mail adresse i feltet og klik "Fortsæt".</p>
';
$strPersonalLocationSent = '<h1>Du modtager inden for kort tid en e-mail med din personlige adresse.</h1>';
$strUserExists   = '<br/>En bruger med denne e-mail adresse eksisterer allerede, og med et andet password';
$strUserExistsExplanationStart = '<br/>For at modtage dit password, klik ';
$strUserExistsExplanationLink = 'her';
$strExplainBlacklist = 'Den indtastede e-mail adresse, registreres i vores database, udelukkende til det formål, at forhindre fremsendelse af e-mails fra systemet.';
$strForwardTitle = 'Videresend en besked til en ven';
$strForwardSubtitle = 'Videresend besked med emne ';
$strForwardEnterEmail = 'Indtast venligst en gyldig e-mail adresse for videresendelse';
$strForwardInvalidEmail = '%s er ugyldig e-mail adresse';
$strForwardBlacklistedEmail = 'Modtageren har frabedt sig, at modtage e-mails fra systemet.';
$strForwardEnterEmails = 'Venligst indtast maks %s gyldige e-mail adresser til videresendelse, i denne boks - én pr. linie';
$strForwardPersonalNote = 'Du kan indtaste maks %d karakterer i klar tekst, som tilføjes den videresendte e-mail.';
$strForwardSuccessInfo ='Beskeden er blevet videresendt';
$strForwardFailInfo = 'Videresendelse af beskeden mislykkedes';
$strForwardAlreadyDone = 'Denne besked er allerede blevet videresendt til den e-mail adresse';
$strForwardCountReached = 'Maks antal e-mail adresser til videresendelse er nået';
$strForwardNoteLimitReached = 'Maksimum antal karakterer er nået';
$strForwardFooter = 'Denne besked er blevet videresendt til dig fra [FORWARDEDBY].
  Du er ikke automatisk blevet tilmeldt dette nyhedsbrev.
  For at tilmelde dig nyhedsbrevet gå til';
$strForward = 'Videresend';
$strFwd = 'FW'; # kort udgave af "videresend" i e-mailens emnefelt
