<?php

# language dependent text used in the interface for users (not admin)
# original translation by Gijsbert Rochat, update by Mike Rijken, 18/11/2002, review by Rudi Van Overloop, ruda@skynet.be 27/2/2004
# 
# Changed to current phplist version by SaWey 25/02/2007
# Reviewed and changed (corrected some major goofs) by Dennis Lutz Oct 4, 2007
# Reviewed and changed by Henk van Dijk (www.klussenpunt.nl) dev v 2.11.10 31/7/2013
# 

$strCharSet             = 'UTF-8';
$strName                = 'Naam';
$strAddress             = 'Adres';
$strEmail               = 'E-mail adres';
$strTown                = 'Plaats';
$strPostcode            = 'Postcode';
$strSubscribeInfo       = 'Meld u aan voor het regelmatig ontvangen van e-mail berichten door onderstaand formulier in te vullen';
$strRequired            = 'Rode tekst = verplicht veld';
$strSubscribeTitle      = 'Meld je aan voor een e-mail bericht';
$strPleaseSelect        = 'Selecteer de verzendlijst(en)';
$strSubmit              = 'Aanmelden bij de geselecteerde verzendlijst(en)';
$strNotAvailable        = 'Er zijn momenteel geen verzendlijsten beschikbaar';
$strEnterName           = 'Vul je naam in';
$strEnterEmail          = 'Vul een geldig e-mail adres in';
$strConfirmEmail        = 'E-mail adres nogmaals';
$strInvalidHostInEmail  = 'Er kan geen e-mail bericht naar dit e-mail adres worden verzonden, controleer of je het juiste e-mail adres hebt ingevuld';
$strEnterList           = 'Selecteer verzendlijst(en)';
$strPleaseEnter         = 'Vul het volgende veld nogmaals in:';
# the thanks message can contain placeholders
$strThanks              = 'Dank voor het aanmelden.';
# the EmailConfirmation message can contain placeholders
$strEmailConfirmation   = 'Je ontvangt binnen enkele ogenblikken een e-mail bericht ter bevestiging van de aanmelding. Vergeet niet op de link in het bericht te klikken, om de inschrijving af te ronden.';
$strEmailFailed         = 'Het verzenden van de bevestigingsmail is mislukt, klik op "Opnieuw laden" om opnieuw te verzenden. Als ook dat niet lukt, dan kan het zijn dat je op de "Zwarte lijst" staat, wat betekent dat je geen berichten kunt of wilt ontvangen. Neem in dat geval contact op met de beheerder.';
$strUnsubscribeTitle    = 'Afmelden';
$strUnsubscribeDone     = 'Je bent afgemeld bij de geselecteerde verzendlijst(en) en je ontvangt binnen enkele ogenblikken een e-mail bericht ter bevestiging.';
$strBack                = 'Terug';
$strUnsubscribeInfo     = 'Afmelden';
$strContinue            = 'Volgende';
$strUnsubscribeSelect   = 'Selecteer de verzendlijst(en) om bij af te melden.';
$strAllLists            = 'Alle verzendlijst(en)';
$strNoLists             = 'Geen enkele verzendlijst';
$strUnsubscribeRequestForReason = 'Jammer dat je niet langer onze e-mail berichten wilt ontvangen. Om onze diensten te verbeteren zouden we het fijn vinden als je ons wilt vertellen waarom:';
$strUnsubscribeFinalInfo = '<br/><strong>Let op</strong>: Je kunt je hier <strong>afmelden</strong> voor het ontvangen van onze e-mail berichten. Als je het e-mail adres wilt wijzigen of je wilt inschrijven bij een andere verzendlijst, klik dan <a href="[PREFERENCESURL]">hier</a> om de persoonlijke instellingen te wijzigen';
$strNoListsFound        = 'Sorry, dit e-mail adres is niet bekend.';
$strResubmit            = 'Voer het e-mail adres nogmaals in';
$strUnsubscribeSubmit   = 'Afmelden bij de geselecteerde verzendlijst(en)';
$strValuesMissing       = 'De volgende verplichte velden zijn niet ingevuld';
$strConfirmInfo         = 'Dank je voor het bevestigen van de aanmelding. De verzendlijst(en) waarop je bent geabonneerd wordt hieronder weergegeven';
$strConfirmTitle        = 'Bevestiging inschrijving verzendlijst(en)';
$strUserNotFound        = 'Gebruiker niet gevonden';
$strUserAlreadyInitialised = 'Sorry, het wachtwoord is al ingesteld';
$strConfirmFailInfo     = 'Sorry, je bevestiging werd niet herkend. Zorg er voor dat je het volledige web adres volgt zoals vermeld in het e-mail bericht welke je hebt ontvangen. Soms beslaat deze URL meerdere regels. Plak in dat geval de twee regels aan elkaar in de adresbalk van de internetbrowser.';
$strPreferHTMLEmail     = 'Ik geef de voorkeur aan het ontvangen van e-mail berichten met HTML opmaak.';
$strPreferTextEmail     = 'Ik geef de voorkeur aan het ontvangen van e-mail berichten met Tekst opmaak.';
$strPreferredFormat     = 'In welke opmaak wil je onze e-mail berichten ontvangen?';
$strText                = 'Tekst opmaak';
$strHTML                = 'HTML opmaak';
$strPreferencesTitle    = 'Vernieuw de instellingen';
$strPreferencesInfo     = 'Als de informatie hieronder correct is kun je op de knop "Wijzig" klikken om de gegevens te bewaren';
$strUpdatePreferences   = 'Wijzig';
$strPreferencesEmailChanged = 'Uw e-mail adres is gewijzigd. Klik op de link in het e-mail bericht die je zo meteen ontvangt om de wijziging te bevestigen.';
$strYouAreBlacklisted = 'Je e-mail adres staat op onze "Zwarte lijst", dit betekent dat wij geen e-mail berichten meer sturen. <br/>
Om opnieuw e-mail berichten van ons te ontvangen is tussenkomst van de administrator vereist. Neem contact op met ons en vermeld dat je opnieuw e-mail berichten wilt ontvangen en wij zullen u dan van de Zwarte lijst halen.';
$strPreferencesNotificationSent = 'Je ontvangt een e-mail bericht met de wijzigingen';
$strPreferencesUpdated = 'Wij hebben de instellingen aangepast.';
$strClickHere          = 'Klik hier';
$strThisLink           = 'deze link';
$strToUnsubscribe      = 'Om je van de verzendlijst(en) af te melden bezoek: ';
$strToUpdate           = 'Om je voorkeuren te wijzigen bezoek: ';
$strSendHTML           = 'Verstuur e-mail berichten met HTML opmaak';
$strYes                = 'Ja';
$strNo                 = 'Nee';
$strUnsubscribe        = 'Afmelden';
$strAllMailinglists    = 'Alle nieuwsbrieven';
$strAttachmentIntro    = 'Dit bericht bevat bijlagen die in een webbrowser kunnen worden weergegeven:';
$strLocation           = 'Locatie';
$strFrequency          = 'Hoe vaak zenden berichten';
$strHourly             = 'Ieder uur';
$strDaily              = 'Iedere dag';
$strWeekly             = 'Iedere week';
$strMonthly            = 'Iedere maand';
$strChoosePassword     = 'Kies een wachtwoord';
$strConfirmPassword    = 'voer het wachtwoord opnieuw in';
$strEnterPassword      = 'Voer het wachtwoord in';
$strForgotPassword     = 'Wachtwoord Vergeten';
$strPassword           = 'Wachtwoord';
$strPassword2          = 'Voer het wachtwoord opnieuw in';
$strPasswordsNoMatch   = 'De wachtwoorden komen niet overeen';
$strEmailsNoMatch      = 'De ingevoerde e-mail adressen zijn niet hetzelfde';
$strInvalidPassword    = 'FOUT: ongeldig e-mail adres of wachtwoord';
$strPasswordSent       = 'Het wachtwoord is naar je e-mail adres verzonden. Je zult het over enkele ogenblikken ontvangen';
$strPasswordRemindSubject = 'Het wachtwoord voor onze verzendlijst(en)';
$strPasswordRemindMessage = 'Het wachtwoord is';
$strPasswordRemindInfo = 'Om het wachtwoord per e-mail bericht te ontvangen, voer het e-mail adres in en klik op de "'.$strForgotPassword.'" knop.';
$strLogin              = 'Inloggen';
$strLoginTitle         = 'Vul het e-mail adres en wachtwoord in';
$strLoginInfo          = 'Deze pagina vereist een wachtwoord. Vul het e-mail adres en wachtwoord in';
$strPersonalLocationInfo = '
  <p>Deze pagina vereist een persoonlijke identificatie welke je terug kunt vinden in elk e-mail bericht die we sturen.<br/>
  Kijk nog eens goed de juiste URL in je browser na wanneer je een foutmelding ontvangt.
  De URL kan soms over twee tekstregels verdeeld zijn.</p>
  <p>Wanneer je de URL niet kan terugvinden, kun je deze eenvoudig per e-mail aanvragen.
  Vul je e-mail adres in en klik op "Continue"';
$strPersonalLocationSent = '<h1>Gefeliciteerd! Je zult binnen enkele ogenblikken een bericht ontvangen met een overzicht van de persoonlijke instellingen.</h1>';
$strUserExists   = '<br/>Een gebruiker met deze email bestaat reeds, met een ander wachtwoord';
$strUserExistsExplanationStart = '<br/>Om je wachtwoord te ontvangen, klik';
$strUserExistsExplanationLink = 'hier';
$strUserExistsExplanationEnd = ' om naar de pagina te gaan waar je jouw persoonlijke locatie kunt aanvragen';
$strForwardTitle = 'Stuur een bericht door aan iemand';
$strForwardSubtitle = 'Bericht wordt doorgestuurd met het volgende onderwerp';
$strForwardEnterEmail = 'Voer een e-mail adres in om het bericht naar door te sturen';
$strForwardSuccessInfo ='Het bericht is doorgestuurd';
$strForwardFailInfo = 'Het doorsturen van het bericht is mislukt';
$strForwardAlreadyDone = 'Dit bericht is al met succes doorgestuurd naar dat adres';
$strForwardFooter = 'Dit bericht is doorgestuurd naar u door [FORWARDEDBY].
  U bent niet automatisch toegevoegd aan onze verzendlijst(en).
  Om in te schrijven bij deze verzendlijst(en), ga naar';
$strForward = 'Stuur door';
$strFwd = 'Fwd'; # short version of forward for email subject
?>