<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strName                = 'Name';
$strAddress             = 'Address';
$strEmail               = 'Email';
$strTown                = 'Town';
$strPostcode            = 'Postcode';
$strSubscribeInfo       = 'Subscribe to one or more of our newsletters using the form below';
$strRequired            = 'All field with labels in red text are required fields.';
$strSubscribeTitle      = 'Subscribe to our Newsletters';
$strPleaseSelect        = 'Please select the newsletters you would like to sign up for';
$strSubmit              = 'Subscribe to the Selected Newsletters';
$strNotAvailable        = 'Sorry, there currently aren\'t any newsletters available';
$strEnterName           = 'Please enter your name';
$strEnterEmail          = 'Please enter your email address';
$strInvalidHostInEmail  = 'Sorry, email to that domain are undeliverable.  Please check that you typed the email address correctly';
$strEnterList           = 'Please select a newsletter to subscribe to';
$strPleaseEnter         = 'Please enter your';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Thank you for subscribing to our newsletters.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your email [email] has been added to our system.  Shortly, you will be e-mailed with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Your email has been added to our system.  Shortly, you will be e-mailed with a request to confirm your membership. Please make sure to click the link in that message to confirm your subscription.';
$strEmailFailed          = 'Sorry.  Sending the email to request your confirmation failed.  Please click "Reload" (or the "BACK" button on your browser) to try again.  If it still does not work, it may be because you are inadvertantly on an exclusionary list; which means that you cannot receive emails from our newsletter system.  If you receive this message again, please contact our administrator at:  onlinesubscriptionmanager@***.com.  We will investigate and re-contact you.';
$strUnsubscribeTitle    = 'Unsubscribe from our Newletters';
$strUnsubscribeDone     = 'You have been unsubscribed from our newsletters, and you will receive confirmation of that, by email, very soon.';
$strBack                = 'Back';
$strUnsubscribeInfo     = 'Unsubscribe from our newsletters';
$strContinue            = 'Continue';
$strUnsubscribeSelect   = 'Please select the newsletters you want to unsubscribe from';
$strAllLists            = 'All Lists';
$strNoLists             = 'None of them';
$strUnsubscribeRequestForReason = 'We are sorry to find out you no longer wish to receive our newsletter.  To help us improve our services, we would be grateful if you could tell us why: ';
$strUnsubscribeFinalInfo = '<br/><b>Please note</b>: this page will stop receiving emails from our newsletter system <b>forever</b>. If you want to change your email, or if you want to change which newsletters you receive, please <a href="[PREFERENCESURL]">update your preferences</a> instead';
$strNoListsFound        = 'Sorry, you are not subscribed to any of our newsletters using this email';
$strResubmit            = 'Re-Submit Email';
$strUnsubscribeSubmit   = 'Unsubscribe from the Selected Newsletters';
$strValuesMissing       = 'The following required values are missing';
$strConfirmInfo         = 'Thank you for confirming your subscription to our newsletters.  The newsletters you are subscribed to are listed below';
$strConfirmTitle        = '***.com Online Subscription Membership Confirmation Page';
$strUserNotFound        = 'User not found';
$strUserAlreadyInitialised = 'Sorry, your password has already been set';
$strConfirmFailInfo     = 'Sorry, your request for confirmation was not recognized. Please make sure you used the full web address as mentioned in the email that you received. Sometimes this web address wraps onto multiple lines.';
$strPreferHTMLEmail     = 'I prefer to receive emails in HTML format';
$strPreferTextEmail     = 'I prefer to receive emails in Text format';
$strPreferredFormat      = 'Preferred format for emails:';
$strText                 = 'Text';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Update your preferences';
$strPreferencesInfo     = 'Please confirm that the information below is correct, and then click the "Update" button';
$strUpdatePreferences   = 'Update';
$strPreferencesEmailChanged = 'Your email has changed. Please visit the link in the email you will receive shortly, to confirm your new email address';
$strYouAreBlacklisted = 'For some reason, your email is listed in one of our exclusionary lists, which means you have requested of us that we never send you any more newsletters. <br/>
In order to receive emails again, manual intervention is required by our administrator. Please contact that manager (at onlinesubscriptionmanager@***.com), stating explicitly that you want to receive newsletters again.  We will investigate and re-contact you. ';
$strPreferencesNotificationSent = 'You will receive an email with the changes';
$strPreferencesUpdated = 'Thank you for your submission.  We have updated your information.';
$strClickHere          = 'Click Here';
$strThisLink           = 'this link';
$strToUnsubscribe      = 'If you do not wish to receive newsletters any longer, ';
$strToUpdate           = 'To update your preferences and to unsubscribe, please visit';
$strSendHTML           = 'Send HTML email';
$strYes                = 'Yes';
$strNo                 = 'No';
$strUnsubscribe        = 'Unsubscribe';
$strAllMailinglists    = 'All newsletters';
$strAttachmentIntro     = 'This message contains attachments that can be viewed with a web browser:';
$strLocation           = 'Location';
$strFrequency           = 'How often do we send you messages';
$strHourly             = 'Hourly';
$strDaily               = 'Daily';
$strWeekly             = 'Weekly';
$strMonthly             = 'Monthly';
$strChoosePassword      = 'Please choose a password';
$strConfirmPassword    = 'Confirm your password';
$strEnterPassword       = 'Please enter your password';
$strForgotPassword     = 'Forgot Password';
$strPassword           = 'Password';
$strPassword2           = 'Confirm Password';
$strPasswordsNoMatch    = 'Those passwords are not the same';
$strEmailsNoMatch     = 'The Email Addresses you entered do not match';
$strInvalidPassword     = 'Error:  invalid email or password';
$strPasswordSent        = 'Your password has been sent to the email address on record with us for your account.  You should receive it via email in the next few minutes';
$strPasswordRemindSubject = 'Your password for our newsletters';
$strPasswordRemindMessage = 'Your password is ';
$strPasswordRemindInfo = 'To receive your password by email, please enter your email and click the "'.$strForgotPassword.'" button.';
$strLogin               = 'Login';
$strLoginTitle          = 'Please enter your email address and password';
$strLoginInfo           = 'This page requires a password.  Please enter your email address and password';
$strPersonalLocationInfo = '
  <p>This page requires a personal identification that can be found on each email that we send to you.<br/>
  If you have clicked this location, and you get this error, please make sure to paste the entire link (address line) into the address or URL address box of your browser.  Sometimes the location is wrapped over several lines.  If that happens, you need to remove those line breaks when you paste it into your browser.</p>
  <p>If you do not know the location, you can request an email that will tell you what it is.  Please enter your email in the box and click "Continue".
';
$strPersonalLocationSent = '<h1>Success!  You should receive a message with your personal location shortly.</h1>';
$strUserExists   = '<br/>A user with that email already exists in our records, and those records contain a different password';
$strUserExistsExplanationStart = '<br/>In order to obtain your password, click ';
$strUserExistsExplanationLink = 'here';
$strUserExistsExplanationEnd = ' to go to the page where you can request your personal location';
$strForwardTitle = 'Forward a Message to Someone';
$strForwardSubtitle = 'Forwarding the message with subject ';
$strForwardEnterEmail = 'Please enter a valid email address to forward to';
$strForwardSuccessInfo ='The message has been forwarded';
$strForwardFailInfo = 'Forwarding the message failed';
$strForwardAlreadyDone = 'This message has already been forwarded successfully to that email address';
$strForwardFooter = 'This message has been forwarded to you by [FORWARDEDBY].
 You have NOT been automatically subscribed to this newsletter.
  To subscribe to this newsletter go to';
$strForward = 'Forward';
$strFwd = 'Fwd'; # short version of forward for email subject
?>
