<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strName                = 'Nimi';
$strAddress             = 'Aadress';
$strEmail               = 'Email';
$strTown                = 'Linn';
$strPostcode            = 'Postikood';
$strSubscribeInfo       = 'Liitu ühe või enamaga meie uudiskirjadest täites väljad allpool';
$strRequired            = 'nõutav väli';
$strSubscribeTitle      = 'Liitu meie uudiskirjadega';
$strPleaseSelect        = 'Please select the newsletters you want to sign up to';
$strSubmit              = 'Liitu valitud uudiskirjadega';
$strNotAvailable        = 'Vabandame, hetkel pole ühtegi uudiskirja saadaval';
$strEnterName           = 'Palun sisesta oma nimi';
$strEnterEmail          = 'Palun sisesta oma e-maili aadress';
$strInvalidHostInEmail  = 'Kahjuks ei ole võimalik e-maili sellele domeenile toimetada, palun kontrolli, et aadress on õige';
$strEnterList           = 'Palun vali uudiskiri, mida soovid tellida';
$strPleaseEnter         = 'Palun sisesta oma';
# the thanks message can contain placeholders
#$strThanks              = 'Hea [FIRST NAME], <br/>Täname, et liitusid meie uudiskirjaga.';
$strThanks              = 'Täname, et liitusid meie uudiskirjaga.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Sinu e-mail [email] on lisatud süsteemi. Sulle saadetakse peatselt kiri, milles pead oma e-maili aadressi kinnitama.';
$strEmailConfirmation   = 'Sinu e-mail on lisatud süsteemi. Sulle saadetakse peatselt kiri, milles pead oma e-maili aadressi kinnitama vajutades kirja lõpus olevale lingile.';
$strEmailFailed          = 'Kahjuks ebaõnnestus kinnituskirja saatmine sinu aadressile, palun kliki "Reload/Refresh" et proovida uuesti. Kui see ikkagiei õnnestu, võib see aadress kuuluda "Musta nimekirja", mis tähendab, et sellele aadressile käesolev süsteem kirju saata ei saa. Sel juhul, palun võta ühendust süsteemi administraatoriga..';
$strUnsubscribeTitle    = 'Uudiskirjade tellimuse lõpetamine';
$strUnsubscribeDone     = 'Sind on eemaldatud meie uudiskirjadest. Saad sellekohase teate ka oma e-mailile.';
$strBack                = 'Tagasi';
$strUnsubscribeInfo     = 'Uudiskirjade tellimuse lõpetamine';
$strContinue            = 'Jätka';
$strUnsubscribeSelect   = 'Palun vali Uudiskiri, mille tellimuse soovid lõpetada';
$strAllLists            = 'Kõik listid';
$strNoLists             = 'Mitte ükski';
$strUnsubscribeRequestForReason = 'Meil on kahju kuulda, et soovid lõpetada meie uudiskirja tellimust. Et me saaks oma teenust parandada, palun kirjuta miks soovid lahkuda:';
$strUnsubscribeFinalInfo = '<br/><b>Pane tähele</b>: see leht on uudiskirjade tellimuse lõpetamiseks <b>jäädavalt</b>. Kui soovid muuta oma e-maili või soovid muuta tellitavat uudiskirja, palun <a href="[PREFERENCESURL]">uuenda oma eelistusi</a> siin';
$strNoListsFound        = 'See e-mail ei ole registreeritud saama ühtegi uudiskirja';
$strResubmit            = 'Saada uuesti Email';
$strUnsubscribeSubmit   = 'Lõpeta valitud uudiskirjade tellimus';
$strValuesMissing       = 'Järgmised nõutavad väljad on puudu';
$strConfirmInfo         = 'Teie uudiskirja tellimus on kinnitatud. Olete lisatud järgnevate uudiskirjade saajate nimistusse';
$strConfirmTitle        = 'PHPlist liikmestaatuse kinnitamise leht';
$strUserNotFound        = 'Ei leia sellist kasutajat';
$strUserAlreadyInitialised = 'Vabandame, teie salasõna on juba välja saadetud';
$strConfirmFailInfo     = 'Vabandame, teie soov tellimuse kinnitamiseks ei läinud läbi. Palun kasutage tervet URL aadressi, mis toodud Teile saadetud e-mailis. that you received. Mõnikord poolitatakse see URL aadress mitmele reale.';
$strPreferHTMLEmail     = 'Eelistan saada E-maile HTML formaadis';
$strPreferTextEmail     = 'Eelistan saada e-maile Teksti-formaadis';
$strPreferredFormat      = 'E-mailide eelistatav formaat:';
$strText                 = 'Tekst';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Uuenda oma eelistusi';
$strPreferencesInfo     = 'Palun kinnita, et allolev info on õige ning vajuta nuppu "Uuenda"';
$strUpdatePreferences   = 'Uuenda';
$strPreferencesEmailChanged = 'Sinu e-mail on muudetud. Palun vaata oma uue e-maili postkasti, leiad sealt kirja, milles palutakse uus e-mail kinnitada';
$strYouAreBlacklisted = 'Sinu e-mail sisaldub "Mustas nimekirjas", mis tähendab, et oled soovinud, et sulle ei saadetaks enam uudiskirju. <br/>
Et kirju uuesti saada, on vajalik administraatori sissekanne. Palun võta meie süsteemi adminsitraatoriga ühendust ning väljenda oma soovi saada taas uudikirju. Seejärel eemaldatakse sinu aadress "mustast nimekirjast". ';
$strPreferencesNotificationSent = 'Sulle saadetakse e-mail muudatustega';
$strPreferencesUpdated = 'Täname. Uuendasime sinu andmeid.';
$strClickHere          = 'Kliki siin';
$strThisLink           = 'seda linki';
$strToUnsubscribe      = 'Kui sa ei soovi saada enam uudiskirju, ';
$strToUpdate           = 'Uuendada oma eelistusi';
$strSendHTML           = 'Saada HTML email';
$strYes                = 'Jah';
$strNo                 = 'Ei';
$strUnsubscribe        = 'Lõpeta tellimus';
$strAllMailinglists    = 'Kõik uudiskirjad';
$strAttachmentIntro     = 'See kiri sisaldab manuseid, mida saab vaadata veebirauseriga:';
$strLocation           = 'Asukoht';
$strFrequency           = 'Kui tihti võime saata sulle kirju';
$strHourly             = 'Iga tund';
$strDaily               = 'Iga päev';
$strWeekly             = 'Iga nädal';
$strMonthly             = 'Iga kuu';
$strChoosePassword      = 'Palun vali salasõna';
$strConfirmPassword    = 'Trüki salasõna uuesti';
$strEnterPassword       = 'Sisesta salasõna';
$strForgotPassword     = 'Unustasid salasõna';
$strPassword           = 'Salasõna';
$strPassword2           = 'Salasõna uuesti';
$strPasswordsNoMatch    = 'Salasõnad ei ühti';
$strEmailsNoMatch     = 'E-maili aadressid, mis sisestasid, ei ühti';
$strInvalidPassword     = 'Viga: vigane e-mail või salasõna';
$strPasswordSent        = 'Sinu salasõna saadeti sulle e-maili teel';
$strPasswordRemindSubject = 'Sinu salasõna meie uudiskirjade juurde';
$strPasswordRemindMessage = 'Sinu salasõna on ';
$strPasswordRemindInfo = 'Et saada salasõna oma e-maili peale, palun sisesta oma e-mail ning vajuta "'.$strForgotPassword.'" nuppu.';
$strLogin               = 'Logi sisse';
$strLoginTitle          = 'Palun sisesta oma e-maili aadress ja salasõna';
$strLoginInfo           = 'See leht vajab salasõna.Palun sisesta oma e-mail ja salasõna';
$strPersonalLocationInfo = '
  <p>See leht vajab personaalset identifitseerimist paroolidega, millised oleme Teile saatnud.<br/>
  Kui te olete selle veateate saanud, veenduga et brauseri aadressireale on sisestatud terve URL aadress, millise saite e-mailiga. Mõnikord poolitab e-mail selle aadressi mitmele reale.</p>
  <p>Kui te ei tea täpset aadressi, võite taas paluda saata oma postkasti e-maili, kus on täpsed juhised.
  Palun sisestage oma e-mail allolevase kasti ning klikake "Jätka"
';
$strPersonalLocationSent = '<h1>Edu! Saate e-maili peatselt, kus on toodud vajaminev URL aadress.</h1>';
$strUserExists   = '<br/>Kasutaja sellise e-mailiga on juba olemas, temal on teistsugune salasõna';
$strUserExistsExplanationStart = '<br/>Et saada oma salasõna, klikake ';
$strUserExistsExplanationLink = 'siia';
$strUserExistsExplanationEnd = ' et minna lehele, kust küsida vajaminev URL aadress';
$strForwardTitle = 'Edasta see kiri kellelegi';
$strForwardSubtitle = 'Edasta kiri teemareaga';
$strForwardEnterEmail = 'Palun sisesta kehtiv e-maili aadress, kuhu edastada';
$strForwardSuccessInfo ='Kiri on edastatud';
$strForwardFailInfo = 'Kirja edastamine ebaõnnestus';
$strForwardAlreadyDone = 'See kiri on juba varem edukalt edastatud sellele aadressile';
$strForwardFooter = 'See kiri on edastatud sulle [FORWARDEDBY] poolt.
  Sa ei ole automaatselt lisatud käesoleva uudiskirja tellijate hulka.
  Et tellida see uudiskiri, mine ';
$strForward = 'Edasta';
$strFwd = 'Fwd'; # short version of forward for email subject
?>