<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strName                = 'Nimi';
$strAddress             = 'Osoite';
$strEmail               = 'Sähköposti';
$strTown                = 'Kaupunki';
$strPostcode            = 'Postinumero';
$strSubscribeInfo       = '<h1>Tilaa uutiskirje</h1>';
$strRequired            = 'Värilli merkityt kentät ovat pakollisia';
$strSubscribeTitle      = 'Tilaa uutiskirje';
$strPleaseSelect        = 'Valitse uutiskirje, jonka haluat tilata';
$strSubmit              = 'Tilaa valittu uutiskirje';
$strNotAvailable        = 'Uutiskirjeitä ei ole saatavilla';
$strEnterName           = 'Ole hyvä ja kirjoita nimesi';
$strEnterEmail          = 'Ole hyvä ja kirjoita sähköpostiosoite';
$strConfirmEmail        = 'Vahvista sähköpostiosoitteesi';
$strInvalidHostInEmail  = 'Virhe! Tarkista sähköpostiosoite';
$strEnterList           = 'Valitse uutiskirje, jonka haluat tilata';
$strPleaseEnter         = 'Ole hyvä ja kirjoita nimesi';
# the thanks message can contain placeholders
#$strThanks              = 'Hei [FIRST NAME], <br/>kiitos tilauksesta.';
$strThanks              = 'Kiitos tilauksesta.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Sähköpostiosoitteesi [email] on lisätty postituslistalle. Saat kohta vahvistuksen antamaasi sähköpostiosoitteeseen.';
$strEmailConfirmation   = 'Sähköpostiosoitteesi [email] on lisätty postituslistalle. Saat kohta vahvistuslinkin antamaasi sähköpostiosoitteeseen. Uutiskirjeen voi tilata vain toimivaan sähköpostiosoitteseen, joten vahvistuviestillä varmistamme antamasi osoitteen toimivaksi. Ole hyvä ja klikkaa postissa olevaa vahvistuslinkkiä';
$strEmailFailed          = 'Virhe! Vahvistussähköpostia ei voitu lähettää antamaasi osoitteeseen. Ole hyvä ja yritä uudelleen. Jos tilaaminen ei onnistu, niin ota yhteyttä järjestelmän ylläpitäjään';
$strUnsubscribeTitle    = 'Peruuta uutiskirje';
$strUnsubscribeDone     = 'Uutiskirje on peruutettu. Saat sähköpostiisi vahvistusviestin.';
$strBack                = 'Takaisin';
$strUnsubscribeInfo     = 'Peruuta uutiskirje';
$strContinue            = 'Jatka';
$strUnsubscribeSelect   = 'Ole hyvä ja valitse uutiskirje, jonka haluat peruuttaa';
$strAllLists            = 'Kaikki listat';
$strNoLists             = 'Ei mitään näistä';
$strUnsubscribeRequestForReason = 'Voit halutessasi antaa palautetta, miksi et halua enää lukea uutiskirjettämme. Voimme näin parantaa palveluamme:';
$strUnsubscribeFinalInfo = '<br/><b>Huomio!</b>: Tällä sivulla peruutat uutiskirjeen <b>lopullisesti</b> ja sähköpostiosoitteesi poistetaan järjestelmästä. Jos haluat muuttaa sähköpostiosoitetta, voit päivittää yhteystietojasi <a href="[PREFERENCESURL]">täältä</a>';
$strNoListsFound        = 'Sähköpostiosoitetta ei löytynyt järjestelmästä';
$strResubmit            = 'Anna sähköpostiosoite uudelleen';
$strUnsubscribeSubmit   = 'Peruuta valittu uutiskirje';
$strValuesMissing       = 'Seuraavat tiedot puuttuvat';
$strConfirmInfo         = 'Kiitos uutiskirjeen tilauksesta. Alla on listattu tilatut uutiskirjeet';
$strConfirmTitle        = 'Jäsenyyden vahvistussivu';
$strUserNotFound        = 'Käyttäjää ei löytynyt';
$strUserAlreadyInitialised = 'Virhe! Salasanasi on jo asetettu';
$strConfirmFailInfo     = 'Virhe, vahvistustasi ei pystytty tunnistamaan. Ole hyvä ja tarkasta, että käytät koko osoitetta, joka on sähköpostissa mainittu.';
$strPreferHTMLEmail     = 'Tilaan uutiskirjeen HTML -muodossa';
$strPreferTextEmail     = 'Tilaan uutiskirjeen teksti -muodossa';
$strPreferredFormat      = 'Uutiskirjeen muoto:';
$strText                 = 'Teksti';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Päivitä yhteystietosi';
$strPreferencesInfo     = 'Ole hyvä ja tarkista, että alla olevat tiedot ovat oikein ja paina "päivitä" -nappia';
$strUpdatePreferences   = 'Päivitä';
$strPreferencesEmailChanged = 'Sähköpostiosoitteesi on päivitetty. Saat kohta uuteen sähköpostisoitteeseen linkin, josta voit vahvistaa uuden sähköpostiosoitteen';
$strYouAreBlacklisted = 'Sähköpostiosoitteesi on merkitty järjestelmässämme "mustalle listalle". Tämä tarkoittaa sitä, että sähköpostiosoitteeseen ei tulla koskaan lähettämään järjestelmästämme postia.<br/>
Jos haluat vastaanottaa uutiskirjeitämme, niin ole hyvä ja ota yhteyttä järjestelmän ylläpitäjään.';
$strPreferencesNotificationSent = 'Saat sähköpostin muutoksista.';
$strPreferencesUpdated = 'Kiitos. Tietosi on päivitetty';
$strClickHere          = 'Klikkaa tästä';
$strThisLink           = 'tätä linkkiä';
$strToUnsubscribe      = 'Jos haluat peruutta uutiskirjeen, ';
$strToUpdate           = 'Yhteystietojen päivitys ja uutiskirjeen peruutus';
$strSendHTML           = 'Lähetä HTML sähköposti';
$strYes                = 'Kyllä';
$strNo                 = 'Ei';
$strUnsubscribe        = 'Peruuta uutiskirje';
$strAllMailinglists    = 'Kaikki uutiskirjeet';
$strAttachmentIntro     = 'Tämä posti sisältää liitteen, jonka voi avata internetselaimella:';
$strLocation           = 'Paikka';
$strFrequency           = 'Kuinka usein uutiskirje lähetetään';
$strHourly             = 'Tunnin välein';
$strDaily               = 'Päivittäin';
$strWeekly             = 'Viikottain';
$strMonthly             = 'Kuukausittain';
$strChoosePassword      = 'Ole hyvä ja anna salasana';
$strConfirmPassword    = 'Vahvista salasana';
$strEnterPassword       = 'Ole hyvä ja anna salasana';
$strForgotPassword     = 'Unohtuiko salasana?';
$strPassword           = 'Salasana';
$strPassword2           = 'Vahvista salasana';
$strPasswordsNoMatch    = 'Annetut salasanat eivät täsmää';
$strEmailsNoMatch     = 'Annetut sähköpostiosoitteet eivät täsmää';
$strInvalidPassword     = 'Virhe! Virheellinen salasana tai sähköpostiosoite';
$strPasswordSent        = 'Salasanasi on lähetetty sähköpostisoitteeseesi. Saat viestin muutaman minuutin päästä';
$strPasswordRemindSubject = 'Salasanasi uutiskirjeeseen';
$strPasswordRemindMessage = 'Salasanasi on ';
$strPasswordRemindInfo = 'Lähetä salasanasi antamalla sähköpostiosoitteesi ja klikkaa "'.$strForgotPassword.'" -nappia.';
$strLogin               = 'Kirjaudu';
$strLoginTitle          = 'Ole hyvä ja anna sähköpostisoitteesi ja salasana';
$strLoginInfo           = 'Tämä sivu vaatii salasanan. Ole hyvä ja anna sähköpostisoitteesi ja salasana';
$strPersonalLocationInfo = '
  <p>Tämä sivu vaatii henkilökohtaisen indentifikoinnin, joka löytyy jokaisesta postista, jonka olet meiltä vastaanottanut.<br/>
  Jos olet klikannut tähän paikkaan ja saat tämän virheilmoituksen, ole hyvä ja tarkasta, että kopioit koko rivin huolellisesti selaimesi.</p>
  <p>Jos et tiedä mitä olet kopioimassa, niin ole hyvä anna sähköpostisoitteesi ja klikkaa "jatka"
';
$strPersonalLocationSent = '<h1>Onnistui!</h1>';
$strUserExists   = '<br/>Käyttäjänimi on jo järjestelmässä, mutta eri salasanalla.';
$strUserExistsExplanationStart = '<br/>Palauttaaksesi salasanan, klikkaa ';
$strUserExistsExplanationLink = 'tästä';
$strUserExistsExplanationEnd = ' mennäksesi sivulle, jossa voit tehdä henkilökohtaisen paikkapyynnön';
$strExplainBlacklist = 'Tähän syötetty sähköpostiosoite lisätään järjestelmään "mustalle listalle" ja tähän sähköpostiosoitteeseen ei lähetetä enää posteja.';
$strForwardTitle = 'Välitä viesti';
$strForwardSubtitle = 'Välitä viesti otsikolla ';
$strForwardEnterEmail = 'Ole hyvä ja anna toimiva sähköpostiosoite, johon viesti välitetään';
$strForwardInvalidEmail = '%s ei ole validi sähköpostiosoite';
$strForwardBlacklistedEmail = 'Vastaanottajalla ei ole mahdollisuutta vastaanottaa järjestelmämme viestejä';
$strForwardEnterEmails = 'Ole hyvä ja anna maksimimäärä %s välittääksesi posti. Yksi sähköpostiosoite kullekkin riville.';
$strForwardPersonalNote = 'Voit syöttää tekstiä (maksimissaan %d merkkiä), joka lisätään viestiin';
$strForwardSuccessInfo ='Viesti on välitetty';
$strForwardFailInfo = 'Välitettyä viestiä ei voida lähettää';
$strForwardAlreadyDone = 'Tämä viesti on jo välitetty onnistuneesti annettuun sähköpostiosoitteeseen';
$strForwardCountReached = 'Sallittu välitysten maksimimäärä saavutettu';
$strForwardNoteLimitReached = 'Tekstin maksimimäärä saavutettu';
$strForwardFooter = '[FORWARDEDBY] on välittänyt sinulle tämän viesin.
  Jos haluat tilata tämän uutiskirjeen, ole hyvä ja klikkaa ';
$strForward = 'Jatka';
$strFwd = 'Fwd'; # Viestin otsikko


?>
