<?php
# language dependent text used in the interface for users (not admin)
# translation by Gijsbert Rochat, updated by Jean-Luc Picard

$strCharSet             = 'UTF-8';
$strName                = 'Nom';
$strAddress             = 'Adresse';
$strEmail               = 'Entrez votre adresse e-mail (courriel) <b>:</b>';
$strTown                = 'Ville';
$strPostcode            = 'Code postal';
$strSubscribeInfo       = 'S\'abonner &agrave; une ou plusieurs listes en utilisant ce formulaire :';
$strRequired            = '<b>Champ requis :</b>';
$strSubscribeTitle      = 'S\'abonner &agrave; nos listes';
$strPleaseSelect        = 'Veuillez s&eacute;lectionner les listes auxquelles vous d&eacute;sirez vous abonner ';
$strSubmit              = 'S\'abonner aux listes s&eacute;lectionn&eacute;es';
$strNotAvailable        = 'D&eacute;sol&eacute;, aucune nouvelle liste n\'est disponible pour le moment.';
$strEnterName           = 'Entrez votre nom :';
$strEnterEmail          = 'Entrez votre adresse de courriel (e-mail)';
$strConfirmEmail        = 'Confirmez cette adresse <b>:</b>';
$strInvalidHostInEmail  = 'D&eacute;sol&eacute;, aucun h&ocirc;te n\'a &eacute;t&eacute; trouv&eacute; pour envoyer votre courriel. Veuillez v&eacute;rifier votre adresse e-mail';
$strEnterList           = 'Veuillez s&eacute;lectionner une liste pour vous abonner :';
$strPleaseEnter         = 'Veuillez entrer votre';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Merci de vous &ecirc;tre abonn&eacute;(e) &agrave; nos listes.';
# the EmailConfirmation message can contain placeholders
#
$strEmailConfirmation   = 'Votre adresse de courrier est enregistr&eacute;e. Vous allez recevoir un message vous demandant de confirmer votre abonnement. Il vous faudra confirmer votre abonnement en cliquant sur le lien qui sera contenu dans le message.';
$strEmailFailed    = 'D&eacute;sol&eacute;, l\'envoi du message de confirmation a &eacute;chou&eacute;. Veuillez actualiser la page pour r&eacute;essayer.';
$strUnsubscribeTitle    = 'Se d&eacute;sabonner de nos listes';
$strUnsubscribeDone     = 'Vous avez &eacute;t&eacute; d&eacute;sabonn&eacute;(e) des listes choisies. Vous recevrez un message de confirmation.';
$strBack                = 'Retour';
$strUnsubscribeInfo     = 'Se d&eacute;sabonner d\'une ou de plusieurs de nos listes';
$strContinue            = 'Continuer';
$strUnsubscribeSelect   = 'S&eacute;lectionnez les listes auxquelles vous d&eacute;sirez vous d&eacute;sabonner';
$strAllLists            = 'Toutes les listes';
$strNoLists             = 'Aucune liste';
$strUnsubscribeRequestForReason = 'nous sommes d&eacute;sol&eacute;s de constater que vous ne souhaitez plus recevoir nos messages. Afin de nous aider &agrave; am&eacute;liorer nos services, pourriez-vous nous en pr&eacute;ciser les raisons ? :';
$strUnsubscribeFinalInfo = '<br/><b>Note</b>: Cette page est une page de d&eacute;sinscription <b>d&eacute;finitive</b> de nos listes. Si vous d&eacute;sirez changer votre adresse Couriel ou modifier les listes auquels vous souscrivez, S.V.P. utilisez le lien <a href="[PREFERENCESURL]">Mise &agrave; jour</a>';
$strNoListsFound        = 'D&eacute;sol&eacute;, votre adresse e-mail ne correspond &agrave; aucun abonnement.';
$strResubmit            = 'Envoyer une deuxi&egrave;me fois le courriel';
$strUnsubscribeSubmit   = 'Se d&eacute;sabonner des listes s&eacute;lectionn&eacute;es';
$strValuesMissing       = 'Les entr&eacute;es requises suivantes manquent :';
$strConfirmInfo         = 'Merci de vous &ecirc;tre abonn&eacute;(e) &agrave; nos listes. Les listes auxquelles vous vous &ecirc;tes abonn&eacute;(e) sont list&eacute;es ci-dessous :';
$strConfirmTitle        = 'Page de confirmation pour membres de PHPlist';
$strUserNotFound        = 'Destinataire introuvable';
$strUserAlreadyInitialised = 'D&eacute;sol&eacute;, votre mot de passe a d&eacute;j&agrave; &eacute;t&eacute; utilis&eacute;';
$strConfirmFailInfo     = 'D&eacute;sol&eacute;, une erreur est survenue en essayant de confirmer votre abonnement. Votre demande de confirmation n\'a pas &eacute;t&eacute; valid&eacute;e. Veuillez v&eacute;rifier que vous utilisez bien l\'adresse compl&egrave;te du lien contenu dans le courriel que vous avez re&ccedil;u. Parfois, cette adresse tient sur plusieurs lignes.';
$strPreferHTMLEmail     = 'Je pr&eacute;f&egrave;re recevoir les messages en mode HTML.';
$strPreferTextEmail     = 'Je pr&eacute;f&egrave;re recevoir les messages en mode texte';
$strPreferredFormat  = 'Format pr&eacute;f&eacute;r&eacute; pour les messages :';
$strText     = 'Texte';
$strHTML    = 'HTML';
$strPreferencesTitle    = 'Mettre &agrave; jour vos pr&eacute;f&eacute;rences';
$strPreferencesInfo     = 'V&eacute;rifiez que les informations ci-dessous sont correctes puis cliquez sur le bouton : <p></p> "mettre &agrave; jour"<br>';
$strUpdatePreferences   = 'Mettre &agrave; jour';
$strPreferencesEmailChanged = 'Votre adresse e-mail a chang&eacute;. Veuillez cliquer sur le lien dans le message que vous allez recevoir pour confimer ce changement.';
$strYouAreBlacklisted = '<br>Votre compte est dans notre "liste : envois interdits" : vous avez demand&eacute; de ne plus recevoir de messages de notre part. <br/>
Pour recevoir de nouveau nos courriels notre administrateur doit effectuer une intervention manuelle. Contactez le afin qu\'il vous retire de notre liste noire, vous pourrez alors vous inscrire de nouveau';
#
$strPreferencesNotificationSent = 'Vous allez recevoir un message avec vos modifications.';
$strPreferencesUpdated = 'Vos informations ont &eacute;t&eacute; mises &agrave; jour. Merci de votre Visite.';
$strClickHere          = 'Cliquez ici';
$strThisLink           = '<font color=red><b>ce lien</b></font>';
$strToUnsubscribe      = 'Pour vous d&eacute;sabonner de cette liste, visitez :';
$strToUpdate           = 'Pour mettre vos pr&eacute;f&eacute;rences &agrave; jour, visitez :';
$strSendHTML           = 'Envoyer le message au format HTML';
$strYes                = 'Oui';
$strNo                 = 'Non';
$strUnsubscribe        = 'Se d&eacute;sabonner';
$strAllMailinglists    = 'Toutes les Listes';
$strAttachmentIntro  = 'Ce message contient des pi&egrave;ces jointes qui peuvent &ecirc;tre ouvertes avec un navigateur :';
$strLocation    = 'Localisation';
$strFrequency    = 'Fr&eacute;quence d\'envoi de nos messages';
$strHourly    = 'Chaque heure';
$strDaily    = 'Journali&egrave;re';
$strWeekly    = 'Hebdomadaire';
$strMonthly    = 'Mensuelle';
$strChoosePassword   = 'Veuillez choisir un mot de passe';
$strConfirmPassword   = 'Confirmez votre mot de passe';
$strEnterPassword  = 'Veuillez entrer votre mot de passe';
$strForgotPassword  = 'Mot de passe oubli&eacute;';
$strPassword    = 'Mot de passe';
$strPassword2    = 'Confirmation du mot de passe';
$strPasswordsNoMatch   = 'Les mots de passe ne sont pas identiques';
$strEmailsNoMatch     = 'les Adresses Email ne correspondent pas';
$strInvalidPassword  = 'Erreur : courriel ou mot de passe invalide';
$strPasswordSent   = 'Le mot de passe vient d\'&ecirc;tre envoy&eacute; par courriel';
$strPasswordRemindSubject = 'Votre mot de passe pour nos listes';
$strPasswordRemindMessage = 'Votre mot de passe est ';
$strPasswordRemindInfo = 'Pour recevoir votre mot de passe, veuillez entrer votre adresse e-mail et cliquer sur le bouton.';
$strLogin    = 'Connexion';
$strLoginTitle     = 'Veuillez entrer votre adresse e-mail et votre mot de passe';
$strLoginInfo    = 'Cette page n&eacute;cessite un mot de passe. Veuillez entrer votre adresse e-mail et votre mot de passe';
$strPersonalLocationInfo = '<p>Cette page n&eacute;cessite une authentification personnalis&eacute;e qui peut &ecirc;tre
 trouv&eacute;e sur chaque message pr&eacute;c&eacute;demment envoy&eacute;.<br> Si vous avez cliqu&eacute; &agrave; partir d\'un lien pour
 obtenir cette page et que vous obteniez cette erreur, veuillez copier l\'adresse compl&egrave;te du lien,
 m&ecirc;me si celle-ci tient sur plusieurs lignes, et la coller ensuite dans le champ correspondant de
 votre navigateur.</p>
<p>Si vous ne connaissez pas sa localisation, vous pouvez demander un courriel qui vous la fera
 parvenir. Veuillez entrer votre adresse e-mail dans le champ et cliquez sur Continuer';
$strPersonalLocationSent = '<h1>Bravo ! vous allez recevoir un courriel avec vos indications personnalis&eacute;es</h1>';
$strUserExists   = '<br/>un destinataire avec cette adresse EMail existe d&eacute;ja dans nos bases , mais le mot de passe ne correspond pas';
$strUserExistsExplanationStart = '<br/>Afin d\'obtenir votre mot de passe cliquez ';
$strUserExistsExplanationLink = 'ici';
$strUserExistsExplanationEnd = ' pour aller &agrave; la page ou vous trouverez vos informations personelles';
$strExplainBlacklist = 'L\'adresse que vous venez d\'indiquer sera enregistr&eacute;e dans notre base afin de ne pas vous envoyer de messages.';
$strForwardTitle = 'Faire suivre un message &agrave; un tiers';
$strForwardSubtitle = 'Faire suivre le message ayant pour sujet';
$strForwardEnterEmail = 'SVP entrez une adresse EMail valide auquel on fera suivre le courier';
$strForwardInvalidEmail = '%s n\'est pas une adresse de courrier valide.';
$strForwardBlacklistedEmail = 'Le r&eacute;cipiendaire a demand&eacute; de ne pas recevoir de messages en provenance du syst&egrave;me.';
$strForwardEnterEmails = 'Veuillez saisir dans cette zone un maximum de %s adresse(s) &eacute;lectronique(s), une adresse par ligne';
$strForwardPersonalNote = 'You can enter a plain text message (of maximum %d characters) that will be prepended to the forwarded mail';
$strForwardSuccessInfo ='Le message a &eacute;t&eacute; transf&eacute;r&eacute;.';
$strForwardFailInfo = 'le Transfert du message a &eacute;chou&eacute;.';
$strForwardAlreadyDone = 'Ce message a d&eacute;j&agrave; &eacute;t&eacute; transf&eacute;r&eacute; avec succ&egrave;s vers cette adresse EMail';
$strForwardCountReached = 'Limite maximum de transferts autoris&eacute;s atteinte.';
$strForwardNoteLimitReached = 'Maximum length of personal note reached';
$strForwardFooter = 'Ce message vous a &eacute;t&eacute; transf&eacute;r&eacute; par  [FORWARDEDBY].
  Vous n\'avez pas &eacute;t&eacute; inscrit automatiquement sur cette liste de diffusion.
  pour vous y inscrire allez &agrave; :';
$strForward = 'Faire Suivre';
$strFwd = 'Tfr'; # short version of forward for email subject
?>
