<?php
# language dependent text used in the interface for users (not admin)
# translation by Gijsbert Rochat, updated by Jean-Luc Picard
$strCharSet             = 'ISO-8859-1';
$strName                = 'Nom';
$strAddress             = 'Adresse';
$strEmail               = 'Adresse email';
$strConfirmEmail  = 'Confirmez votre adresse email';
$strTown                = 'Ville';
$strPostcode            = 'Code postal';
$strSubscribeInfo       = 'S\'abonner à une ou plusieurs listes en utilisant ce formulaire';
$strRequired            = 'Champ requis';
$strSubscribeTitle      = 'S\'abonner à nos listes';
$strPleaseSelect        = 'Veuillez sélectionner les listes auxquelles vous désirez vous abonner ';
$strSubmit              = 'S\'abonner aux listes sélectionnées';
$strNotAvailable        = 'Désolé, aucune nouvelle liste n\'est disponible pour le moment';
$strEnterName           = 'Entrez votre nom ';
$strEnterEmail          = 'Entrez votre adresse email';
$strInvalidHostInEmail  = 'Désolé, nous n\'avons pu confirmer l\'existence de votre adresse email. Veuillez vérifier l\'adresse saisie';
$strEnterList           = 'Veuillez sélectionner une liste pour vous abonner';
$strPleaseEnter         = 'Veuillez entrer votre';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Merci de vous être abonné(e) à nos listes.';
# the EmailConfirmation message can contain placeholders
$strEmailConfirmation   = 'Votre adresse [email] est enregistrée. Vous allez recevoir un message pour confirmer votre abonnement. Veuillez finaliser votre inscription en cliquant sur le lien contenu dans ce message.';
$strEmailFailed    = 'Désolé, l\'envoi du message de confirmation a échoué. Veuillez actualiser la page pour réessayer.';
$strUnsubscribeTitle    = 'Se désabonner de nos listes';
$strUnsubscribeDone     = 'Vous avez été désabonné(e) des listes choisies. Vous recevrez un message de confirmation.';
$strBack                = 'Retour';
$strUnsubscribeInfo     = 'Se désabonner d\'une ou de plusieurs de nos listes';
$strContinue            = 'Continuer';
$strUnsubscribeSelect   = 'Sélectionnez les listes auxquelles vous désirez vous désabonner';
$strAllLists            = 'Toutes les listes';
$strNoLists             = 'Aucune liste';
$strUnsubscribeRequestForReason = 'nous sommes désolé de constater que vous ne souhaitez plus recevoir nos lettres. Afin de nous aider a améliorer nos services, pouvez vous nous en préciser les raisons:';
$strUnsubscribeFinalInfo = '<br/><b>Note</b>: Cette page est une page de désinscription <b>définitive</b> de nos listes. Si vous désirez changer votre adresse email ou modifier les listes auquels vous souscrivez, S.V.P. utilisez le lien <a href="[PREFERENCESURL]">Mise à jour</a>';
$strNoListsFound        = 'Désolé, votre adresse email n\'est pas inscrite sur nos listes.';
$strResubmit            = 'Ré-envoyer le message';
$strUnsubscribeSubmit   = 'Se désabonner des listes sélectionnées';
$strValuesMissing       = 'Les champs ci-dessous sont obligatoires';
$strConfirmInfo         = 'Merci de vous être abonné(e) à nos listes. Les listes auxquelles vous vous êtes abonné(e) sont listées ci-dessous';
$strConfirmTitle        = 'Page de confirmation pour les membres de PHPlist';
$strUserNotFound        = 'Utilisateur introuvable';
$strUserAlreadyInitialised = 'Désolé, cette adresse est déjà inscrite par ailleurs';
$strConfirmFailInfo     = 'Désolé, une erreur est survenue en essayant de confirmer votre abonnement. Votre demande de confirmation n\'a pas été validée. Veuillez vérifier que vous utilisez bien l\'adresse complète du lien contenu dans le message que vous avez reçu. Parfois, cette adresse tient sur plusieurs lignes.';
$strPreferHTMLEmail     = 'Je préfère recevoir les messages en mode HTML ';
$strPreferTextEmail     = 'Je préfère recevoir les messages en mode texte brut';
$strPreferredFormat  = 'Format préféré pour les messages :';
$strText     = 'Texte brut';
$strHTML    = 'HTML';
$strPreferencesTitle    = 'Mettre à jour vos préférences';
$strUpdatePreferences   = 'Mettre à jour';
$strPreferencesInfo     = 'Vérifiez si les informations ci-dessous sont correctes<br />et cliquez sur le bouton "'.$strUpdatePreferences.'"<br />';
$strPreferencesEmailChanged = 'Votre adresse email a changé. Veuillez cliquer sur le lien dans le message que vous allez recevoir pour confimer ce changement d\'adresse';
$strYouAreBlacklisted = '<br>Votre compte est dans notre "Black List", vous avez demandé à ne plus recevoir d\'information de notre part. <br/>
Pour recevoir de nouveau nos messages notre administrateur doit éffectuer une intervention manuelle. Contacter le afin qu\'il vous retire de notre "Black List", vous pourrez alors vous abonner de nouveau';
$strPreferencesNotificationSent = 'Vous allez recevoir un message avec vos modifications.';
$strPreferencesUpdated = 'Vos informations ont été mises à jour. Merci de votre visite.';
$strClickHere          = 'Cliquez ici';
$strThisLink           = 'ce lien';
$strToUnsubscribe      = 'Pour vous désabonner à cette liste, cliquez';
$strToUpdate           = 'Pour mettre vos préférences à jour, cliquez';
$strSendHTML           = 'Envoyer un message au format HTML';
$strYes                = 'Oui';
$strNo                 = 'Non';
$strUnsubscribe        = 'Se désabonner';
$strAllMailinglists    = 'Toutes les Listes';
$strAttachmentIntro  = 'Ce message contient des pièces jointes qui peuvent être ouvertes avec un navigateur :';
$strLocation    = 'Localisation';
$strFrequency    = 'Fréquence d\'envoi de nos messages';
$strHourly    = 'Chaque heure';
$strDaily    = 'Journalière';
$strWeekly    = 'Hebdomadaire';
$strMonthly    = 'Mensuelle';
$strChoosePassword   = 'Veuillez choisir un mot de passe';
$strConfirmPassword   = 'Confirmez votre mot de passe';
$strEnterPassword  = 'Veuillez entrer votre mot de passe';
$strForgotPassword  = 'Mot de passe oublié';
$strPassword    = 'Mot de passe';
$strPassword2    = 'Confirmation du mot de passe';
$strPasswordsNoMatch   = 'Les mots de passe ne sont pas identiques';
$strEmailsNoMatch     = 'les 2 adresses email ne sont pas identiques';
$strInvalidPassword  = 'Erreur : adresse email ou mot de passe invalide';
$strPasswordSent   = 'Le mot de passe vient d\'être envoyé par email';
$strPasswordRemindSubject = 'Votre mot de passe pour nos listes';
$strPasswordRemindMessage = 'Votre mot de passe est ';
$strPasswordRemindInfo = 'Pour recevoir votre mot de passe par email, veuillez entrer votre adresse email et cliquer sur le bouton "'.$strForgotPassword.'".';
$strLogin    = 'Connexion';
$strLoginTitle     = 'Veuillez entrer votre adresse email et votre mot de passe';
$strLoginInfo    = 'Cette page nécessite un mot de passe. Veuillez entrer votre adresse email et votre mot de passe';
$strPersonalLocationInfo = '<p>Cette page nécessite une authentification personnalisée qui peut être
 trouvée sur chaque message précédemment envoyé.<br> Si vous avez cliqué à partir d\'un lien pour
 obtenir cette page et que vous obtenez cette erreur, veuillez copier l\'adresse complète du lien,
 même si celle-ci tient sur plusieurs lignes, et la coller ensuite dans le champ correspondant de
 votre navigateur.</p>
<p>Si vous ne connaissez pas sa localisation, vous pouvez demander un message qui vous la fera
 parvenir. Veuillez entrer votre adresse email dans le champ et cliquer sur "Continuer"';
$strPersonalLocationSent = '<h1>Bravo ! vous allez recevoir un message avec vos indications personnalisées</h1>';

$strUserExists   = '<br/>un utilisateur avec cette adresse email existe déja dans notre base de données, mais le mot de passe ne correspond pas';
$strUserExistsExplanationStart = '<br/>Afin d\'obtenir votre mot de passe cliquez ';
$strUserExistsExplanationLink = 'ici';
$strUserExistsExplanationEnd = ' pour aller à la page ou vous trouverez vos informations personelles';
$strForwardTitle = 'Faire suivre un message a quelqu\'un';
$strForwardSubtitle = 'Faire suivre le message ayant pour sujet';
$strForwardEnterEmail = 'SVP entrez une adresse email valide auquel on fera suivre le message';
$strForwardSuccessInfo ='Le message a été transféré';
$strForwardFailInfo = 'le transfert du message a échoué';
$strForwardAlreadyDone = 'Ce message a déja été transféré avec succès à cette adresse email';
$strForwardFooter = 'Ce message vous a été transféré par [FORWARDEDBY].
  Vous n\'avez pas été inscrit automatiquement sur cette liste de diffusion.
  Pour vous y inscrire allez à ';
$strForward = 'Faire Suivre';
$strFwd = 'Tfr'; # short version of forward for email subject

$strExplainBlacklist = 'L\'adresse email que vous entrez ici sera enregistrée dans notre base de données dans le seul but de bloquer tout message envoyé par ce système.';
$strForwardInvalidEmail = '%s n\'est pas une adresse email valide';
$strForwardBlacklistedEmail = 'Le propriétaire de cette adresse email a demandé de ne plus recevoir de courriels de ce système.';
$strForwardEnterEmails = 'SVP entrez un maximum de %s adresses email valides à faire suivre, une par ligne';
$strForwardPersonalNote = 'Vous pouvez entrer une note personnelle en texte brut (avec un maximum de %d caractères) qui sera ajouté à l\'email transferé';
$strForwardCountReached = 'Le nombre maximum des messages à fair suivre a été atteint';
$strForwardNoteLimitReached = 'La longueur maximale de la note personnelle a été atteint';

?>

