<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strName                = 'Name';
$strAddress             = 'Adresse';
$strEmail               = 'E-Mail';
$strTown                = 'Wohnort';
$strPostcode            = 'Postfach';
$strSubscribeInfo       = 'Zum Anmelden bei einer oder mehreren unserer Mailinglisten benutzen Sie das nachfolgende Formular!';
$strRequired            = 'Benötigte Felder in rot';
$strSubscribeTitle      = 'Anmelden bei der Mailingliste';
$strPleaseSelect        = 'Bitte wählen Sie eine oder mehrere Listen, bei denen Sie sich anmelden wollen';
$strSubmit              = 'Anmelden bei den ausgewählten Mailinglisten';
$strNotAvailable        = 'Derzeit sind keine Listen verfügbar';
$strEnterName           = 'Bitte geben Sie ihren Namen ein';
$strEnterEmail          = 'Bitte geben Sie ihre E-Mail Adresse ein';
$strConfirmEmail        = 'E-Mail bestätigen';
$strInvalidHostInEmail  = 'Entschuldigung, aber E-Mail an diese Adresse ist unzustellbar. Bitte prüfen Sie Ihre Adresse erneut.';
$strEnterList           = 'Bitte wählen Sie ein Liste aus, bei der Sie sich anmelden wollen';
$strPleaseEnter         = 'Bitte geben Sie ein';
# the thanks message can contain placeholders
#$strThanks              = 'Liebe/lieber [FIRST NAME], <br/>Danke, dass sie sich für unsere Listen angemeldet haben.';
$strThanks              = 'Danke für die Anmeldung bei unseren Listen.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Ihre E-mail [email] ist zu unserem System hinzugefügt worden. Sie bekommen in Kürze eine E-Mail mit der Bestätigung der Listen, für welche sie sich angemeldet haben.';
$strEmailConfirmation   = 'Sie erhalten in Kürze eine E-Mail mit der Bestätigung der Listen bei denen Sie sich angemeldet haben.';
$strEmailFailed         = 'Entschuldigung, aber die E-Mail mit der Bestätigungsanfrage wurde nicht versandt, bitte drücken Sie „Aktualisieren“ und versuchen Sie es nochmals.';
$strUnsubscribeTitle    = 'Abmelden von unseren Mailinglisten';
$strUnsubscribeDone     = 'Sie wurden von den Mailinglisten, die Sie ausgewählt haben, abgemeldet - eine Bestätigung erhalten Sie in Kürze per E-Mail.';
$strBack                = 'Zurück';
$strUnsubscribeInfo     = 'Abmelden von einer oder mehreren unserer Mailinglisten';
$strContinü            = 'Weiter';
$strUnsubscribeSelect   = 'Bitte wählen Sie die Listen von denen Sie sich abmelden wollen';
$strAllLists            = 'Alle Listen';
$strNoLists             = 'Keine von diesen';
$strUnsubscribeRequestForReason = 'Wir bedauern die Abmeldung unseres Newsletters. Es würde uns helfen, wenn Sie den Grund angeben könnten:';
$strUnsubscribeFinalInfo = '<br/><b>Bitte beachten</b>: diese Seite dient dazu, unseren Newsletter <b>endgültig</b> abzumelden. Falls Sie Ihre E-Mail Adresse oder die Auswahl des Newsletters ändern möchten, ändern Sie bitte Ihre <a href="[PREFERENCESURL]">Voreinstellungen</a>';
$strNoListsFound        = 'Sie wurden mit dieser E-Mail bei keiner unserer Mailinglisten angemeldet';
$strResubmit            = 'Erneut versuchen';
$strUnsubscribeSubmit   = 'Abmelden von den gewählten Mailinglisten';
$strValuesMissing       = 'Die folgenden benötigten Felder fehlen';
$strConfirmInfo         = 'Danke für die Bestätigung. Sie wurden auf folgenden Listen eingeschrieben:';
$strConfirmTitle        = 'Bestätigungsseite';
$strUserNotFound        = 'User nicht gefunden';
$strUserAlreadyInitialised = 'Ihre Passwort wurde bereits verschickt';
$strConfirmFailInfo     = 'Es trat ein Fehler auf. Details:';
$strPreferHTMLEmail     = 'Ich bevorzuge E-Mails im HTML-Format';
$strPreferTextEmail     = 'Ich bevorzuge E-Mails im Text-Format';
$strPreferredFormat     = 'Bevorzugtes Format für E-Mails:';
$strText                = 'Text';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Einstellungen ändern';
$strPreferencesInfo     = 'Bitte bestätigen Sie, dass die folgenden Informationen korrekt sind und drücken Sie den Update-Button';
$strUpdatePreferences   = 'Update';
$strPreferencesEmailChanged = 'Ihre E-Mail wurde geändert. Bitte besuchen Sie den Link, welcher in der E-Mail genannt wird, die Sie an Ihre neue Adresse erhalten.';
$strYouAreBlacklisted  = 'Ihre E-Mail Adresse ist in unserer "Black List" - das heisst, Sie möchten keine Newsletter mehr. <br/>
Um wieder Newsletter E-Mails zu empfangen, müsste der Administrator manuell eingreifen. Bitte kontaktieren Sie den Webmaster explizit mit der Anfrage, den Newsletter wieder zu empfangen, und Sie werden von der "Black List" entfernt.';
$strPreferencesNotificationSent = 'Sie werden eine E-Mail mit den Änderungen erhalten';
$strPreferencesUpdated = 'Danke für Ihre Änderungen. Wir haben Ihre Informationen aktualisiert.';
$strClickHere          = 'Drücken Sie hier';
$strThisLink           = 'dieser Link';
$strToUnsubscribe      = 'Um sich aus der Liste auszutragen besuchen Sie';
$strToUpdate           = 'Um Ihre Einstellungen zu ändern besuchen Sie';
$strSendHTML           = 'Sende HTML E-Mail';
$strYes                = 'Ja';
$strNo                 = 'Nein';
$strUnsubscribe        = 'Abmelden';
$strAllMailinglists    = 'Alle Mailinglisten';
$strAttachmentIntro    = 'Diese Nachricht beinhaltet Anhänge, die mit einem Webbrowser betrachtet werden können:';
$strLocation           = 'Ort';
$strFrequency          = 'Wie oft dürfen wir Ihnen Nachrichten senden';
$strHourly             = 'Stündlich';
$strDaily              = 'Täglich';
$strWeekly             = 'Wöchentlich';
$strMonthly            = 'Monatlich';
$strChoosePassword     = 'Bitte wählen Sie ein Passwort';
$strConfirmPassword    = 'Bitte bestätigen Sie Ihr Passwort';
$strEnterPassword      = 'Bitte geben Sie Ihr Passwort ein';
$strForgotPassword     = 'Passwort vergessen';
$strPassword           = 'Passwort';
$strPassword2          = 'Passwort bestätigen';
$strPasswordsNoMatch   = 'Die Passwörter stimmen nicht überein';
$strEmailsNoMatch      = 'Die E-Mail Adressen stimmen nicht überein';
$strInvalidPassword    = 'Fehler: ungültige E-Mail oder Passwort';
$strPasswordSent       = 'Ihre Passwort wurde Ihnen per E-Mail zugesendet. Sie sollten es innerhalb der nächsten Minuten erhalten.';
$strPasswordRemindSubject = 'Ihr Passwort für unsere Listen';
$strPasswordRemindMessage = 'Ihr Passwort lautet ';
$strPasswordRemindInfo = 'Um Ihr Passwort per E-Mail zu erhalten, geben Sie bitte Ihre E-Mail-Adresse ein und drücken den "'.$strForgotPassword.'" Knopf.';
$strLogin              = 'Login';
$strLoginTitle         = 'Bitte geben Sie Ihre E-Mail-Adresse und Ihr Passwort ein';
$strLoginInfo          = 'Diese Seite benötigt ein Passwort. Bitte geben Sie Ihre E-Mail-Adresse und Ihr Passwort ein';
$strPersonalLocationInfo = '
  <p>Diese Seite benötigt eine persönliche Identifikation, welche auf jeder von uns an Sie gesendeten E-Mail angegeben ist.<br/>
  Wenn Sie diesen Bereich angeklickt haben und diesen Fehler erhalten, vergewissern Sie sich, dass Sie die vollständigen Zeilen in die 
  Adresszeile Ihres Browsers eingetragen haben. Manchmal ist die Adresse über mehrere Zeilen umgebrochen.</p>
  <p>Wenn Sie den Bereich nicht kennen, können Sie Ihn per E-Mail erfragen.
  Bitte geben Sie dazu Ihre E-Mail-Adresse ein und klicken Sie auf Weiter
';
$strPersonalLocationSent       = '<h1>Erfolg! Sie sollten eine Nachricht mit Ihrem persönlichen Bereich in Kürze erhalten</h1>';
$strUserExists                 = '<br/>Ein Benutzer mit dieser E-Mail-Adresse existiert bereits und hat ein anderes Passwort';
$strUserExistsExplanationStart = '<br/>Um Ihr Passwort zu erhalten, klicken Sie';
$strUserExistsExplanationLink  = 'hier';
$strUserExistsExplanationEnd   = ' um zu der Seite zu gelangen, wo Sie Ihren persönlichen Bereich anfordern können';

$strExplainBlacklist        = 'Die E-Mail Adresse wird ausschliesslich zum Blockieren auf diesem System verwendet.';
$strForwardTitle            = 'Nachricht weiterleiten';
$strForwardSubtitle         = 'Weiterleiten mit Betreff ';
$strForwardEnterEmail       = 'Bitte eine gültige E-Mail für die Weiterleitung angeben';
$strForwardInvalidEmail     = '%s ist keine gültige E-Mail Adresse';
$strForwardBlacklistedEmail = 'Empfänger lehnt E-Mails von diesem System ab.';
$strForwardEnterEmails      = 'Bitte tragen Sie eine maximale Anzahl von %s gültigen E-Mail Adressen zur Weiterleitung in diese Feld ein (eine pro Zeile)';
$strForwardPersonalNote     = 'Sie können eine Textnachricht (maximal %d Zeichen) eingeben, die der weitergeleiteten E-Mail vorangestellt werden';
$strForwardSuccessInfo      = 'Diese Nachricht wurde weitergeleitet';
$strForwardFailInfo         = 'Diese Nachricht konnte nicht weitergeleitet werden';
$strForwardAlreadyDone      = 'Diese Nachricht wurde schon erfolgreich an diese E-Mail Adresse weitergeleitet';
$strForwardCountReached     = 'Maximale Anzahl von Weiterleitungen erreicht';
$strForwardNoteLimitReached = 'Maximale Länge der personalisierten Nachricht erreicht';
$strForwardFooter           = 'Diese Nachricht wurde an Sie weitergeleitet durch [FORWARDEDBY].
  Sie sind nicht automatisch bei diesem Newsletter angemeldet.
  Zum Abonnieren dieses Newsletters gehen Sie bitte hierhin';
$strForward = 'Weiterleiten';
$strFwd = 'Fwd';
$strUserExistsResubscribe = 'Diese E-Mail ist bereits registriert.';
$strUserExistsResubscribeExplanation = 'Besuchen Sie die <a href="%s"> Voreinstellungsseite </a>, um Ihre persönlichen Angaben zu überprüfen.';
$strContinue            = 'Weiter'; 
