<?php

# language dependent text used in the interface for users (not admin)

$strCharSet               = 'UTF-8';
$strLancode               = 'he';
$strLandir                = 'rtl'; ## language direction (ltr or rtl)
$strName                  = 'שם';
$strAddress               = 'כתובת';
$strEmail                 = 'אימייל';
$strTown                  = 'עיר';
$strPostcode              = 'מיקוד';
$strSubscribeInfo       = 'להצטרפות לרשימת תפוצה אחת או יותר יש להשתמש בטופס שלהלן';
$strRequired                = 'שדה נדרש';
$strSubscribeTitle      = 'להצטרפות לרשימת התפוצה שלנו';
$strPleaseSelect          = 'אנא בחר/י את רשימות התפוצה אליהן ברצונך להצטרף';
$strSubmit                  = 'צרפוני  לרשימה שסומנה';
$strNotAvailable        = 'צר לנו, אך אין כרגע רשימות תפוצה זמינות';
$strEnterName           = 'אנא הזן/הזיני את שמך';
$strEnterEmail          = 'אנא ציין/צייני את כתובת האימייל שלך';
$strInvalidHostInEmail  = 'צר לנו, אך דואר אלקטרוני זה אינו קיים. אנא בדוק/בדקי אם לא נפלה טעות בהקלדה';
$strEnterList           = 'אנא בחר/י רשימת תפוצה אליה ברצונך להצטרף';
$strPleaseEnter         = 'אנא הזן/הזיני';
# the thanks message can contain placeholders
#$strThanks              = 'שלום [FIRST NAME], <br/>תודה שהצטרפת לרשימת התפוצה שלנו.';
$strThanks              = 'תודה שהצטרפת לרשימת התפוצה שלנו.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'כתובת האימייל [email] נרשמה במערכת. בקרוב תקבל/י אימייל ובו תתבקש/תתבקשי לאשר הצטרפות לרשימת.';
$strEmailConfirmation   = 'כתובת האימייל שלך נרשמה במערכת. בקרוב תקבל/י אימייל ובו תתבקש/תתבקשי לאשר הצטרפות לרשימת. אנא לחצ/י על הקישור על מנת לוודא את הרשמתך.';
$strEmailFailed          = 'צר לנו, אך לא הצלחנו לשלוח אליך אימייל לאישור ההצטרפת, אנא רענן/רענני את הדף ונסי שנית.';
$strUnsubscribeTitle    = 'הסרה מרשימת התפוצה';
$strUnsubscribeDone     = 'הוסרת מרשימת התפוצה ובקרוב תקבל/י אימייל לאישור.';
$strBack                = 'חזרה';
$strUnsubscribeInfo     = 'הסרה מרשימת תפוצה אחת או יתר';
$strContinue                = 'המשך';
$strUnsubscribeSelect   = 'אנא בחר/י את רשימת התפוצה שברצונך לבטל ההרשמה אליה';
$strAllLists            = 'כל הרשימות';
$strNoLists             = 'אף רשימה';
$strNoListsFound        = 'צר לנו, אך אינך רשום לאף רשימה עם כתובת האימייל הזו.';
$strResubmit            = 'שלח/י בשנית את האימייל';
$strUnsubscribeSubmit   = 'הסרה מרשימות התפוצה שסומנו';
$strValuesMissing       = 'השדות שלהלן לא מולאו';
$strConfirmInfo         = 'תודה שאישרת את ההצטרפות לרשימת התפוצה שלנו. להלן הרשימות אליהן את/ה רשומ/ה.';
$strConfirmTitle        = 'דף אישור הרשמה ל-PHPlist';
$strUserNotFound        = 'המשתמש/ת לא נמצא/ה';
$strUserAlreadyInitialised = 'צר לנו, אך בחרת כבר סיסמה';
$strConfirmFailInfo     = 'צר לנו, אך נפלה שגיאה באישור ההרשמה. אנא וודא/י כי הקלדת את כל הקישור שהופיע באימייל שנשלח אליך. קישור זה לעתים גולש למספר שורות.';
$strPreferHTMLEmail     = 'אנא שלחו לי אימיילים בפורמט HTML';
$strPreferTextEmail     = 'אנא שלחו לי אימייל בפורמט טקסט בלבד';
$strPreferredFormat      = 'פורמט מועדף לקבלת אימיילים:';
$strText                 = 'טקסט';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'עידכון ההעדפות שלך';
$strPreferencesInfo     = 'אנא ודא/י כי האינפורמציה שלהלן נכונה ולחצ/י על "עדכון".';
$strUpdatePreferences   = 'עדכון';
$strPreferencesEmailChanged = 'כתובת האימייל שלך שונתה. אנא לחצ/י על הקישור המופיע באימייל שזה עתה נשלח לכתובת זו על מנת לאשרה.';
$strPreferencesNotificationSent = 'את/ה תקבלי אימייל לאישור השינויים';
$strPreferencesUpdated = 'תודה על האישור. עדכנו את הנתונים החדשים.';
$strClickHere          = 'לחצ/י כאן';
$strThisLink           = 'קישור זה';
$strToUnsubscribe      = 'להסרה מרשימת התפוצה';
$strToUpdate           = 'לעדכון ההעדפות האישיות לחצ/י על הקישור';
$strSendHTML           = 'שלח אימייל בפורמט HTML';
$strYes                = 'כן';
$strNo                 = 'לא';
$strUnsubscribe        = 'הסרה מהרשימה';
$strAllMailinglists    = 'כל הרשימות';
$strAttachmentIntro     = 'הודעה זו כוללת קבצים בהם ניתן לצפות בדפדפן:';
$strLocation           = 'מיקום';
$strFrequency           = 'באיזו תכיפות את/ה רוצה שנשלח אליך הודעות';
$strHourly             = 'מדי שעה';
$strDaily               = 'מדי יום';
$strWeekly             = 'מדי שבוע';
$strMonthly             = 'מדי חודש';
$strChoosePassword      = 'אנא בחר/י סיסמה';
$strConfirmPassword    = 'אנא הקלד/הקלידי שנית את הסיסמה לאישור';
$strEnterPassword       = 'אנא הזן/הזיני את הסיסמה';
$strForgotPassword     = 'שכחתי את הסיסמה שלי';
$strPassword           = 'סיסמה';
$strPassword2           = 'אישור סיסמה';
$strPasswordsNoMatch    = 'הסיסמאות שהזנת אינן זהות';
$strInvalidPassword     = 'שגיאה: כתובת אימייל או סיסמה שגויה';
$strPasswordSent        = 'הסיסמה נשלחה אליך באימייל. תקבל/י אותה בעוד מספר דקות.';
$strPasswordRemindSubject = 'הסיסמה שלך לרשימות התפוצה שלנו';
$strPasswordRemindMessage = 'הסיסמה שלך היא ';
$strPasswordRemindInfo = 'לקבלת הסיסמה באימייל אנא הזן/הזיני את כתובתך ולחצי על  "'.$strForgotPassword.'".';
$strLogin               = 'כניסה למערכת';
$strLoginTitle          = 'אנא הזן/הזיני כתובת אימייל וסיסמה';
$strLoginInfo           = 'לצפייה בדף זה יש צורך להיכנס למערכת. אנא הזן/הזיני שם וסיסמה';
$strPersonalLocationInfo = '
  <p> הצפיה בדף זה מתאפשרת באמצעות סימן זיהוי שמצא באימייל ששלחנו אליך.<BR>
  אם לחצת על הקישור באימייל שנשלח אליך, וקיבלת הודעת שגיאה זות אנא וודא/י כי הקלדת את הדבקת את כל הכתובת לדפדפן. לעתים הכתובת גולשת על מספר שורות.</P>
  <p>אם אינך יודע/ת את המיקום, את/ה יכול/ה לבקש כי יישלח אליך אימייל ובו הכתובת. אנא הזן/הזיני את כתובת האימייל שלך ולחצי על "המשך"';
$strPersonalLocationSent = '<h1>פעולה בוצעה בהצלחה! בקרוב תקבלי אימייל ובו הפרטים שמילאת</h1>';
