<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'utf-8';
$strName                = 'Név';
$strAddress             = 'Cím';
$strEmail               = 'E-mail cím';
$strTown                = 'Lakóhely';
$strPostcode            = 'Irányítószám';
$strSubscribeInfo       = 'Hírlevelünk megrendeléséhez töltse ki az alábbi űrlapot';
$strRequired            = 'a mező kitöltése kötelező';
$strSubscribeTitle      = 'Hírlevelünk megrendelése';
$strPleaseSelect        = 'Kérjük, válassza ki azokat a hírleveleket, melyeket meg akar rendelni';
$strSubmit              = 'Megrendelem a kiválasztott hírleveleket';
$strNotAvailable        = 'Sajnos jelenleg nincs hírlevelünk';
$strEnterName           = 'Kérjük, írja be a nevét';
$strEnterEmail          = 'Kérjük, adjon meg egy működő e-mail címet';
$strConfirmEmail        = 'Az e-mail cím megerősítése';
$strInvalidHostInEmail  = 'Sajnos abba a tartományba nem kézbesíthető e-mail. Kérjük, ellenőrizze, hogy pontosan írta-e be az e-mail címet.';
$strEnterList           = 'Kérjük, válassza ki a megrendelni kívánt hírlevelet';
$strPleaseEnter         = 'Kérjük, töltse ki a következő mezőt:';
# the thanks message can contain placeholders
#$strThanks              = 'Kedves [FIRST NAME]!<br/>Köszönjük, hogy feliratkozott a listáinkra.';
$strThanks              = 'Köszönjük, hogy megrendelte a hírleveleinket.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'A(z) [email] e-mail címet nyilvántartásba vettük. Hamarosan visszaigazoljuk e-mailben az Ön által megrendelt listákat.';
$strEmailConfirmation   = 'E-mail címét nyilvántartásba vettük. Hamarosan fog kapni egy e-mailt a megrendelés jóváhagyásához. Kérjük, kattintson az üzenetben lévő hivatkozásra.';
$strEmailFailed          = 'Sajnos nem tudtuk elküldeni a visszaigazoló e-mailt. Kérjük, kattintson a "Frissítés" gombra, és próbálkozzon újra. Ha még mindig nem sikerül, az azért lehet, mert Ön szerepel a "feketelistánkon", ami azt jelenti, hogy Ön nem kaphatja meg a hírlevélrendszerünk által küldött e-maileket. Kérjük, hogy ebben az esetben vegye fel a kapcsolatot az adminisztrátorral.';
$strUnsubscribeTitle    = 'Hírlevelünk lemondása';
$strUnsubscribeDone     = 'A hírlevél lemondása megtörtént, melyet hamarosan vissza fogunk igazolni e-mailben.';
$strBack                = 'Vissza';
$strUnsubscribeInfo     = 'Hírleveleink lemondása';
$strContinue            = 'Folytatás';
$strUnsubscribeSelect   = 'Kérjük, válassza ki azokat a hírleveleket, melyeket le kíván mondani';
$strAllLists            = 'Az összes hírlevelet';
$strNoLists             = 'Egyiket sem';
$strUnsubscribeRequestForReason = 'Sajnálatos módon tapasztaljuk, hogy már nem tart igényt a hírlevelünkre. Segítene a szolgáltatásunk javításában, ha elmondaná nekünk, hogy miért döntött így:';
$strUnsubscribeFinalInfo = '<br/><b>Kérjük, ne feledje</b>: ezen az oldalon <b>végleg</b> leállíthatja az e-mailjeink fogadását. Ha módosítani kívánja e-mail címét, vagy változtatni óhajt a hírlevelek megrendelésén, kérjük, <a href="[PREFERENCESURL]">módosítsa</a> inkább a beállításait';
$strNoListsFound        = 'Sajnos Ön egyik hírlevelünket sem rendelte meg ezzel az e-mail címmel';
$strResubmit            = 'E-mail újraküldése';
$strUnsubscribeSubmit   = 'A kiválasztott hírlevelek lemondása';
$strValuesMissing       = 'A következő kötelező adatok hiányoznak';
$strConfirmInfo         = 'Köszönjük, hogy visszaigazolta hírleveleink megrendelését. Az Ön által megrendelt hírlevelek listáját alább találja';
$strConfirmTitle        = 'SOFT-TRANS Shareware Bolt hírlevél-megrendelés visszaigazoló oldal';
$strUserNotFound        = 'A felhasználó nem található';
$strUserAlreadyInitialised = 'Sajnos megadták már a jelszót';
$strConfirmFailInfo     = 'Sajnos nem lett felismerve az Ön visszaigazolási kérése. Kérjük, ellenőrizze, hogy a teljes webcímet használta-e, ahogy említettük az e-mailben, amit megkapott. Ez a webcím olykor több sorba tördelve jelenik meg.';
$strPreferHTMLEmail     = 'A HTML formátumú e-mailt szeretem jobban';
$strPreferTextEmail     = 'Az egyszerű szöveg formátumú e-mailt szeretem jobban';
$strPreferredFormat      = 'Az e-mailek kért formátuma:';
$strText                 = 'Szöveg';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Beállítások módosítása';
$strPreferencesInfo     = 'Kérjük, erősítse meg, hogy az alábbi adatok pontosak, s kattintson a "Módosítás" gombra';
$strUpdatePreferences   = 'Módosítás';
$strPreferencesEmailChanged = 'Az e-mail címét módosítottuk. Kérjük, hogy az új e-mail cím jóváhagyásához keresse fel az e-mailben megküldött hivatkozást.';
$strYouAreBlacklisted = 'Az e-mail cím felkerült a "feketelistánkra", ami azt jelenti, Ön azt kérte, hogy soha ne küldjünk Önnek hírlevelet. <br/>
Ha ismét meg szeretné kapni az e-mailjeinket, adminisztrátorunk kézi beavatkozására van szükség. Kérjük, vegye fel velünk a kapcsolatot, világosan jelentse ki, hogy ismét szeretné kapni a hírleveleinket, 
s mi levesszük Önt a feketelistánkról. ';
$strPreferencesNotificationSent = 'Meg fogja kapni a módosításokat tartalmazó e-mailt';
$strPreferencesUpdated = 'Köszönjük, a beküldött adatokat frissítettük.';
$strClickHere          = 'Kattintson ide';
$strThisLink           = 'erre a hivatkozásra';
$strToUnsubscribe      = 'Ha már nem akarja megkapni a hírlevelünket, ';
$strToUpdate           = 'Beállításai módosításához és a lemondáshoz keresse fel';
$strSendHTML           = 'HTML e-mail küldése';
$strYes                = 'Igen';
$strNo                 = 'Nem';
$strUnsubscribe        = 'Lemondás';
$strAllMailinglists    = 'Az összes hírlevél';
$strAttachmentIntro     = 'Ez az üzenet mellékleteket tartalmaz, melyeket webböngészőben tekinthet meg:';
$strLocation           = 'Hely';
$strFrequency           = 'Milyen gyakorisággal küldjük Önnek az üzeneteket';
$strHourly             = 'Óránként';
$strDaily               = 'Naponta';
$strWeekly             = 'Hetente';
$strMonthly             = 'Havonta';
$strChoosePassword      = 'Kérjük, válasszon jelszót';
$strConfirmPassword    = 'A jelszó megerősítése';
$strEnterPassword       = 'Kérjük, írja be jelszavát';
$strForgotPassword     = 'Elfelejtett jelszó';
$strPassword           = 'Jelszó';
$strPassword2           = 'Jelszó megerősítése';
$strPasswordsNoMatch    = 'Nem egyeznek a jelszavak';
$strEmailsNoMatch     = 'Nem egyeznek az Ön által beírt e-mail címek';
$strInvalidPassword     = 'Hiba: az e-mail cím vagy a jelszó érvénytelen';
$strPasswordSent        = 'Jelszavát megküldtük az e-mail címére, melyet perceken belül meg kell kapnia';
$strPasswordRemindSubject = 'Az Ön jelszava a hírleveleinkhez';
$strPasswordRemindMessage = 'Az Ön jelszava: ';
$strPasswordRemindInfo = 'Kérjük, hogy a jelszó e-mailben történő megküldéséhez írja be az e-mail címét, majd kattintson az "'.$strForgotPassword.'" gombra.';
$strLogin               = 'Bejelentkezés';
$strLoginTitle          = 'Kérjük, írja be e-mail címét és jelszavát';
$strLoginInfo           = 'Ezen oldalhoz történő hozzáféréshez jelszóra van szükség. Kérjük, írja be e-mail címét és jelszavát';
$strPersonalLocationInfo = '
  <p>Ehhez az oldalhoz személyes azonosításra van szükség, melyet megtalál minden általunk küldött e-mailben.<br/>
  Ha rákattintott erre a helyre, és ez a hiba jelentkezik, kérjük, bizonyosodjon meg róla, hogy a teljes sort illesztette-e be 
  a böngészője Hely mezőjébe. A helyet olykor több sorba tördelik a levelezőprogramok.</p>
  <p>Ha nem ismeri a helyet, kérhet egy olyan e-mailt, melyből megtudhatja a címet.
  Kérjük, írja be e-mail címét a mezőbe, aztán kattintson a "Folytatás" gombra.
';
$strPersonalLocationSent = '<h1>Sikerült! Hamarosan meg kell kapnia az Ön személyes helyét tartalmazó e-mailt</h1>';
$strUserExists   = '<br/>Már van ilyen e-mail címmel rendelkező felhasználó, nyilvántartásaink szerint azonban eltérő a jelszava.';
$strUserExistsExplanationStart = '<br/>A jelszó beszerzéséhez kattintson ';
$strUserExistsExplanationLink = 'ide';
$strUserExistsExplanationEnd = ' annak az oldalnak a felkereséséhez, ahol meg tudja kérni az Ön személyes helyét';
$strExplainBlacklist = 'Az Ön által ide beírt e-mail címet kizárólag abból a célból rögzítjük az adatbázisban, hogy blokkoljunk az ebből a rendszerből küldött bármilyen e-mailt.';
$strForwardTitle = 'Az üzenet továbbítása valakinek';
$strForwardSubtitle = 'Üzenet továbbítása, melynek tárgya ';
$strForwardEnterEmail = 'Kérjük, írja be a továbbítás e-mail címét';
$strForwardInvalidEmail = '%s nem érvényes e-mail cím';
$strForwardBlacklistedEmail = 'A címzett kérte, hogy nem akar e-maileket kapni ettől a rendszertől.';
$strForwardEnterEmails = 'Kérjük, írjon be legfeljebb %s működő e-mail címet ebbe a mezőbe a továbbításhoz, soronként egyet';
$strForwardPersonalNote = 'Beírhat egy egyszerű szöveg formátumú (legfeljebb %d karakterből álló) üzenetet, mely hozzáfűzésre kerül a továbbított levél elejéhez';
$strForwardSuccessInfo ='Az üzenet továbbítása megtörtént';
$strForwardFailInfo = 'Az üzenet továbbítása nem sikerült';
$strForwardAlreadyDone = 'Ezt az üzenetet már sikeresen továbbítottuk arra az e-mail címre';
$strForwardCountReached = 'Elérte a továbbítások legnagyobb számát';
$strForwardNoteLimitReached = 'Elérte a személyes jegyzet legnagyobb hosszát';
$strForwardFooter = 'Ezt az üzenetet [FORWARDEDBY] továbbította Önnek.
  Ön nem rendelte meg automatikusan ezt a hírlevelet.
  A hírlevél megrendeléséhez keresse fel';
$strForward = 'Továbbítás';
$strFwd = 'Fwd'; # short version of forward for email subject
?>