<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strName                = 'Nama';
$strAddress             = 'Alamat';
$strEmail               = 'Email';
$strTown                = 'Kota';
$strPostcode            = 'KodePos';
$strSubscribeInfo       = 'Berlangganan satu atau lebih newsletter menggunakan form di bawah ini';
$strRequired            = 'wajib diisi';
$strSubscribeTitle      = 'Berlangganan Newsletter';
$strPleaseSelect        = 'Pilih Newsletter yang anda inginkan';
$strSubmit              = 'Berlangganan Newsletter yang dikehendaki';
$strNotAvailable        = 'Maaf, belum ada Newsletter';
$strEnterName           = 'Mohon isikan nama anda';
$strEnterEmail          = 'Mohon isikan alamat email anda';
$strInvalidHostInEmail  = 'Maaf, tak dapat mengirimkan email ke domain tersebut, mohon diperiksa ulang alamat email yang anda berikan';
$strEnterList           = 'Mohon pilih Newsletter yang diinginkan';
$strPleaseEnter         = 'Mohon isikan';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Terima kasih telah berlangganan newsletter kami.';
$strThanks              = 'Terima kasih telah berlangganan newsletter kami.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Email anda [email] telah dimasukkan dalam sistem kami. Anda akan menerima email berisi konfirmasi daftar Newsletter langganan anda.';
$strEmailConfirmation   = 'Email anda [email] telah dimasukkan ke dalam sistem kami. Anda akan menerima email berisi permintaan konfirmasi. Pastikan bahwa anda meng-klik link yang ada dalam email tersebut untuk melakukan konfirmasi berlangganan.';
$strEmailFailed          = 'Maaf, gagal mengirimkan email konfirmasi, mohon klik "Ulangi" untuk mencoba lagi. Jika tetap tak berhasil, mungkin alamat email anda masuk dalam Daftar Hitam kami, sehingga anda tak dapat menerima email dari sistem newsletter kami. Jika benar demikian, mohon hubungi administrator.';
$strUnsubscribeTitle    = 'Berhenti berlangganan Newsletter';
$strUnsubscribeDone     = 'Anda telah berhenti berlangganan dan anda akan menerima email konfirmasi segera.';
$strBack                = 'Kembali';
$strUnsubscribeInfo     = 'Berhenti berlangganan Newsletter';
$strContinue            = 'Lanjutkan';
$strUnsubscribeSelect   = 'Mohon pilih newsletter yang ingin dihentikan langganannya';
$strAllLists            = 'Semuanya';
$strNoLists             = 'Tak ada';
$strUnsubscribeRequestForReason = 'Sayang sekali anda tak tertarik pada newsletter kami lagi. Untuk membantu kami meningkatkan layanan, kami akan sangat berterima kasih bila anda dapat memberitahukan alasannya:';
$strUnsubscribeFinalInfo = '<br/><b>Mohon diperhatikan</b>: halaman ini adalah untuk menghentikan pengiriman email dari sistem kami <b>selamanya</b>. Jika anda ingin merubah email anda, atau jika anda ingin mengganti langganan newsletter, mohon untuk <a href="[PREFERENCESURL]">mengubah pilihan anda</a> saja';
$strNoListsFound        = 'Maaf, anda tidak berlangganan newsletter apapun dengan alamat email ini';
$strResubmit            = 'Kirim Ulang Email';
$strUnsubscribeSubmit   = 'Berhenti berlangganan Newsletter yang terpilih';
$strValuesMissing       = 'Isian yang diminta untuk kolom berikut ini tidak ada';
$strConfirmInfo         = 'Terima kasih atas konfirmasi berlangganan newsletter anda. Daftar newsletter langganan anda ada di bawah ini';
$strConfirmTitle        = 'Halaman konfirmasi keanggotaan';
$strUserNotFound        = 'User tidak ditemukan';
$strUserAlreadyInitialised = 'Maaf, password anda telah dikirimkan';
$strConfirmFailInfo     = 'Maaf, permintaan konfirmasi anda tak dikenali. Pastikan anda menggunakan alamat web yang lengkap seperti yang tertulis dalam email yang anda terima. Terkadang alamat web ini terpisah menjadi beberapa baris.';
$strPreferHTMLEmail     = 'Saya ingin menerima email dalam bentuk HTML';
$strPreferTextEmail     = 'Saya ingin menerima email dalam bentuk teks biasa';
$strPreferredFormat      = 'Bentuk Email yang disukai:';
$strText                 = 'Teks';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Perbarui pilihan anda';
$strPreferencesInfo     = 'Mohon pastikan bahwa informasi di bawah ini benar, dan klik tombol "Update"';
$strUpdatePreferences   = 'Update';
$strPreferencesEmailChanged = 'Email anda telah diganti. Mohon klik link di dalam email yang nanti anda terima untuk mengkonfirmasi alamat email anda yang baru';
$strYouAreBlacklisted = 'Email anda ada dalam Daftar Hitam kami, yang berarti anda pernah meminta kami untuk menghentikan pengiriman newsletter.<br/>
Untuk dapat menerima email kembali, perlu dilakukan intervensi manual oleh administrator kami. Mohon hubungi kami dengan menyebutkan secara jelas bahwa anda
ingin menerima newsletter lagi, dan kami akan menghapus nama anda dari Daftar Hitam kami';
$strPreferencesNotificationSent = 'Anda akan menerima email tentang perubahan';
$strPreferencesUpdated = 'Terima kasih. Kami telah memperbarui informasi anda.';
$strClickHere          = 'Klik Di Sini';
$strThisLink           = 'link ini';
$strToUnsubscribe      = 'Jika anda tidak ingin menerima newsletter lagi, ';
$strToUpdate           = 'Untuk memperbarui pilihan anda atau untuk berhenti berlangganan, kunjungi';
$strSendHTML           = 'Kirim email HTML';
$strYes                = 'Ya';
$strNo                 = 'Tidak';
$strUnsubscribe        = 'Berhenti berlangganan';
$strAllMailinglists    = 'Semua newsletter';
$strAttachmentIntro     = 'Pesan ini berisi lampiran yang dapat dilihat melalui web browser:';
$strLocation           = 'Lokasi';
$strFrequency           = 'Seberapa sering pesan dikirimkan';
$strHourly             = 'Per Jam';
$strDaily               = 'Per Hari';
$strWeekly             = 'Per Minggu';
$strMonthly             = 'Per Bulan';
$strChoosePassword      = 'Mohon isikan password';
$strConfirmPassword    = 'Konfirmasi password';
$strEnterPassword       = 'Mohon isikan password';
$strForgotPassword     = 'Lupa Password';
$strPassword           = 'Password';
$strPassword2           = 'Konfirmasi Password';
$strPasswordsNoMatch    = 'Password tidak sama';
$strEmailsNoMatch     = 'Alamat email yang anda isikan tidak sama';
$strInvalidPassword     = 'Error: email atau password tidak valid';
$strPasswordSent        = 'Password telah dikirimkan ke email anda. Anda akan menerimanya beberapa saat kemudian';
$strPasswordRemindSubject = 'Password anda untuk newsletter kami';
$strPasswordRemindMessage = 'Password anda adalah ';
$strPasswordRemindInfo = 'Untuk menerima password lewat email, isikan alamat email anda dan klik tombol "'.$strForgotPassword.'"';
$strLogin               = 'Login';
$strLoginTitle          = 'Mohon isikan alamat email dan password anda';
$strLoginInfo           = 'Halaman ini membutuhkan password. Isikan alamat email dan password anda';
$strPersonalLocationInfo = '
  <p>Halaman ini membutuhkan identifikasi pribadi yang dapat ditemukan dalam setiap email yang kami kirimkan pada anda.<br/>
  Jika anda mengklik lokasi tersebut, dan mendapat pesan kesalahan ini, pastikan bahwa anda telah memasukkan seluruh baris ke
  dalam browser anda. Terkadang lokasi ini terpotong menjadi beberapa baris.</p>
  <p>Jika anda tidak tahu lokasi ini, anda dapat meminta email yang akan memberikan lokasi tersebut.
  Masukkan alamat email anda dan klik "'.$strContinue.'"</p>
';
$strPersonalLocationSent = '<h1>Sukses! Anda akan menerima pesan berisi lokasi pribadi anda sesaat lagi</h1>';
$strUserExists   = '<br/>Telah ada user yang memakai alamat email tersebut, dan menurut catatan kami memakai password yang berbeda';
$strUserExistsExplanationStart = '<br/>Untuk memperoleh password anda, klik ';
$strUserExistsExplanationLink = 'di sini';
$strUserExistsExplanationEnd = ' untuk menuju halaman di mana anda dapat meminta lokasi pribadi anda';
$strForwardTitle = 'Meneruskan Pesan Pada Seseorang';
$strForwardSubtitle = 'Meneruskan pesan dengan subjek ';
$strForwardEnterEmail = 'Mohon isikan alamat email valid yang akan menerima pesan terusan ini';
$strForwardSuccessInfo ='Pesan telah diteruskan';
$strForwardFailInfo = 'Pesan gagal diteruskan';
$strForwardAlreadyDone = 'Pesan ini telah berhasil diteruskan ke alamat email tersebut';
$strForwardFooter = 'Pesan ini diteruskan kepada anda oleh [FORWARDEDBY].
  Anda belum berlangganan newsletter ini.
  Untuk berlangganan newsletter ini, silahkan ke';
$strForward = 'Forward';
$strFwd = 'Fwd'; # short version of forward for email subject
?>