<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             	= 'ISO-8859-1';
$strName                	= 'Nome';
$strAddress             	= 'Indirizzo';
$strEmail               	= 'Email';
$strTown                	= 'Comune';
$strPostcode            	= 'CAP';
$strSubscribeInfo       	= 'Iscriviti ad una o pi&ugrave; mailinglist utilizzando il seguente modulo';
$strRequired            	= 'I campi segnati in rosso sono obbligatori';
$strSubscribeTitle      	= 'Iscriviti alla nostra mailinglist';
$strPleaseSelect        	= 'Per favore, seleziona la lista a cui ti vuoi iscrivere';
$strSubmit              	= 'Iscriviti alle mailinglist selezionate';
$strNotAvailable        	= 'Spiacenti, ma non ci sono liste disponibili';
$strEnterName           	= 'Per favore, inserisci il tuo nome';
$strEnterEmail          	= 'Per favore, inserisci il tuo indirizzo email';
$strConfirmEmail      		= 'Conferma il tuo indirizzo email';
$strInvalidHostInEmail  	= 'Spiacenti, ma il tuo indirizzo email non &egrave; raggiungibile: controlla di averlo inserito correttamente';
$strEnterList           	= 'Per favore, seleziona una lista a cui iscriverti';
$strPleaseEnter         	= 'Per favore, inserisci il tuo';
# the thanks message can contain placeholders
#$strThanks             		= 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              	= 'Grazie per esserti iscritto alle nostre liste.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation  	= 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   	= 'Il tuo indirizzo email ([email]) &egrave; stato aggiunto nel nostro sistema. A breve riceverai una email con la richiesta di confermare la tua iscrizione. Per favore, clicca sul link contenuto nel messaggio per confermarla.';
$strEmailFailed         	= "Spiacenti, l'invio della email di conferma non &egrave; riuscito... clicca su 'Riprova' per ritentare. Se i problemi dovessero persistere, potrebbe essere che il tuo indirizzo sia finito nella nostra 'black list', il che significa che non puoi ricevere messaggi dalla nostra mailinglist. In tal caso contatta l'amministratore.";
$strUnsubscribeTitle    	= 'Cancellati dalla nostra mailinglist';
$strUnsubscribeDone     	= 'Sei stato cancellato dalle mailinglist che hai selezionato: riceverai a breve una email di conferma.';
$strBack                	= 'Indietro';
$strUnsubscribeInfo     	= 'Cancellati dalla nostra mailinglist';
$strContinue            	= 'Procedi';
$strUnsubscribeSelect   	= 'Per favore, seleziona le liste da cui ti vuoi cancellare';
$strAllLists            	= 'Tutte le liste';
$strNoLists             	= 'Nessuna';
$strUnsubscribeRequestForReason = 'Ci spiace che tu non sia pi&ugrave; interessato alla nostra newsletter. Per aiutarci a migliorare il servizio, ti saremmo grato se ci indicassi il motivo della tua decisione:';
$strUnsubscribeFinalInfo 	= '<br/><b>Attenzione</b>: questa pagina consente di annullare la sottoscrizione alla nostra newsletter <b>per sempre</b>. Se vuoi semplicemente cambiare il tuo indirizzo email o modificare le tue preferenze, utilizza <a href="[PREFERENCESURL]">la seguente pagina</a>';
$strNoListsFound        	= 'Spiacenti, ma non sei iscritto a nessuna mailinglist con questa email';
$strResubmit            	= "Reinvia l'email";
$strUnsubscribeSubmit   	= 'Cancellati dalle mailinglist selezionate';
$strValuesMissing       	= 'I seguenti campi obbligatori sono mancanti';
$strConfirmInfo         	= "Grazie per aver confermato l'iscrizione alle nostre liste. Le liste a cui sei iscritto sono elencate di seguito";
$strConfirmTitle        	= 'PHPlist pagina di conferma delle iscrizioni';
$strUserNotFound        	= 'Utente non trovato';
$strUserAlreadyInitialised 	= 'Spiacenti, ma la tua password &egrave; stata gi&agrave; settata';
$strConfirmFailInfo     	= "Spiacenti, la tua richiesta di conferma non &egrave; stata riconosciuta. Verifica di aver inserito correttamente l'indirizzo web come indicato nella mail che hai ricevuto... in alcuni casi questo viene spezzato su pi&ugrave; righe";
$strPreferHTMLEmail     	= 'Preferisco ricevere le email in formato HTML';
$strPreferTextEmail     	= 'Preferisco ricevere le email in formato testo';
$strPreferredFormat  		= 'Formato preferito per le email:';
$strText     				= 'Testo';
$strHTML    				= 'HTML';
$strPreferencesTitle    	= 'Aggiorna le tue preferenze';
$strPreferencesInfo     	= "Per favore, controlla che il seguente dato sia corretto e clicca sul bottone 'Aggiorna'";
$strUpdatePreferences   	= 'Aggiorna';
$strPreferencesEmailChanged = 'Il tuo indirizzo email &egrave; stato aggiornato. Per favore, clicca sul link contenuto nel messaggio che riceverai a breve per confermare il nuovo indirizzo';
$strYouAreBlacklisted 		= "Il tuo indirizzo email compare nella nostra 'black list', il che significa che ci hai chiesto di non inviarti pi&ugrave; alcuna informazione.<br/>
Per ricevere alcora dei messaggi, &egrave; richiesto l'intervento manuale dell'amministratore. 
Per favore contattaci indicando esplicitamente che desideri ricevere la nostra newsletter nuovamente";
$strPreferencesNotificationSent = 'Riceverai un messaggio email con le modifiche';
$strPreferencesUpdated  	= 'Grazie per i dati che ci hai fornito. Abbiamo aggiornato le tue informazioni personali.';
$strClickHere    			= 'Clicca qui';
$strThisLink            	= 'questo link';
$strToUnsubscribe  			= 'Per cancellarti da questa lista';
$strToUpdate    			= 'Per aggiornare le tue preferenze e per annullare la tua iscrizione visita questo link';
$strSendHTML            	= 'Invia email in HTML';
$strYes                 	= 'S&igrave;';
$strNo      				= 'No';
$strUnsubscribe    			= "Annulla l'iscrizione";
$strAllMailinglists     	= 'Tutte le newsletters';
$strAttachmentIntro  		= 'Questo messaggio contiene allegati che possono essere visti con un browser web:';
$strLocation    			= 'Luogo';
$strFrequency           	= 'Indica la frequenza con cui desideri ricevere i messaggi';
$strHourly    				= 'Ogni ora';
$strDaily    				= 'Quotidianamente';
$strWeekly    				= 'Settimanalmente';
$strMonthly    				= 'Mensilmente';
$strChoosePassword   		= 'Per favore, scegli una password';
$strConfirmPassword   		= 'Conferma la password';
$strEnterPassword  			= 'Per favore, inserisci la tua password';
$strForgotPassword  		= 'Password dimenticata';
$strPassword    			= 'Password';
$strPassword2    			= 'Conferma Password';
$strPasswordsNoMatch    	= 'Le password non coincidono';
$strEmailsNoMatch       	= 'Gli indirizzi email che hai inserito non coincidono';
$strInvalidPassword  		= 'Errore: email o password non validi';
$strPasswordSent   			= 'La tua password &egrave; stata inviata al tuo indirizzo email. Dovresti riceverla a breve';
$strPasswordRemindSubject 	= "La tua password d'accesso alla nostra newsletter";
$strPasswordRemindMessage 	= 'La tua password &egrave; ';
$strPasswordRemindInfo  	= 'Per ricevere la tua password per email, inserisci il tuo indirizzo e clicca sul pulsante "'.$strForgotPassword.'"';
$strLogin    				= 'Login';
$strLoginTitle     			= 'Per favore, inserisci il tuo indirizzo email e la password';
$strLoginInfo    			= 'Questa pagina richiede una password.';
$strPersonalLocationInfo 	= "
 <p>Questa pagina richiede un identificativo personale che pu&ograve; essere trovato in uno qualsiasi dei messaggi che ti abbiamo inviato.<br/>
 Se hai seguito un link ed hai ottenuto questo errore, per favore, assicurati di avere inserito tutto il link nella barra degli indirizzi del
 tuo browser. A volte pu&ograve; succedere che i link contenuti nei messaggi vengano riportati su pi&ugrave; linee.
 <p>Se non conosci l'indirizzo esatto, puoi richiedere una email che te lo
 indichi. Per favore, inserisci la tua email nel campo seguente e clicca su 'Continua'
";
$strPersonalLocationSent 	= '<h1>Eseguito! Dovresti ricevere a breve un messaggio email con il tuo link personale</h1>';
$strUserExists   			= '<br/>Un utente con la tua email esiste gi&agrave;, ma con una password diversa';
$strUserExistsExplanationStart 	= '<br/>Per ottenere la tua password, clicca ';
$strUserExistsExplanationLink 	= 'qui';
$strUserExistsExplanationEnd 	= ' per visitare la pagina dove puoi richiedere i tuoi dati personali';
$strExplainBlacklist 		= 'The email that you enter here will be recorded in our database with the sole purpose of blocking any email sent from this system.';
$strForwardTitle	 		= 'Inoltra un messaggio a qualcuno';
$strForwardSubtitle 		= 'Inoltra il messaggio con titolo ';
$strForwardEnterEmail 		= 'Per favore, indica un indirizzo email valido a cui inoltrare il messaggio';
$strForwardInvalidEmail 	= '%s non è un indirizzo email valido';
$strForwardBlacklistedEmail = 'Il destinatario ha richiesto di non dicevere più email da questo sistema.';
$strForwardEnterEmails 		= 'Inserisci in questo box un massimo di %s indirizzi email validi a cui desideri inoltrare il messaggio, uno per riga';
$strForwardPersonalNote 	= 'Puoi inserire un semplice messaggio di testo (per un massimodi %d caratteri) che sar&agrave; posizionato in testa alla email inoltrata';
$strForwardSuccessInfo 		= 'Il messaggio &egrave; stato inoltrato';
$strForwardFailInfo 		= "L'inoltro del messaggio &egrave; fallito";
$strForwardAlreadyDone 		= "Questo messaggio &egrave; gi&agrave; stato inoltrato all'indirizzo specificato";
$strForwardCountReached 	= 'Numero massimo di destinatari raggiunto';
$strForwardNoteLimitReached = 'Lunghezza massima del messaggio personale raggiunta';
$strForwardFooter 			= "Questo messaggio ti &egrave; stato inoltrato da [FORWARDEDBY].
  Questo non significa che tu sia stato iscritto a questa newsletter.
  Per iscriverti, vai a ";
$strForward 				= 'Inoltra';
$strFwd 					= 'Fwd'; # short version of forward for email subject
?>
