<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strName                = '名前';
$strAddress             = '住所';
$strEmail               = '電子メール';
$strTown                = '街';
$strPostcode            = '郵便番号';
$strSubscribeInfo       = '以下のフォームを使い1つ以上のメールマガジンを登録してください。';
$strRequired            = '必須項目';
$strSubscribeTitle      = 'メールマガジンの購読';
$strPleaseSelect        = '購読したいメールマガジンを選択してください。';
$strSubmit              = '選択したメールマガジンの購読';
$strNotAvailable        = 'すいません。現在、利用可能なメールマガジンはありません。';
$strEnterName           = 'お名前を入力してください';
$strEnterEmail          = '電子メールアドレスを入力してください';
$strInvalidHostInEmail  = 'すいません。そのドメインへの電子メールを送ることはできません。正しい電子メールアドレスを入力しているか確認してください。';
$strEnterList           = '購読したいメールマガジンを選択してください。';
$strPleaseEnter         = '入力してください：';
# ありがとうメッセージにはプレースホルダーを含めることができます。
#$strThanks              = '[FIRST NAME]さん、<br/>メールマガジンを購読いただきありがとうございます。';
$strThanks              = 'メールマガジンに購読いただきありがとうございます。';
# 登録認証のお願いメッセージにはプレースホルダーを含めることができます。
#$strEmailConfirmation   = 'あなたの電子メールアドレス [email] がシステムに追加されました。間もなく購読したメールマガジンについて購読確定のお願いが電子メールで送信されます。';
$strEmailConfirmation   = 'あなたの電子メールアドレスがシステムに追加されました。間もなく購読したメールマガジンについて購読確定のお願いが電子メールで送信されます。';
$strEmailFailed          = 'すいません。購読確定のお願いの電子メールを送信することに失敗しました。再度、「Reload」をクリックしてください。もし、まだ失敗するようでしたら、あなたの電子メールアドレスは"購読解除済リスト"に追加されているかもしれません。、これは、私たちのメールマガジンシステムから電子メールを受け取れないことを意味しています。そのような場合、管理者までご連絡ください。';
$strUnsubscribeTitle    = 'メールマガジンの購読解除';
$strUnsubscribeDone     = 'メールマガジンの購読を解除しました。間もなく確認の電子メールが送信されますのでご確認ください。';
$strBack                = '戻る';
$strUnsubscribeInfo     = 'メールマガジンの購読解除';
$strContinue            = '続ける';
$strUnsubscribeSelect   = '購読解除したいメールマガジンを選択してください。';
$strAllLists            = '全てのメールマガジン';
$strNoLists             = 'None of them';
$strUnsubscribeRequestForReason = 'メールマガジンに興味がなくなったことを残念に思います。私たちのサービスを改善するために、理由を教えていただければ幸いです。';
$strUnsubscribeFinalInfo = '<br/><b>注意</b>: このページはわたしたちのメールマガジンシステムから<b>永遠</b>に電子メールを受け取ることを停止します。もし電子メールアドレスを変更したいのでしたら、または、読みたいメールマガジンを変更したいのでしたら、代わりに、<a href="[PREFERENCESURL]">あなたの選択している情報</a>を更新してください。';
$strNoListsFound        = 'すいません。この電子メールアドレスではメールマガジンを登録できません。';
$strResubmit            = 'Re-Submit Email';
$strUnsubscribeSubmit   = '選択しているメールマガジンの購読解除';
$strValuesMissing       = '次の必須項目に入力されていません。';
$strConfirmInfo         = 'メールマガジンに購読いただきありがとうございます。購読したメールマガジンは下記です。';
$strConfirmTitle        = 'PHPlist メンバーシップ設定ページ';
$strUserNotFound        = 'ユーザがみつかりません。';
$strUserAlreadyInitialised = 'すいません。あなたのパスワードは既に設定されています。';
$strConfirmFailInfo     = 'すいません。購読の確定はされませんでした。受け取った電子メールに記載されている完全なWEBアドレスを確かめてください。ときどき、このWEBアドレスは複数行にわかれて表示されています。';
$strPreferHTMLEmail     = '私はHTMLフォーマットで電子メールを受け取ります。';
$strPreferTextEmail     = '私はTextフォーマットで電子メールを受け取ります。';
$strPreferredFormat      = '電子メールの優先フォーマット:';
$strText                 = 'Text';
$strHTML                = 'HTML';
$strPreferencesTitle    = '選択した情報の更新';
$strPreferencesInfo     = '下記の情報が正しいことを確認し、"更新"ボタンをクリックしてください。';
$strUpdatePreferences   = '更新';
$strPreferencesEmailChanged = '電子メールが変更されました。新しい電子メールアドレスを確定するための電子メールを送信しますので、電子メールに記載されたリンクをクリックしてください。';
$strYouAreBlacklisted = 'あなたの電子メールアドレスは購読解除済リストに掲載されています。いかなるメッセージもあなたには決して送信されません。 <br/>
また電子メールを受け取るために、管理者による手動の解除が必要です。またメールマガジンを受け取りたいことをはっきりと明言しわたしたちにコンタクトしてください。購読解除済リストからあなたをはずします。';
$strPreferencesNotificationSent = 'あなたは変更箇所を記載した電子メールを受け取ります。';
$strPreferencesUpdated = 'ありがとうございます。あなたの情報は更新されました。';
$strClickHere          = 'ここをクリック';
$strThisLink           = 'このリンク';
$strToUnsubscribe      = 'もし、いかなるメールマガジンも受け取りたくないならば、こちらをクリック：';
$strToUpdate           = 'あなたの情報を更新したり購読解除する場合はこちらをクリック：';
$strSendHTML           = 'HTMLメールを受信する';
$strYes                = 'はい';
$strNo                 = 'いいえ';
$strUnsubscribe        = '登録解除';
$strAllMailinglists    = 'すべてのメールマガジン';
$strAttachmentIntro     = 'このメッセージにはウェブブラウザでみることができる添付ファイルを含まれています:';
$strLocation           = 'ロケーション';
$strFrequency           = 'メッセージを送る頻度';
$strHourly             = '毎時';
$strDaily               = '毎日';
$strWeekly             = '毎週';
$strMonthly             = '毎月';
$strChoosePassword      = 'パスワードを選択してください';
$strConfirmPassword    = 'パスワード（確認）';
$strEnterPassword       = 'パスワードを入力してください';
$strForgotPassword     = 'パスワードを忘れた方へ';
$strPassword           = 'パスワード';
$strPassword2           = 'パスワード（確認）';
$strPasswordsNoMatch    = 'パスワードが同じでありません。';
$strEmailsNoMatch     = '入力した電子メールアドレスがマッチしません。';
$strInvalidPassword     = 'エラー: 電子メールまたはパスワードが妥当でありません。';
$strPasswordSent        = 'あなたのパスワードを電子メールで送りましたので、数分で電子メールを受信してください。';
$strPasswordRemindSubject = 'メールマガジンに対するあなたのパスワード';
$strPasswordRemindMessage = 'Your password is ';
$strPasswordRemindInfo = '電子メールでパスワードを受け取るために、電子メールアドレスを入力して、"'.$strForgotPassword.'" ボタンをクリックしてください。';
$strLogin               = 'ログイン';
$strLoginTitle          = '電子メールアドレスとパスワードを入力してください。';
$strLoginInfo           = 'このページはパスワードが必要です。電子メールアドレスとパスワードを入力してください。';
$strPersonalLocationInfo = '
  <p>このページは、メールマガジン購読者の区別を必要としています。このメールマガジン購読者の区別には、ロケーションをクリックすることが必要で、あなたに送信される各メッセージに記載されています。<br/>
  もしあなたがこのロケーションをクリックし、エラーが出るならば。あなたのブラウザのロケーションボックス内に完全な行を確実にペーストしてください。ときどきロケーションが複数行にわたっています。</p>
  <p>もしあなたがロケーションを知らなければ、あなたはロケーションを知らせる電子メールをリクエストすることができます。
  ボックスに電子メールアドレスを入力して、"続ける"をクリックしてください。
';
$strPersonalLocationSent = '<h1>成功しました！まもなくあなたのパーソナルロケーションが記載されたメッセージを受信します。</h1>';
$strUserExists   = '<br/>その電子メールアドレスをもつユーザは既に存在し、異なったパスワードになっています。';
$strUserExistsExplanationStart = '<br/>あなたのパスワードを入手するために、クリック ';
$strUserExistsExplanationLink = 'ここ';
$strUserExistsExplanationEnd = ' パーソナルロケーションをリクエストできるページにいく';
$strForwardTitle = 'メッセージを誰かに転送する';
$strForwardSubtitle = 'メールタイトル付でメッセージを転送する ';
$strForwardEnterEmail = '転送するために妥当な電子メールアドレスを入力してください。';
$strForwardSuccessInfo ='メッセージは転送されました。';
$strForwardFailInfo = 'メッセージの転送は失敗しました。';
$strForwardAlreadyDone = 'このメッセージは既にうまくその電子メールアドレスに転送されました。';
$strForwardFooter = 'このメッセージは[FORWARDEDBY]によりあなたに転送されました。
  このメールマガジンは自動的に登録されません。
  このメールマガジンを購読するには以下のアドレスをクリックしてください。';
$strForward = '転送';
$strFwd = 'Fwd'; # short version of forward for email subject
?>