<?php

# language dependent text used in the interface for users (not admin)
#Translated to norwegian by Ronny Williams, ronny@williams.no

$strCharSet             = 'UTF-8';
$strName                = 'Navn';
$strAddress             = 'Adresse';
$strEmail               = 'Epost adresse';
$strTown                = 'By';
$strPostcode            = 'Postnummer';
$strSubscribeInfo       = 'Abonner på et eller flere av våre nyhetsbrev under';
$strRequired            = 'Obligatoriske felt';
$strSubscribeTitle      = 'Abonner på våre nyhetsbrev';
$strPleaseSelect        = 'Vennligst velg de nyhetsbrev du ønsker å abonnere på';
$strSubmit              = 'Abonner på de valgte nyhetsbrev';
$strNotAvailable        = 'Beklager, men det er ingen nyhetsbrev tilgjengelige';
$strEnterName           = 'Vennligst skriv inn navnet ditt';
$strEnterEmail          = 'Vennligst skriv inn e-post adressen din';
$strInvalidHostInEmail  = 'Beklager, epost til det domene kan ikke sendes, sjekk at du har lagt inn riktig e-mail adresse';
$strEnterList           = 'Velg et nyhetsbrev å abonnere på';
$strPleaseEnter         = 'Skriv inn ditt';
# the thanks message can contain placeholders
#$strThanks              = 'Kjære [FIRST NAME], <br/>Takk for at du abonnerer på våre nyhetsbrev.';
$strThanks              = 'Takk for at du abonnerer på våre nyhetsbrev.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Din epostadresse [email] er registrert i vårt system. Du vil motta en e-mail med bekreftelse på hvilke nyhetsbrev du har abonnert på.';
$strEmailConfirmation   = 'Din emailadresse er registrert i vårt system. Du vil snart motta en epost med en URL som du må klikke på for å bekrefte ditt medlemssskap. ';
$strEmailFailed          = 'Beklager, sending av epost for å bekrefte ditt abonnement, mislyktes, klikk "Oppfrisk" for å prøve igjen. Hvis det fortsatt ikke virker, kan det være at epost adressen din står på vår "Svarteliste", som betyr at du ikke kan motta noe epost fra vårt nyhetsbrev system. Da må du kontakte administrator.';
$strUnsubscribeTitle    = 'Meld deg av våre nyhetsbrev';
$strUnsubscribeDone     = 'Du er nå avmeldt fra våre nyhetsbrev og vil snart motta en epost med bekreftelse.';
$strBack                = 'Tilbake';
$strUnsubscribeInfo     = 'Meld deg av våre nyhetsbrev';
$strContinue            = 'Fortsett';
$strUnsubscribeSelect   = 'Vennligst velge hvilke nyhetsbrev du ønsker å avbestille';
$strAllLists            = 'Alle lister';
$strNoLists             = 'Ingen av dem';
$strUnsubscribeRequestForReason = 'Vi beklager at du ikke lenger er interessert i vårt nyhetsbrev. For å forbedre vår tjeneste, ville vi være takknemlige dersom du kunne fortelle oss hvorfor:';
$strUnsubscribeFinalInfo = '<br/><b>Obs</b>: denne siden er for å stoppe mottagelse av flere nyhetsbrev <b>for alltid</b>. HVis du vil endre din epost adresse, eller ønsker å forndre hvilke nyhetsbrev du mottar, vennligst <a href="[PREFERENCESURL]">oppdater dine preferanser.</a> istedet';
$strNoListsFound        = 'Beklager, men du abonnerer ikke på noen av våre nyhetsbrev med denne epostadressen';
$strResubmit            = 'Re-send Epost adresssen';
$strUnsubscribeSubmit   = 'Meld deg av valgte nyhetsbrev';
$strValuesMissing       = 'Følgende obligatoriske felt mangler';
$strConfirmInfo         = 'Takk for din bekreftelse av ditt abonnement på nyhetsbrev. Nyhetsbrevene du abonnerer på er listet under';
$strConfirmTitle        = 'PHPlist medlemsskaps side';
$strUserNotFound        = 'Bruker ikke funnet';
$strUserAlreadyInitialised = 'Beklager, men passordet er allerede sendt';
$strConfirmFailInfo     = 'Beklager, men ditt ønske om bekreftelse ble ikke gjenkjent. Vennligst bruk hele web adressen oppgitt i den mottatte epost. Noen ganger går denne web adressen over flere linjer.';
$strPreferHTMLEmail     = 'Jeg ønsker å motta epost i HTML format';
$strPreferTextEmail     = 'Jeg ønsker å motta epost i Tekst format';
$strPreferredFormat      = 'Ønsket format for epost:';
$strText                 = 'Tekst';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Oppdater dine preferanser';
$strPreferencesInfo     = 'Vennligst bekreft at informasjonen under er korrekt og klikk på "Oppdater" knappen';
$strUpdatePreferences   = 'Oppdater';
$strPreferencesEmailChanged = 'Din epost adresse er endret. Vennligst klikk på linken i eposten du snart vil motta for å bekrefte din nye epost adresse';
$strYouAreBlacklisted = 'Din epost adressse er listet i vår "Svarteliste", som betyr at du har fortalt oss aldri mer å sende deg noen nyhetsbrev. <br/>
For å kunne motta noen nyhetsbrev igjen, vår admistrator må varsles. Vennligst kontakt oss og gi oss beskjed om at du ønsker å motta nyhetsbrev igjen, og vi vil fjerne deg fra svartelisten ';
$strPreferencesNotificationSent = 'Du vil motta en epost med endringene';
$strPreferencesUpdated = 'Takk for ditt endring. Vi har oppdatert din informasjon.';
$strClickHere          = 'Klikk her';
$strThisLink           = 'denne linken';
$strToUnsubscribe      = 'Hvis du ikke ønsker å motta flere nyhetsbrev ';
$strToUpdate           = 'For å oppdatere dine preferanser og for melde deg av nyhetsbrev besøk';
$strSendHTML           = 'Send HTML epost';
$strYes                = 'Ja';
$strNo                 = 'Nei';
$strUnsubscribe        = 'Meld deg av liste';
$strAllMailinglists    = 'Alle nyhetsbrev';
$strAttachmentIntro     = 'Denne meldingen inneholder vedlegg som kan leses i en nettleser:';
$strLocation           = 'Sted';
$strFrequency           = 'Hvor ofte sender vi deg meldinger';
$strHourly             = 'Hver time';
$strDaily               = 'Daglig';
$strWeekly             = 'Ukentlig';
$strMonthly             = 'Månedlig';
$strChoosePassword      = 'Velg et passord';
$strConfirmPassword    = 'Bekreft passord';
$strEnterPassword       = 'Skriv inn ditt passord';
$strForgotPassword     = 'Glemt passord';
$strPassword           = 'Passord';
$strPassword2           = 'Bekreft passord';
$strPasswordsNoMatch    = 'Passordene er ikke like';
$strEmailsNoMatch     = 'Epost adressene du skrev inn er ikke like';
$strInvalidPassword     = 'Feil: ugyldig epostadresse eller passord';
$strPasswordSent        = 'Passordet ditt er sendt til deg i epost. Du bør motta den i løpet av et par minutter';
$strPasswordRemindSubject = 'Ditt passord for våre nyhetsbrev';
$strPasswordRemindMessage = 'Ditt passord er ';
$strPasswordRemindInfo = ' For å motta nytt passord med epost. skriv inn din epostadresse og klikk på "'.$strForgotPassword.'" knappen.';
$strLogin               = 'Logg inn';
$strLoginTitle          = 'Skriv inn din epost adresse og passord';
$strLoginInfo           = 'Denne siden krever et passord. Skriv inn din epost adresse og passord';
$strPersonalLocationInfo = '
  <p>Denne siden krever en personlig identifikasjon som du finner på hver epost vi sender deg.<br/>
  Dersom du har klikket på denne linken, og får denne feilen, prøv å lime hele linjen inn i adressefeltet på din nettleser.
  Noen ganger går linken over flere linjer.</p>
  <p>Vet du ikke hvilken link du skal bruke, kan du be om en epost som viser deg dette.
  Skriv inn epost adressen din i boksen og klikk "Fortsett"
';
$strPersonalLocationSent = '<h1>Suksess! Du vil motta en epost med en link til din personlige side</h1>';
$strUserExists   = '<br/>En bruker med den epost adressen finnes allerede, og våre data inneholder et annet passord';
$strUserExistsExplanationStart = '<br/>For å kunne motta ditt passord, klikk ';
$strUserExistsExplanationLink = 'her';
$strUserExistsExplanationEnd = ' for å gå til siden der du kan be om linken til din personlige side';
$strForwardTitle = 'Videresend en melding til noen';
$strForwardSubtitle = 'Videresende meldingen med emne ';
$strForwardEnterEmail = 'Skriv inn en gyldig epost adresse å videresende til';
$strForwardSuccessInfo ='Meldingen er videresendt';
$strForwardFailInfo = 'Videresending av melding mislyktes';
$strForwardAlreadyDone = 'Meldingen er allerede vidersendt til den epost adressen';
$strForwardFooter = 'Denne meldingen er videresendt deg av [FORWARDEDBY].
  Du er ikke blitt automatisk påmeldt til dette nyhetsbrevet.
  For å abonnere på dette nyhetsbrevet, gå til';
$strForward = 'Videresend';
$strFwd = 'Videresend'; # short version of forward for email subject
?>