<?php

# language dependent text used in the interface for users (not admin)
# Polish translation by Agata Szczesniak
$strCharSet             = 'UTF-8';
$strName                = 'Imię i nazwisko';
$strAddress             = 'Adres';
$strEmail               = 'e-mail';
$strTown                = 'miasto';
$strPostcode            = 'kod pocztowy';
$strSubscribeInfo       = 'Za pomocą poniższego formularza można zasubskrybować nasze listy wysyłkowe';
$strRequired            = 'pole obowiązkowe';
$strSubscribeTitle      = 'Subskrypcja naszych list wysyłkowych';
$strPleaseSelect        = 'Należy wybrać listy do zasubskrybowania';
$strSubmit              = 'Subskrybuj wybrane listy wysyłkowe';
$strNotAvailable        = 'Niestety, nie ma teraz dostępnych list';
$strEnterName           = 'Proszę podać imię i nazwisko (lub pseudonim)';
$strEnterEmail          = 'Proszę wprowadzić adres e-mail';
$strInvalidHostInEmail  = 'Niestety, nie można dostarczać poczty e-mail do tej domeny; proszę sprawdzić, czy wpisany adres jest poprawny';
$strEnterList           = 'Proszę wybrać subskrybowaną listę';
$strPleaseEnter         = 'Proszę wprowadzić';
# the thanks message can contain placeholders
#$strThanks              = 'Dziękujemy za subskrypcję naszej listy.';
$strThanks              = 'Dziękujemy za subskrypcję naszej listy.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Adres [email] został dodany do naszego systemu. Wkrótce zostanie wysłane potwierdzenie subskrypcji.';
$strEmailConfirmation   = 'Adres [email] został dodany do naszego systemu. Wkrótce zostanie wysłana prośba o potwierdzenie subskrypcji. Aby potwierdzić subskrypcję, należy kliknąć odnośnik zawarty w wiadomości.';
$strEmailFailed					= 'Niestety, nie udało się wysłać wiadomości z prośbą o potwierdzenie subskrypcji. Aby spróbować ponownie, należy kliknąć ikonę "Odśwież".';
$strUnsubscribeTitle    = 'Rezygnacja z subskrypcji';
$strUnsubscribeDone     = 'Zrezygnowano z subskrypcji wybranych list wysyłkowych. Zostanie to potwierdzone pocztą elektroniczną.';
$strBack                = 'Wstecz';
$strUnsubscribeInfo     = 'Rezygnacja z przynajmniej jednej listy wysyłkowej';
$strContinue            = 'Kontynuuj';
$strUnsubscribeSelect   = 'Proszę wybrać listy, których subskrypcja ma być anulowana';
$strAllLists            = 'Wszystkie listy';
$strNoLists             = 'Żadna';
$strNoListsFound        = 'Niestety, ten adres e-mail nie występuje w subskrypcji żadnej z naszych list wysyłkowych.';
$strResubmit            = 'Ponownie podaj adres e-mail';
$strUnsubscribeSubmit   = 'Rezygnacja z wybranych list wysyłkowych';
$strValuesMissing       = 'Brakuje następujących danych';
$strConfirmInfo         = 'Dziękujemy za potwierdzenie subskrypcji naszych list. Poniżej znajduje się lista subskrybowanych list wysyłkowych.';
$strConfirmTitle        = 'Strona potwierdzenia subskrypcji - PHPlist';
$strUserNotFound        = 'Użytkownik nie został znaleziony';
$strUserAlreadyInitialised = 'Niestety, hasło zostało już ustawione';
$strConfirmFailInfo     = 'Niestety, prośba o potwierdzenie nie została rozpoznana. Należy użyć pełnego adresu internetowego z otrzymanej wiadomości. W niektórych programach pocztowych adres jest zawijany do następnego wiersza.';
$strPreferHTMLEmail     = 'Chcę otrzymywać wiadomości w formacie HTML';
$strPreferTextEmail     = 'Chcę otrzymywać wiadomości w formacie tekstowym.';
$strPreferredFormat			= 'Wybrany format wiadomości:';
$strText 								= 'Tekst';
$strHTML								= 'HTML';
$strPreferencesTitle    = 'Aktualizacja preferencji';
$strPreferencesInfo     = 'Prosimy o potwierdzenie poprawności poniższych informacji i kliknięcie przycisku "Aktualizuj".';
$strUpdatePreferences   = 'Aktualizuj';
$strPreferencesEmailChanged = 'Adres e-mail został zmieniony. Prosimy kliknąć odnośnik w wiadomości, która zostanie wysłana w celu potwierdzenia nowego adresu.';
$strPreferencesNotificationSent = 'Wysłana wiadomość będzie zawierać informacje o zmianach';
$strPreferencesUpdated = 'Dziękujemy za zgłoszenie. Informacje zostały aktualizowane.';
$strClickHere          = 'Kliknij tutaj';
$strThisLink           = 'ten odnośnik';
$strToUnsubscribe      = 'Aby zrezygnować z subskrypcji tej listy, odwiedź stronę';
$strToUpdate           = 'Aby zaktualizować preferencje, odwiedź stronę';
$strSendHTML           = 'Wyślij wiadomość w formacie HTML';
$strYes                = 'Tak';
$strNo                 = 'Nie';
$strUnsubscribe        = 'Rezygnuję';
$strAllMailinglists    = 'Wszystkie listy';
$strAttachmentIntro		 = 'Ta wiadomość zawiera załącznik, który nie może zostać odczytany przez przeglądarkę:';
$strLocation					 = 'Lokalizacja';
$strFrequency					 = 'Jak często mamy wysyłać wiadomości';
$strHourly						 = 'Co godzinę';
$strDaily							 = 'Co dzień';
$strWeekly						 = 'Co tydzień';
$strMonthly						 = 'Co miesiąc';
$strChoosePassword 		 = 'Prosimy wybrać hasło';
$strConfirmPassword 	 = 'Potwierdzenie hasła';
$strEnterPassword			 = 'Prosimy wprowadzić hasło';
$strForgotPassword		 = 'Zapomniałam/Zapomniałem hasła';
$strPassword					 = 'Hasło';
$strPassword2					 = 'Potwierdzenie hasła';
$strPasswordsNoMatch 	 = 'Wprowadzone hasła są różne';
$strInvalidPassword		 = 'Błędny adres e-mail lub hasło';
$strPasswordSent 		   = 'Hasło zostanie wysłane pocztą elektroniczną. Wiadomość powinna dotrzeć w ciągu kilku minut.';
$strPasswordRemindSubject = 'Hasło do list wysyłkowych';
$strPasswordRemindMessage = 'Hasło:';
$strPasswordRemindInfo = 'Aby otrzymać hasło pocztą elektroniczną, należy wprowadzić adres e-mail i kliknąć przycisk "Zapomniałam/Zapomniałem hasła".';
$strLogin							 = 'Zaloguj';
$strLoginTitle 				 = 'Prosimy wprowadzić adres e-mail i hasło';
$strLoginInfo					 = 'Dostęp do strony tylko podaniu hasła. Prosimy wprowadzić adres e-mail i hasło';
$strPersonalLocationInfo = '
	<p> Dostęp do strony wymaga osobistego identyfikatora, który znajduje się w każdej naszej wiadomości.<br/>
  Jeżeli po kliknięciu tego adresu internetowego wystąpi błąd, należy przekleić do pola adresu całą linię z przeglądarki. Czasami adres jest zawijany do kilku następnych wierszy.</p>
  <p>W wypadku nieznajomości tego adresu można zażądać wiadomości, w której zostanie on podany. Prosimy wprowadzić adres e-mail i kliknąć przycisk "Kontynuuj"
';
$strPersonalLocationSent = '<h1>Wkrótce zostanie wysłana wiadomość z osobistym identyfikatorem</h1>';

?>
