<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'ISO-8859-15';
$strName                = 'Nome';
$strAddress             = 'Morada';
$strEmail               = 'Correio Electr&oacute;nico';
$strTown                = 'Localidade';
$strPostcode            = 'C&oacute;digo Postal';
$strSubscribeInfo       = 'Use o formul&aacute;rio abaixo para subscrever uma ou mais das nossas listas de distribui&ccedil;&atilde;o';
$strRequired            = 'campo obrigat&oacute;rio';
$strSubscribeTitle      = 'Subscreva as nossas listas de distribui&ccedil;&atilde;o';
$strPleaseSelect        = 'Por favor seleccione a(s) lista(s) que pretende subscrever';
$strSubmit              = 'Subscreva as listas seleccionadas';
$strNotAvailable        = 'Lamentamos, mas ainda n&atilde;o existem listas dispon&iacute;veis.';
$strEnterName           = 'Por favor insira o seu nome';
$strEnterEmail          = 'Por favor introduza o seu endere&ccedil;o de correio electr&oacute;nico';
$strInvalidHostInEmail  = 'Lamentamos mas n&atilde;o conseguimos entregar correio electr&oacute;nico no dom&iacute;nio indicado. Por favor certifique-se que introduziu correctamente o seu endere&ccedil;o de correio electr&oacute;nico';
$strEnterList           = 'Por favor seleccione a lista que pretende subscrever';
$strPleaseEnter         = 'Por favor indique';
# the thanks message can contain placeholders
# $strThanks              = 'Obrigado por subscrever a(s) nossa(s) listas de distribui&ccedil;&atilde;o';
$strThanks              = 'Estimado(a) [FIRST NAME], <br/>Obrigado por subscrever a(s) nossa(s) listas de distribui&ccedil;&atilde;o';
# the EmailConfirmation message can contain placeholders
# $strEmailConfirmation   = 'O seu endere&ccedil;o de correio electr&oacute;nico foi acrescentado ao nosso sistema. Em breve receber&aacute; uma mensagem com a confirma&ccedil;&atilde;o da(s) lista(s) que subscreveu. Por favor certifique-se que clica no endere&ccedil;o enviado nessa mensagem para confirmar a sua subscri&ccedil;&atilde;o.';
$strEmailConfirmation   = 'O seu endere&ccedil;o de correio electr&oacute;nico [email] foi acrescentado ao nosso sistema. Em breve receber&aacute; uma mensagem com a confirma&ccedil;&atilde;o da(s) lista(s) que subscreveu. Por favor certifique-se que clica no endere&ccedil;o enviado nessa mensagem para confirmar a sua subscri&ccedil;&atilde;o.';
$strEmailFailed      = 'Lamentamos mas n&atilde;o conseguimos enviar-lhe o correio electr&oacute;nico solicitando a sua confirma&ccedil;&atilde;o. Por favor clique no bot&atilde;o "<em>Reload</em>" ou "Refrescar" para tentar novamente.';
$strUnsubscribeTitle    = 'Cancelar a sua subscri&ccedil;&atilde;o da(s) nossa(s) lista(s) de distribui&ccedil;&atilde;o';
$strUnsubscribeDone     = 'Procedemos ao cancelamento da sua subscri&ccedil;&atilde;o da(s) lista(s) de distribui&ccedil;&atilde;o seleccionada(s) e brevemente receber&aacute; uma confirma&ccedil;&atilde;o por correio electr&oacute;nico.';
$strBack                = 'Voltar atr&aacute;s';
$strUnsubscribeInfo     = 'Cancelar a subscri&ccedil;&atilde;o de uma ou v&aacute;rias das nossas listas de distribui&ccedil;&atilde;o';
$strContinue            = 'Continuar';
$strUnsubscribeSelect   = 'Por favor seleccione a(s) lista(s) cuja subscri&ccedil;&atilde;o pretende cancelar.';
$strAllLists            = 'Todas as listas';
$strNoLists             = 'Nenhuma das listas';
$strUnsubscribeRequestForReason = '&Eacute; com tristeza que o vemos partir e que vemos que j&aacute; n&atilde;o demonstra interesse nas nossas listas. Para nos ajudar a melhorar os nossos servi%ccedil;os ficariamos agradecidos se nos pudesse dizer a raz&atilde;o:';
$strUnsubscribeFinalInfo = '<br/><b>Please note</b>: this page is to stop receiving emails from our newsletter system <b>forever</b>. If you want to change your email, or if you want to change which newsletters you receive, please <a href="[PREFERENCESURL]">update your preferences</a> instead';
$strNoListsFound        = 'Lamentamos, mas este endere&ccedil;o de correio electr&oacute;nico n&atilde;o se encontra nas bases de dados de assinantes de nenhuma das nossas listas.';
$strResubmit            = 'Reenviar correio electr&oacute;nico';
$strUnsubscribeSubmit   = 'Cancelar a subscri&ccedil;&atilde;o da(s) lista(s) seleccionada(s).';
$strValuesMissing       = 'N&atilde;o preencheu os seguintes dados obrigat&oacute;rios';
$strConfirmInfo         = 'Obrigado pela confirma&ccedil;&atilde;o da sua subscri&ccedil;&atilde;o. A(s) lista(s) que subscreve encontra(m)-se listada(s) abaixo.';
$strConfirmTitle        = 'P&aacute;gina de confirma&ccedil;&atilde;o da subscri&ccedil;&atilde;o';
$strUserNotFound        = 'Assinante n&atilde;o encontrado';
$strUserAlreadyInitialised = 'Lamentamos, mas a sua senha j&aacute; foi definida';
$strConfirmFailInfo     = 'Lamentamos, mas o seu pedido de confirma&ccedil;&atilde;o n&atilde;o foi reconhecido. Certifique-se que usa a totalidade do endere&ccedil;o conforme este surge na mensagem de correio electr&oacute;nico que lhe foi enviada. Por vezes, esse endere&ccedil;o &eacute; quebrado em duas linhas.';
$strPreferHTMLEmail     = 'Eu prefiro receber mensagens no formato HTML';
$strPreferTextEmail     = 'Eu prefiro receber mensagens no formato Texto';
$strPreferredFormat    = 'Formato preferido:';
$strText         = 'Texto';
$strHTML        = 'HTML';
$strPreferencesTitle    = 'Actualize os seus dados';
$strPreferencesInfo     = 'Por favor confirme se a informa&ccedil;&atilde;o abaixo est&aacute; correcta e clique no bot&atilde;o "Actualizar".';
$strUpdatePreferences   = 'Actualizar';
$strPreferencesEmailChanged = 'O seu endere&ccedil;o de correio electr&oacute;nico foi alterado. Por favor visite o endere&ccedil;o indicado na mensagem que vai receber por correio electr&oacute;nico, para confirmar o seu novo endere&ccedil;o.';
$strYouAreBlacklisted = 'O seu email est&aacute; registado na nossa "Lista Negra", o que significa que vec&ecirc; nos pediu para que nunca mais lhe enviassemos emails.<br/>Para que possa receber emails novamente &eacute; necess&aacute;ria interven&ccedil;o do administrador. Contact-nos dizendoo explicitamente que deseja tornar a receber os nossos boletins e será removido da "Lista Negra".';
$strPreferencesNotificationSent = 'Receber&aacute; uma mensagem por correio electr&oacute;nico contendo as altera&ccedil;&otilde;es efectuadas.';
$strPreferencesUpdated = 'Obrigado pela actualiza&ccedil;&atilde;o. Os seus dados foram actualizados.';
$strClickHere          = 'Clique aqui';
$strThisLink           = 'esta liga&ccedil;&atilde;o';
$strToUnsubscribe      = 'Para cancelar a subscri&ccedil;&atilde;o desta lista visite';
$strToUpdate           = 'Para actualizar os seus dados visite';
$strSendHTML           = 'Enviar correio electr&oacute;nico em HTML';
$strYes                = 'Sim';
$strNo                 = 'N&atilde;o';
$strUnsubscribe        = 'Cancelar subscri&ccedil;&otilde;es';
$strAllMailinglists    = 'Todas as listas';
$strAttachmentIntro     = 'Esta mensagem cont&eacute;m anexos que podem ser vistos com um <em>web browser</em>:';
$strLocation       = 'Endere&ccedil;o/URL';
$strFrequency       = 'Com que frequ&ecirc;ncia lhe enviaremos mensagens';
$strHourly         = 'Hora a hora';
$strDaily         = 'Diariamente';
$strWeekly         = 'Semanalmente';
$strMonthly         = 'Mensalmente';
$strChoosePassword      = 'Por favor escolha uma senha';
$strConfirmPassword    = 'Confirme a sua senha';
$strEnterPassword     = 'Por favor introduza a sua senha';
$strForgotPassword     = 'Esqueci-me da senha';
$strPassword       = 'senha';
$strPassword2       = 'Confirmar senha';
$strPasswordsNoMatch   = 'As senhas n&atilde;o condizem';
$strEmailsNoMatch     = 'Os endere&ccedil;os de email n&atilde;o s&atilde;o iguais';
$strInvalidPassword     = 'Erro: endere&ccedil;o de correio electr&oacute;nico ou senha inv&aacute;lidos';
$strPasswordSent      = 'A sua senha foi enviada para o seu endere&ccedil;o de correio electr&oacute;nico. Dever&aacute; receb&ecirc;-la dentro de momentos';
$strPasswordRemindSubject = 'A sua senha para as nossas listas';
$strPasswordRemindMessage = 'A sua senha é ';
$strPasswordRemindInfo = 'Para receber a sua senha por correio electr&oacute;nico, por favor introduza o seu endere&ccedil;o de correio electr&oacute;nico e clique no bot&atilde;o "'.$strForgotPassword.'"';
$strLogin         = 'Login';
$strLoginTitle        = 'Por favor introduza o seu endere&ccedil;o de correio electr&oacute;nico e senha';
$strLoginInfo       = 'Esta p&aacute;gina requer uma senha. Por favor introduza o seu endere&ccedil;o de correio electr&oacute;nico e a senha';
$strPersonalLocationInfo = '
  <p>Para aceder a esta p&aacute;gina &eacute; necess&aacute;ria uma identifica&ccedil;&atilde;o pessoal que pode ser encontrada em cada mensagem que lhe enviamos.<br/>
  Se clicou neste endere&ccedil;o <em>web</em> e se obteve este erro, por favor certifique-se que coloca a totalidade do endere&ccedil;o no seu <em>browser</em>. Por vezes, os programas de correio electr&oacute;nico quebram este endere&ccedil;o em mais de uma linha.</p>
  <p>Se n&atilde;o conhece esse endere&ccedil;o <em>web</em>, pode solicitar o envio de uma mensagem que lho dar&aacute; a conhecer.
  Por favor introduza o seu endere&ccedil;o de correio electr&oacute;nico no campo e clique "Continuar"
';
$strPersonalLocationSent = '<h1>Sucesso! Dever&aacute; receber a mensagem com o seu endere&ccedil;o/URL pessoal dentro de momentos</h1>';
$strUserExists   = '<br/>Um utilizador com esse email j&aacute; existe e os nossos registos cont&ecirc;m uma senha diferente';
$strUserExistsExplanationStart = '<br/>In order to obtain your password, click ';
$strUserExistsExplanationLink = 'here';
$strUserExistsExplanationEnd = ' to go to the page where you can request your personal location';
$strForwardTitle = 'Forward a Message to Someone';
$strForwardSubtitle = 'Forwarding the message with subject ';
$strForwardEnterEmail = 'Please enter a valid email address to forward to';
$strForwardSuccessInfo ='The message has been forwarded';
$strForwardFailInfo = 'Forwarding the message failed';
$strForwardAlreadyDone = 'This message has already been successfully forwarded to that email address';
$strForwardFooter = 'This message has been forwarded to you by [FORWARDEDBY].
  You have not been automatically subscribed to this newsletter.
  To subscribe to this newsletter go to';
$strForward = 'Forward';
$strFwd = 'Fwd'; # short version of forward for email subject
$strConfirmEmail = 'Confirme o seu endereço de email';
