<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strName                = 'Nume';
$strAddress             = 'Adresă';
$strEmail               = 'Email';
$strTown                = 'Localitate';
$strPostcode            = 'Cod poştal';
$strSubscribeInfo       = 'Abonează-te la una sau mai multe liste folosint formularul de mai jos';
$strRequired            = 'câmp obligatoriu';
$strSubscribeTitle      = 'Abonează-te la listele noastre';
$strPleaseSelect        = 'Te rugăm alege listele la care vrei să te abonezi';
$strSubmit              = 'Abonează-te la listele selectate';
$strNotAvailable        = 'Ne pare rău, deocamdată nu există liste disponibile';
$strEnterName           = 'Te rugăm să îţi introduci numele';
$strEnterEmail          = 'Te rugăm introdu adresa de e-mail';
$strInvalidHostInEmail  = 'Ne pare rău, nu se pot livra e-mail-uri la domeniul acesta, te rugăm să verifici dacă ai scris adresa de e-mail corectă';
$strEnterList           = 'Selectează o listă la care să te abonezi';
$strPleaseEnter         = 'Te rugăm să-ţi introduci';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Mulţumim pentru că te-ai abonat la listele noastre';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Adresa ta de e-mail a fost adăugată la sistemul nostru. Vei primi în scurt timp un mesaj cu o cerere de confirmare. Te rugăm să dai clic pe link-ul din acel mesaj pentru a-ţi confirma abonamentul.';
$strEmailFailed		= 'Ne pare rău, e-mailul de confirmare nu a putut fi trimis, te rugăm să dai click pe "Reload" pentru a încerca din nou.';
$strUnsubscribeTitle    = 'Dezabonează-te de la listele noastre';
$strUnsubscribeDone     = 'Ai fost dezabonat de la listele selectate şi vei primi o confirmare prin e-mail în curând.';
$strBack                = 'Înapoi';
$strUnsubscribeInfo     = 'Dezabonează-te de la una sau mai multe liste';
$strContinue            = 'Continuă';
$strUnsubscribeSelect   = 'Te rugăm să selectezi listele de la care vrei să te dezabonezi';
$strAllLists            = 'Toate listele';
$strNoLists             = 'Nici una';
$strNoListsFound        = 'Ne pare rău, nu eşti abonat la nici una din listele noastre cu această adresă de e-mail';
$strResubmit            = 'Re-trimite e-mail-ul';
$strUnsubscribeSubmit   = 'Dezabonează-te de la listele selectate';
$strValuesMissing       = 'Următoarele câmpuri obligatorii nu au fost completate';
$strConfirmInfo         = 'Îţi mulţumim pentru că ţi-ai confirmat abonamentul la listele noastre. Listele la care eşti abonat sunt enumerate mai jos';
$strConfirmTitle        = 'Pagina de confirmare a abonamentului';
$strUserNotFound        = 'Utilizatorul nu a fost identificat';
$strUserAlreadyInitialised = 'Ne pare rău, parola ta a fost trimisă deja';
$strConfirmFailInfo     = 'Ne pare rău, cererea ta de confirmare nu a fost recunoscută. Asigură-te că ai folosit adresa web completă aşa cum este menţionată în mesajul pe care l-ai primit. Uneori această adresă se întinde pe mai multe rânduri.';
$strPreferHTMLEmail     = 'Prefer să primesc e-mail-uri în format HTML';
$strPreferTextEmail     = 'Prefer să primesc e-mail-uri în format Text';
$strPreferredFormat			= 'Formatul preferat pentru e-mail-uri:';
$strText 								= 'Text';
$strHTML								= 'HTML';
$strPreferencesTitle    = 'Actualizează-ţi preferinţele';
$strPreferencesInfo     = 'Te rugăm să confirmi dacă informaţiile de mai jos sunt corecte şi apăsaţi pe butonul "Actualizează"';
$strUpdatePreferences   = 'Actualizează';
$strPreferencesEmailChanged = 'Adresa ta de e-mail a fost modificată. Te rugăm să vizitezi link-ul din mesajul pe care îl vei primi pentru a confirma noua adresă';
$strPreferencesNotificationSent = 'Vei primi un e-mail cu schimbările';
$strPreferencesUpdated = 'Îţi mulţumim pentru modificări. Am actualizat informaţiile tale.';
$strClickHere          = 'Clic Aici';
$strThisLink           = 'acest link';
$strToUnsubscribe      = 'Pentru a te dezabona de la această listă vizitează';
$strToUpdate           = 'Pentru a-ţi modifica preferinţele vizitează';
$strSendHTML           = 'Trimite e-mail HTML';
$strYes                = 'Da';
$strNo                 = 'Nu';
$strUnsubscribe        = 'Dezabonează-te';
$strAllMailinglists    = 'Toate listele';
$strAttachmentIntro		 = 'Acest mesaj conţine ataşamente care pot fi văzute cu un webbrowser:';
$strLocation					 = 'Locaţie';
$strFrequency					 = 'Cât de des îţi trimitem mesaje';
$strHourly						 = 'În fiecare oră';
$strDaily							 = 'Zilnic';
$strWeekly						 = 'Săptămânal';
$strMonthly						 = 'Lunar';
$strChoosePassword 		 = 'Te rugăm să alegi o parolă';
$strConfirmPassword 	 = 'Confirmă parola';
$strEnterPassword			 = 'Introdu parola';
$strForgotPassword		 = 'Am uitat parola';
$strPassword					 = 'Parola';
$strPassword2					 = 'Confirmă Parola';
$strPasswordsNoMatch 	 = 'Parolele nu sunt aceleaşi';
$strInvalidPassword		 = 'Eroare: E-mail-ul sau parola sunt incorecte';
$strPasswordSent 		   = 'Parola ta a fost trimisă prin e-mail. Ar trebui să o primeşti în următoarele minute';
$strPasswordRemindSubject = 'Parola ta pentru listele noastre';
$strPasswordRemindMessage = 'Parola ta este ';
$strPasswordRemindInfo = 'Pentru a primi parola prin e-mail, te rugăm să introduci adresa de e-mail şi să apeşi butonul "'.$strForgotPassword.'".';
$strLogin							 = 'Login';
$strLoginTitle 				 = 'Te rugăm să introduci adresa de e-mail şi parola';
$strLoginInfo					 = 'Această pagină necesită o parolă. Te rugăm să introduci adresa e-mail şi parola';
$strPersonalLocationInfo = '
	<p>Această pagină necesită o identificare personală care poate fi găsită în fiecare e-mail pe care ţi-l trimitem.<br/>
	Dacă ai apăsat pe această licaţie, şi primeşti această eroare, te rugăm să te asiguri că ai copiat întreaga linie în câmpul de adresă al browserului. Uneori acest link se întinde pe mai multe rânduri</p>
  <p>Dacă nu cunoşti locaţia, poţi solicita un e-mail în care ţi se va spune care este. Te rugăm să introduci adrea de e-mail în câmpul acesta şi apasă "Continuă"';
$strPersonalLocationSent = '<h1>Succes! Ar trebui să primeşti un mesaj cu locaţia ta personală în scurt timp</h1>';
$strUserExists   = '<br/>Un utilizator cu această adresă de e-mail există deja, şi înregistrările noastre conţin o altă parolă';
$strUserExistsExplanationStart = '<br/>Pentru a obţine parola apasă ';
$strUserExistsExplanationLink = 'aici';
$strUserExistsExplanationEnd = ' pentru a merge la pagina unde poţi să-ţi soliciţi o locaţie personală';

?>
