<?php

# language dependent text used in the interface for users (not admin)
# update 2013-12-25 Gregor Suhadolc <gregor at  suhi.si>

$strCharSet             = 'UTF-8';
$strName                = 'Ime';
$strAddress             = 'Naslov';
$strEmail               = 'Elektronski naslov';
$strTown                = 'Mesto';
$strPostcode            = 'Poštna št.';
$strSubscribeInfo       = '<h3>Izpolnite obrazec in se prijavite na naše novice.</h3>';
$strRequired            = 'Obvezno polje';
$strSubscribeTitle      = 'Prijavite se na naše novice';
$strPleaseSelect        = 'Prosimo izberite sklope novic, na katere se želite prijaviti';
$strSubmit              = 'Prijavite se na izbrane novice';
$strNotAvailable        = 'Žal ni na voljo noben sklop novic';
$strEnterName           = 'Vnesite svoje ime';
$strEnterEmail          = 'Vnesite svoj e-naslov';
$strConfirmEmail        = 'Potrdite e-naslov';
$strInvalidHostInEmail  = 'Žal na to domeno sporočila ni bilo mogoče dostaviti. Prosimo preverite ali ste pravilno vnesli elektronski naslov.';
$strEnterList           = 'Prosimo izberite novice, na katere se želite prijaviti';
$strPleaseEnter         = 'Prosimo vnesite ';
# the thanks message can contain placeholders
#$strThanks             = '[FIRST NAME], <br/>Hvala, ker ste se prijavili v naš sistem novic.';
$strThanks              = 'Hvala za prijavo.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation  = 'Vaš elektronski naslov [email] je bil dodan v naš sistem novic. V kratkem boste prejeli elektronsko sporočilo z zahtevo za potrditev prijave.';
$strEmailConfirmation   = 'Vaš elektronski naslov je bil dodan v sistem novic. V kratkem boste prejeli elektronsko sporočilo z zahtevo za potrditev prijave. Prosimo kliknite na povezavo za potrditev prijave v elektronskem sporočilu.';
$strEmailFailed         = 'Žal pošiljanje sporočila za potrditev prijave ni uspelo. Prosimo kliknite "Osveži" za ponoven poizkus. Če to ne zaleže, ste morda na našem "seznamu nepošiljanja novic", kar pomeni, da ne morete prejemati sporočil iz našega sistema novic. V tem primeru kontaktirajte administratorja.';
$strUnsubscribeTitle    = 'Odjavite se od naših sklopov novic';
$strUnsubscribeDone     = 'Odjavljeni ste od naših sklopov novic. V kratkem boste prejeli elektronsko sporočilo za potrditev odjave.';
$strUnsubscribedNoConfirm = 'Odjavljeni ste od naših sklopov novic.';
$strBack                = 'Nazaj';
$strUnsubscribeInfo     = 'Odjavite se od naših sklopov novic';
$strContinue            = 'Naprej';
$strUnsubscribeSelect   = 'Prosimo označite sklope novic od katerih se želite odjaviti';
$strAllLists            = 'Vse kategorije novic';
$strNoLists             = 'Nobena kategorija';
$strUnsubscribeRequestForReason = 'Žal nam je, ker niste več zainteresirani za naše novice. Da bi sistem novic izboljšali, bi vam bili hvaležni, če bi nam zaupali, kaj je botrovalo vaši odločitvi:';
$strUnsubscribeFinalInfo = '<br/><b>Pozor</b>: ta stran je namenjena prenehanju prejemanja sporočil iz našega sistema novic <b>za vedno</b>. Če bi radi le spremenili vaš elektronski naslov ali če bi radi spremenili sklope novic, ki jih prejemate, prosimo <a href="[PREFERENCESURL]">spremenite svoje nastavitve</a>';
$strNoListsFound        = 'Na ta naslov ne prejemate nobenega od naših sklopov novic';
$strResubmit            = 'Ponovno predloži';
$strUnsubscribeSubmit   = 'Odjavite se od označenih sklopov novic';
$strValuesMissing       = 'Manjkajo naslednji obvezni podatki';
$strConfirmInfo         = 'Hvala, ker ste potrdili vašo prijavo. Kategorije novic, na katere ste prijavljeni so naštete spodaj';
$strConfirmTitle        = 'Stran za potrditev prijave v eposta';
$strUserNotFound        = 'Uporabnika ni bilo mogoče najti';
$strUserAlreadyInitialised = 'Vaše geslo je bilo že nastavljeno';
$strConfirmFailInfo     = 'Žal ni bilo mogoče prepoznati vašega zahtevka za potrditev. Preverite ali je v elektronskem sporočilu povezava v enem kosu. Včasi se namreč razdeli na več vrstic.';
$strPreferHTMLEmail     = 'Želim prejemati novice v formatu HTML';
$strPreferTextEmail     = 'Želim prejemati novice v tekstovnem formatu';
$strPreferredFormat     = 'Izbran format sporočil:';
$strText                = 'Text';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Spremenite svoje nastavitve';
$strPreferencesInfo     = 'Preverite ali so vnešene vrednosti pravilne in kliknite gumb "Posodobi"';
$strUpdatePreferences   = 'Posodobi';
$strPreferencesEmailChanged = 'Vaš elektronski naslov je bil spremenenjen. Za potrditev spremembe kliknite na povezavo v elektronskem sporočilu, ki ga boste prejeli v kratkem';
$strYouAreBlacklisted = 'Vaš naslov se nahaja na našem "seznamu nepošiljanja sporočil", kar pomeni da ne želite več prejemati nobenih naših novic. <br/>
Če želite zopet prejemati naše novice, mora za to osebno poskrbeti naš administrator. Pošljite nam sporočilo, da želite zopet prejemati naše novice in odstranjeni boste s seznama za neprejemanje sporočil.';
$strPreferencesNotificationSent = 'Prejeli boste elektronsko sporočilo s spremembami';
$strPreferencesUpdated = 'Hvala. Vaše nastavitve so bile posodobljene.';
$strClickHere          = 'Kliknite tukaj';
$strThisLink           = 'to povezavo';
$strToUnsubscribe      = 'Če ne želite več prejemati naših novic, ';
$strToUpdate           = 'Za spremembo nastavitev ali odjavo pojdite na';
$strSendHTML           = 'Pošlji sporočilo v HTML formatu';
$strYes                = 'Da';
$strNo                 = 'Ne';
$strUnsubscribe        = 'Odjava';
$strAllMailinglists    = 'Vse kategorije novic';
$strAttachmentIntro    = 'To sporočilo vsebuje priponke, ki jih je mogoče videti z internetnim brskalnikom:';
$strLocation           = 'Lokacija';
$strFrequency          = 'Kako pogosto želite prejemati naša sporočila';
$strHourly             = 'Vsako uro';
$strDaily              = 'Dnevno';
$strWeekly             = 'Tedensko';
$strMonthly            = 'Mesečno';
$strChoosePassword     = 'Izberite svoje geslo';
$strConfirmPassword    = 'Potrdite geslo';
$strEnterPassword      = 'Vnesite svoje geslo';
$strForgotPassword     = 'Ste pozabili geslo?';
$strForgotPasswordEmailBody = '
    Pozdravljen Administrator
    
	Pozabil-a sem geslo za sistem obveščanja eposta.
	Ali lahko geslo ponastavite in mi sporočite novo geslo?
    
    Hvala
';    

$strPassword           = 'Geslo';
$strPassword2          = 'Potrdite geslo';
$strPasswordsNoMatch    = 'Gesli se ne ujemata';
$strEmailsNoMatch     = 'Vnešena elektronska naslova se ne ujemata';
$strInvalidPassword     = 'Napaka: neveljaven elektronski naslov ali geslo';
$strPasswordSent        = 'Vaše geslo vam je bilo poslano po elektronski pošti. Sporočilo boste prejeli v naslednjih nekaj minutah';
$strPasswordRemindSubject = 'Vaše geslo za naše novice';
$strPasswordRemindMessage = 'Vaše geslo je ';
$strPasswordRemindInfo = 'Če želite prejeti vaše geslo po elektronski pošti, vpišite vaš elektronski naslov in kliknite gumb  "'.$strForgotPassword.'".';
$strLogin               = 'Prijava';
$strLoginTitle          = 'Vnesite svoj elektronski naslov in geslo';
$strLoginInfo           = 'Za dostop do te strani morate vnesti geslo. Prosimo vnesite svoj elektronski naslov in geslo';
$strPersonalLocationInfo = '
  <p>Za dostop do te strani se morate identificirati s podatki, ki smo vam jih poslali po elektronski pošti.<br/>
  Če ste sem prispeli preko povezave in dobili to napako, preglejte če je bila povezava v enem kosu. Včasih se namreč razdeli na več vrstic.</p>
  <p>Če povezave nimate več, lahko zahtevate elektronsko sporočilo, v katerem bo navedena.
  Prosimo vnesite vaš elektronski naslov v okence in kliknite "Naprej"
';
$strPersonalLocationSent = '<h3>Sporočilo z vašo osebno lokacijo vam je bilo uspešno poslano! Prejeli ga boste v naslednjih nekaj minutah.</h3>';
$strUserExists   = 'Uporabnik s tem elektronskim naslovom že obstaja v sistemu, vendar je geslo za ta naslov drugačno od vnešenega';
$strUserExistsExplanationStart = 'Če želite prejeti svoje geslo, kliknite ';
$strUserExistsExplanationLink = 'tukaj';
$strUserExistsExplanationEnd = ' in obiščite stran za pridobitev osebne lokacije';
$strExplainBlacklist = 'Vnešeni e-naslov bo zabeležen v naši bazi izključno z razlogom, da ne boste več prejeli nobenega sporočila.';

$strUserExistsResubscribe = 'Uporabnik s tem e-naslovom že obstaja';
$strUserExistsResubscribeExplanation = 'Za posodobitev vaših nastavitev, obiščite <a href="%s">stran za Nastavitve</a>';


$strForwardTitle = 'Posredujte sporočilo';
$strForwardSubtitle = 'Posredovanje sporočila z zadevo ';
$strForwardEnterEmail = 'Prosimo vnesite veljaven e-naslov, kateremu želite posredovati sporočilo';
$strForwardInvalidEmail = '%s je neveljaven e-naslov';
$strForwardBlacklistedEmail = 'Uporabnik je zahteval, da ne prejema sporočil iz tega sistema.';
$strForwardEnterEmails = 'Vnesite največ %s e-naslovov za posredovanje sporočila, po enega v vrstico';
$strForwardPersonalNote = 'Vnesete lahko svoje sporočilo (največ %d znakov), ki bo pripisano posredovanemu sporočilu';
$strForwardSuccessInfo ='Sporočilo je bilo posredovano';
$strForwardFailInfo = 'Posredovanje sporočila ni uspleo';
$strForwardAlreadyDone = 'To sporočilo je bilo že uspešno posredovano na ta e-naslov';
$strForwardCountReached = 'Doseženo največje število naslovov za posredovanje';
$strForwardNoteLimitReached = 'Dosežena največja dolžina sporočila za posredovanje';
$strForwardFooter = 'To sporočilo vam je posredoval-a [FORWARDEDBY].
  V sistem novic niste bili avtomatsko prijavljeni.
  Če se želite prijaviti na sistem novic, pojdite na';
$strForward = 'Posreduj';
$strFwd = 'Posreduj'; # short version of forward for email subject
