<?php

# language dependent text used in the public interface for users (not admin)
# Encoded in UTF-8 + Updated up till v2.10.10

$strCharSet             = 'UTF-8';
$strName                = 'Nombre';
$strAddress             = 'Dirección';
$strEmail               = 'E-mail';
$strTown                = 'Ciudad';
$strPostcode            = 'Código Postal';
$strSubscribeInfo       = 'Suscríbase a una o más de nuestras listas usando el siguiente formulario';
$strRequired            = 'Campo obligatorio';
$strSubscribeTitle      = 'Suscríbase a nuestras listas de correo';
$strPleaseSelect        = 'Por favor, seleccione las listas a las que desea suscribirse';
$strSubmit              = 'Suscribir';
$strNotAvailable        = 'Lo sentimos, actualmente no hay listas disponibles';
$strEnterName           = 'Por favor, introduzca su nombre';
$strEnterEmail          = 'Por favor, introduzca su dirección de correo';
$strConfirmEmail        = 'Confirme su dirección de correo';
$strInvalidHostInEmail  = 'Lo sentimos, pero no encontramos su servidor, por favor, compruebe su dirección de correo';
$strEnterList           = 'Por favor, seleccione la lista a la que se quiere suscribir';
$strPleaseEnter			= 'Por favor, introduzca su';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Gracias por suscribirse a nuestras listas.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your e-mail [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Su mail ha sido agregado a nuestro sistema. En breve recibirá un mail solicitando confirmación. Por favor, haga clic en el link de ese mensaje para confirmar la suscripción.';
$strEmailFailed			= 'Lo sentimos, hubo un fallo en el envío de su confirmación. Por favor, pulse "actualizar" para intentarlo de nuevo.';
$strUnsubscribeTitle    = 'Cancelar la suscripción a nuestras listas de correo';
$strUnsubscribeDone     = 'Ha cancelado la suscripción a la lista que selecciono y recibirá una confirmación por mail.';
$strBack                = 'Atrás';
$strUnsubscribeInfo     = 'Cancelar la suscripción a nuestra(s) lista(s) de correo';
$strContinue            = 'Continuar';
$strUnsubscribeSelect   = 'Por favor, seleccione la lista de la que quiere cancelar su suscripción';
$strAllLists            = 'Todas las Listas';
$strNoLists             = 'Ninguna';
$strUnsubscribeRequestForReason = 'Lamentamos que no esté mas interesado en nuestro newsletter. Para ayudarnos a mejorar le agradeceríamos si nos indica el motivo por el que se desuscribe:';
$strUnsubscribeFinalInfo = '<br/><b>Nota importante</b>: esta página es para dejar de recibir nuestros newsletters <b>de manera permanente</b>. Si ud. quiere cambiar su e-mail, o si quiere cambiar el newsletter al que está suscripto, por favor <a href="[PREFERENCESURL]">actualice sus preferencias</a> en su lugar';
$strNoListsFound        = 'Actualmente no estás suscrito a ninguna de nuestras listas de correo con esa dirección de correo';
$strResubmit            = 'Re-enviar e-mail';
$strUnsubscribeSubmit   = 'Cancelar suscripción de las listas de correo seleccionadas';
$strValuesMissing       = 'El siguiente valor obligatorio no fue introducido';
$strConfirmInfo 		= 'Gracias por confirmar su suscripción a nuestras listas. Las listas a las que se ha suscrito se muestran a continuación';
$strConfirmTitle 		= 'Página de confirmación para los miembros';
$strUserNotFound		= 'Usuario no encontrado';
$strUserAlreadyInitialised = 'Lo sentimos, su password ya ha sido configurado';
$strConfirmFailInfo		= 'Un error ha ocurrido al tratar de confirmar su suscripción. El mensaje de error se muestra a continuación.';
$strPreferHTMLEmail     = 'Prefiero recibir emails en formato HTML';
$strPreferTextEmail     = 'Prefiero recibir emails en formato Texto';
$strPreferredFormat		= 'Formato preferido para los emails:';
$strText 				= 'Texto';
$strHTML				= 'HTML';
$strPreferencesTitle    = 'Actualice sus preferencias';
$strPreferencesInfo     = 'Por favor, confirme que la información es correcta y pulse el botón "Actualizar información"';
$strUpdatePreferences   = 'Actualizar información';
$strPreferencesEmailChanged = 'Su e-mail ha cambiado. Por favor, visite el enlace en el e-mail que recibirá para confirmar su nueva dirección';
$strYouAreBlacklisted 	= 'Su e-mail ha sido incluido en nuestra "Lista negra", lo que significa que ha solicitado no recibir más nuestros newsletters. <br/> Para recibir emails nuevamente es necesaria la intervención manual de nuestro administrador. Por favor, contacte al administrador y comentele la situación, para que lo elimine de la Lista negra.';
$strPreferencesNotificationSent = 'Recibirá un e-mail con los cambios';
$strPreferencesUpdated = 'Gracias. Hemos actualizado su información.';
$strClickHere          = 'Pulse aquí';
$strThisLink           = 'este enlace';
$strToUnsubscribe      = 'Para borrarse de esta lista visite';
$strToUpdate           = 'Para actualizar sus preferencias visite';
$strSendHTML           = 'Enviar correo HTML';
$strYes                = 'Sí';
$strNo                 = 'No';
$strUnsubscribe        = 'Dar de baja';
$strAllMailinglists    = 'Todas las listas';
$strAttachmentIntro		= 'Este mensaje contiene caracteres que pueden ser vistos con un navegador:';
$strLocation			= 'Ubicación';
$strFrequency			= 'Que tan frecuente le mandamos mensajes';
$strHourly				= 'Cada Hora';
$strDaily				= 'Diariamente';
$strWeekly				= 'Semanalmente';
$strMonthly				= 'Mensualmente';
$strChoosePassword 		= 'Por favor elija una contraseña';
$strConfirmPassword 	= 'Confirme su contraseña';
$strEnterPassword		= 'Por favor ingrese su contraseña';
$strForgotPassword		= 'Olvido su contraseña?';
$strPassword			= 'Contraseña';
$strPassword2			= 'Confirme su contraseña';
$strPasswordsNoMatch 	= 'Las contraseñas no son iguales ';
$strEmailsNoMatch     	= 'Las direcciones de e-mail no son iguales';
$strInvalidPassword		= 'Error: e-mail o contraseña incorrectos';
$strPasswordSent 		= 'Su contraseña ha sido enviada a su correo. Deberia recibirla en los proximos minutos.';
$strPasswordRemindSubject = 'Su contraseña en nuestra lista';
$strPasswordRemindMessage = 'Su contraseña es ';
$strPasswordRemindInfo 	= 'para recibir su contraseña por e-mail, por favor ingrese su e-mail y haga clic en el boton de "'.$strForgotPassword.'".';
$strLogin				= 'Ingresar';
$strLoginTitle 			= 'Por favor ingrese su e-mail y contraseña.';
$strLoginInfo			= 'Esta Pagina requiere una contraseña. Por favor ingrese su e-mail y contraseña.';
$strPersonalLocationInfo = '
	<p>Esta pagina requiere una identificacion personal que puede ser encontrada en cada e-mail que le enviamos.<br/>
  Si usted ve este mensaje, por favor revise que copio y pego TODO el vínculo que recibio por e-mail. Algunas veces el vínculo se salta de linea y no es copiado en su TOTALIDAD.</p>
  <p>Si usted perdio el correo, puede solicitar uno nuevo.
  Por favor ingrese su e-mail y haga clic en  "Continuar" ';
$strPersonalLocationSent = '<h1>Exito! Usted pronto recibira un correo con su ubicación personal</h1>';
$strUserExists   		= '<br/>Un usuario con ese e-mail existe, pero tiene una contraseña distinta.';
$strUserExistsExplanationStart = '<br/>para obtener su password, haga clic ';
$strUserExistsExplanationLink = 'aquí';
$strUserExistsExplanationEnd = ' para ir a la página donde puede pedir su ubicación personal';
$strExplainBlacklist 	= 'El e-mail que ingrese aquí será registrada en nuestra base de datos con el único propósito de bloquear cualquier correo enviado desde este sistema.';
$strForwardTitle 		= 'Reenviar el mensaje a otra persona';
$strForwardSubtitle 	= 'Reenviando el mensaje con asunto ';
$strForwardEnterEmail 	= 'Por favor, ingrese un mail válido al que reenviar este mensaje';
$strForwardInvalidEmail = '%s is not a valid e-mail address';
$strForwardBlacklistedEmail = 'El receptor ha solicitado de NO recibir correos electrónicos de este sistema.';
$strForwardEnterEmails 	= 'Por favor, introduzca un máximo de %s emails válidos para reenviar en este cuadro, uno por línea';
$strForwardPersonalNote = 'Puede introducir un mensaje de texto (de % caracteres máximo) que se antepondrá al correo enviado';
$strForwardSuccessInfo 	='El mensaje ha sido reenviado';
$strForwardFailInfo 	= 'El reenvío del mensaje a fallado';
$strForwardAlreadyDone 	= 'Este mensaje ha sido exitosamente reenviado al mail';
$strForwardCountReached = 'Alcanzado el número máximo de reenvios';
$strForwardNoteLimitReached = 'Alcanzado tamaño máximo de la nota personal';
$strForwardFooter 		= 'Este mensaje le ha sido enviado por [FORWARDEDBY]. 
  Ud. no será automáticamente suscrito al newsletter. 
  Para suscribirse debe ir a ';
$strForward 			= 'Reenviar';
$strFwd 				= 'Fwd'; # short version of forward for e-mail subject
?>