<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strName                = 'Name';
$strAddress             = 'Addresse';
$strEmail               = 'E-Mail';
$strTown                = 'Wohnort';
$strPostcode            = 'Postfach';
$strSubscribeInfo       = 'Zum Anmelden bei einer oder mehreren unserer Mailinglisten ben&uuml;tzen Sie das nachfolgende Formular!';
$strRequired            = 'Ben&ouml;tigte Felder:';
$strSubscribeTitle      = 'Anmelden bei der Mailingliste';
$strPleaseSelect        = 'Bitte w&auml;hlen Sie eine oder mehrere Listen, bei denen Sie sich anmelden wollen';
$strSubmit              = 'Anmelden bei den ausgew&auml;hlten Mailinglisten';
$strNotAvailable        = 'Derzeit sind keine Listen verf&uuml;gbar';
$strEnterName           = 'Bitte geben Sie ihren Namen ein';
$strEnterEmail          = 'Bitte geben Sie ihre E-Mail Adresse ein';
$strInvalidHostInEmail  = 'Entschuldigung, aber E-Mail an diese Adresse ist unzustellbar. Bitte pr&uuml;fen Sie Ihre Adresse erneut.';
$strEnterList           = 'Bitte w&auml;hlen Sie ein Liste aus, bei der Sie sich anmelden wollen';
$strPleaseEnter		= 'Bitte geben Sie ein';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Danke f&uuml;r die Anmeldung bei unseren Listen.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Sie erhalten in k&uuml;rze eine E-Mail mit der Best&auml;tigung der Listen bei denen Sie sich angemeldet haben.';
$strEmailFailed		= 'Entschuldigung, aber die E-Mail mit der Best&auml;tigungsanfrage wurde nicht versandt, bitte dr&uuml;cken Sie Aktualisieren und versuchen Sie es nochmals.';
$strUnsubscribeTitle    = 'Abmelden von unseren Mailinglisten';
$strUnsubscribeDone     = 'Sie wurden von den Mailinglisten die Sie ausgew&auml;hlt haben abgemeldet, eine Best&auml;tigung erhalten Sie in k&uuml;rze per E-Mail.';
$strBack                = 'Zur&uuml;ck';
$strUnsubscribeInfo     = 'Abmelden von einer oder mehreren unserer Mailinglisten';
$strContinue            = 'Weiter';
$strUnsubscribeSelect   = 'Bitte w&auml;hlen Sie die Listen von denen Sie sich abmelden wollen';
$strAllLists            = 'Alle Listen';
$strNoLists             = 'Keine von diesen';
$strNoListsFound        = 'Sie wurden mit dieser E-Mail bei keiner unserer Mailinglisten angemeldet';
$strResubmit            = 'Erneut versuchen';
$strUnsubscribeSubmit   = 'Abmelden von den gew&auml;hlten Mailinglisten';
$strValuesMissing       = 'Die folgenden ben&ouml;tigten Felder fehlen';
$strConfirmInfo 	= 'Danke f&uuml;r die Best&auml;tigung. Sie wurden auf folgenden Listen eingeschrieben:';
$strConfirmTitle 	= 'Best&auml;tigungsseite';
$strUserNotFound	= 'User nicht gefunden';
$strUserAlreadyInitialised = 'Ihre Passwort wurde bereits verschickt';
$strConfirmFailInfo	= 'Es trat ein Fehler auf. Details:';
$strPreferHTMLEmail     = 'Ich bevorzuge E-Mails im HTML-Format';
$strPreferTextEmail     = 'Ich bevorzuge E-Mails im Text-Format';
$strPreferredFormat	= 'Bevorzugtes Format f&uuml;r E-Mails:';
$strText                = 'Text';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Einstellungen Aendern';
$strPreferencesInfo     = 'Bitte best&auml;tigen Sie, daß die folgenden Informationen korrekt sind und dr&uuml;cken Sie den Update-Button';
$strUpdatePreferences   = 'Update';
$strPreferencesEmailChanged = 'Ihre E-Mail wurde ge&auml;ndert. Bitte besuchen Sie den Link, welcher in der E-Mail genannt wird, die Sie an Ihre neue Adresse erhalten.';
$strPreferencesNotificationSent = 'Sie werden eine E-Mail mit den Aenderungen erhalten';
$strPreferencesUpdated = 'Danke f&uuml;r Ihre Aenderungen. Wir haben Ihre Informationen aktualisiert.';
$strClickHere          = 'Dr&uuml;cken Sie hier';
$strThisLink           = 'dieser Link';
$strToUnsubscribe      = 'Um sich aus der Liste auszutragen, besuchen Sie';
$strToUpdate           = 'Um Ihre Einstellungen zu &auml;ndern, besuchen Sie';
$strSendHTML           = 'Sende HTML E-Mail';
$strYes                = 'Ja';
$strNo                 = 'Nein';
$strUnsubscribe        = 'Abmelden';
$strAllMailinglists    = 'Alle Mailinglisten';
$strAttachmentIntro    = 'Diese Nachricht beinhaltet Anh&auml;nge, die mit einem Webbrowser betrachtet werden k&ouml;nnen:';
$strLocation           = 'Ort';
$strFrequency          = 'Wie oft d&uuml;rfen wir Ihnen Nachrichten senden';
$strHourly             = 'St&uuml;ndlich';
$strDaily              = 'T&auml;glich';
$strWeekly             = 'W&ouml;chentlich';
$strMonthly            = 'Monatlich';
$strChoosePassword     = 'Bitte w&auml;hlen Sie ein Passwort';
$strConfirmPassword    = 'Bitte best&auml;tigen Sie Ihr Passwort';
$strEnterPassword      = 'Bitte geben Sie Ihr Passwort ein';
$strForgotPassword     = 'Passwort vergessen';
$strPassword           = 'Passwort';
$strPassword2          = 'Passwort best&auml;tigen';
$strPasswordsNoMatch   = 'Die Passw&ouml;rter stimmen nicht &uuml;berein';
$strInvalidPassword    = 'Fehler: ung&uuml;ltige E-Mail oder Passwort';
$strPasswordSent       = 'Ihre Passwort wurde Ihnen per E-Mail zugesendet. Sie sollten es innerhalb der n&auml;chsten Minuten erhalten.';
$strPasswordRemindSubject = 'Ihr Passwort f&uuml;r unsere Listen';
$strPasswordRemindMessage = 'Ihr Passwort lautet ';
$strPasswordRemindInfo = 'Um Ihr Passwort per E-Mail zu erhalten, geben Sie bitte Ihre E-Mail-Adresse ein und dr&uuml;cken den "'.$strForgotPassword.'" Knopf.';
$strLogin              = 'Login';
$strLoginTitle         = 'Bitte geben Sie Ihre E-Mail-Adresse und Ihr Passwort ein';
$strLoginInfo          = 'Diese Seite ben&ouml;tigt ein Passwort. Bitte geben Sie Ihre E-Mail-Adresse und Ihr Paßwort ein';
$strPersonalLocationInfo = '
  <p>Diese Seite ben&ouml;tigt eine pers&ouml;nliche Identifikation, welche auf jeder von uns an Sie gesendeten E-Mail angegeben ist.<br/>
  Wenn Sie diesen Bereich angeklickt haben und diesen Fehler erhalten, vergewissern Sie sich, daß Sie die vollst&auml;ndige Linie in die 
  Adressezeile Ihres Browsers eigetragen haben. Manchmal ist die Adresse &uuml;ber mehrere Zeilen umgebrochen.</p>
  <p>Wenn Sie den Bereich nicht kennen, k&ouml;nnen Sie ihn per E-Mail erfragen.
  Bitte geben Sie dazu Ihre E-Mail-Adresse ein und klicken Sie auf Weiter
';
$strPersonalLocationSent = '<h1>Erfolg! Sie sollten eine Nachricht mit Ihrem pers&ouml;nlichen Bereich in K&uuml;rze erhalten</h1>';
$strUserExists         = '<br/>Ein Benutzer mit dieser E-Mail-Adresse existiert bereits und hat ein anderes Passwort';
$strUserExistsExplanationStart = '<br/>Um Ihr Passwort zu erhalten, klicken Sie';
$strUserExistsExplanationLink = 'hier';
$strUserExistsExplanationEnd = ' um zu der Seite zu gelangen, wo Sie Ihren pers&ouml;nlichen Bereich anfordern k&ouml;nnen';
?>
