<?php
$strCharSet = 'utf-8';
$strName = '姓名';
$strAddress = '住址';
$strEmail = '電子郵件';
$strTown = '居住城市';
$strPostcode = '郵遞區號';
$strSubscribeInfo = '請利用以下表格訂定電子報';
$strRequired = '需要的欄位';
$strSubscribeTitle = '我要訂報';
$strPleaseSelect = '請選擇您所要登記的列表';
$strSubmit = '訂定您所選擇的列表';
$strNotAvailable = '對不起，目前沒有任何電子報';
$strEnterName = '請輸入您的姓名';
$strEnterEmail = '請輸入您的電子郵件信箱';
$strConfirmEmail = '請再輸入一次您的電子郵件信箱';
$strInvalidHostInEmail = '對不起，這個信箱位址無法寄出，請再檢查一下位址是否有誤';
$strEnterList = '請選擇列表中您所要訂定電子報';
$strPleaseEnter = '請輸入您的';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks = '謝謝您訂閱我們的電子報';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation = '您的電子郵件已加入我們的系統中，您將會在這個信箱中收到我們的確定函, 請接著按信中的回覆網址，這樣就完成我們的註冊手續';
$strEmailFailed = '對不起您所按的確認請求錯誤,請按 "Reload" 再試一次';
$strUnsubscribeTitle = '取消訂閱電子報';
$strUnsubscribeDone = '已經取消您的訂閱。';
$strBack = '回上一頁';
$strUnsubscribeInfo = '取消更多的電子報';
$strContinue = '繼續';
$strUnsubscribeSelect = '請選擇您想要取消的電子報列表';
$strAllLists = '所有的列表';
$strNoLists = '沒有任何列表';
$strUnsubscribeRequestForReason = '對於您不再訂閱我們的電子報我們深感遺憾，如果能夠，請讓我們知道原因，我們希望能夠讓它越來越好：';
$strUnsubscribeFinalInfo = '<br/><b>請注意</b>：這個頁面表示您將 <b>永遠</b> 不再收到我們的電子報。';
$strNoListsFound = '對不起，這個電子郵件沒有訂定任何電子報';
$strResubmit = '請重新確定電子郵件地址';
$strUnsubscribeSubmit = '從列表中選擇欲取消的電子報';
$strValuesMissing = '您沒有輸入下面必填欄位';
$strConfirmInfo = '謝謝您完成了電子報的訂閱確認，您訂閱的電子報如下';
$strConfirmTitle = '電子報會員確認網頁';
$strUserNotFound = '沒有這個人';
$strUserAlreadyInitialised = '抱歉，您的必碼已經設定';
$strConfirmFailInfo = '抱歉，您嘗試連結的網址不存在，請確認您是透過我們寄出信件中的完整連結，有時候同一行的網址會被電子郵件軟體切成多行。';
$strPreferHTMLEmail = '我希望收到HTML格式';
$strPreferTextEmail = '我希望收到純文字格式';
$strPreferredFormat = '您想要的電子報格式:';
$strText = '純文字';
$strHTML = 'HTML';
$strPreferencesTitle = '更新您的設定';
$strPreferencesInfo = '請確認下面的資訊是否正確，接著點選"更新"';
$strUpdatePreferences = '更新';
$strPreferencesEmailChanged = '您修改了收件信箱，我們將會寄出一封確認信函到您的新信箱。';
$strYouAreBlacklisted = '抱歉，您的信箱列在我們的封鎖清單中，這表示您曾經要求我們不要再寄送任何信件到您的信箱 <br/>
如果您希望透過這個信箱再次訂閱我們的電子報，
請連繫管理員協助更新這個封鎖清單！';
$strPreferencesNotificationSent = '您將會收到異動通知信';
$strPreferencesUpdated = '謝謝您提供的資訊，資料已經更新。';
$strClickHere = '點選這裡';
$strThisLink = '這個連結';
$strToUnsubscribe = '取消訂閱：';
$strToUpdate = '更新設定：';
$strSendHTML = '送出 HTML 郵件';
$strYes = '是';
$strNo = '否';
$strUnsubscribe = '取消訂閱';
$strAllMailinglists = '所有電子報';
$strAttachmentIntro = '這個訊息包含附加檔案，它可以在網頁瀏覽器中看到';
$strLocation = '位置';
$strFrequency = '我們多久送一次電子信';
$strHourly = '每小時';
$strDaily = '每天';
$strWeekly = '每週';
$strMonthly = '每月';
$strChoosePassword = '請選擇密碼';
$strConfirmPassword = '再次確定密碼';
$strEnterPassword = '請輸入您的密碼';
$strForgotPassword = '" 鍵';
$strPassword = '密碼';
$strPassword2 = '再次輸入密碼';
$strPasswordsNoMatch = '兩次密碼不同';
$strEmailsNoMatch = '您輸入的電子信箱不符';
$strInvalidPassword = '錯誤：無效的密碼或電子郵件地址';
$strPasswordSent = '您的密碼已送到您的電子郵件中，您可以在幾分鐘後收到電子信 ';
$strPasswordRemindSubject = '列表密碼';
$strPasswordRemindMessage = '您的密碼是： ';
$strPasswordRemindInfo = '如果要正確收到我們的密碼， 請輸入您的電子郵件及按 "';
$strLogin = '登入';
$strLoginTitle = '請輸入您的電子郵件地址及密碼';
$strLoginInfo = '這頁需要密碼，請輸入您的電子郵件地址及密碼';
$strPersonalLocationInfo = '
  <p>這個頁面需要透過我們電子報內容後附加的個人連結<br/>
  如果您是透過那些連結而出現這個錯誤訊息，
  請確認網址的部分有沒有被切成兩行，記得將他們完整的貼到網址列。</p>
  <p>如果您不知道是哪個位置，
  您可以在下面欄位輸入您的信箱，接著點選 "繼續"
';
$strPersonalLocationSent = '<h1>成功！您在幾分鐘內會收到上述的連結</h1>';
$strUserExists = '<br/>電子郵件位址重複或是密碼錯誤';
$strUserExistsExplanationStart = '<br/>如果忘記密碼，請點選 ';
$strUserExistsExplanationLink = '這裡';
$strUserExistsExplanationEnd = ' 來繼續索取密碼的步驟';
$strExplainBlacklist = '系統會記錄您所輸入的 Email，並放在禁止寄送的名單中';
$strForwardTitle = '轉寄信件給朋友';
$strForwardSubtitle = '轉寄信件主旨';
$strForwardEnterEmail = '請輸入希望轉寄的信箱';
$strForwardInvalidEmail = '%s 並不是正確的 Email';
$strForwardBlacklistedEmail = '收信人已設定拒絶收信';
$strForwardEnterEmails = '請在此輸入最大的 %s Email 轉信數量';
$strForwardPersonalNote = '你可以輸入純文字訊 (最多 %d 個字元) 來轉信';
$strForwardSuccessInfo = '信件已經轉寄出去';
$strForwardFailInfo = '信件轉寄失敗';
$strForwardAlreadyDone = '信件已經成功轉寄到您指定的信箱';
$strForwardCountReached = '已超過最大轉信量';
$strForwardNoteLimitReached = '已超過最大轉信說明可容許的長度';
$strForwardFooter = '這封信由 [FORWARDEDBY] 轉寄給您，
  您並未因此自動訂閱了我們的電子報（別擔心），
  如果您希望訂閱我們的電子報請前往';  
$strForward = '轉寄';
$strFwd = '[轉寄]';
?>