<?php

# language dependent text used in the interface for users (not admin) - UTF-8 encoded
# originally translated by Seref Erkayhan erkayhan@fzi.de
# completed, modified and corrected by WolfHawke (wolfhawke@wolfhawke.com) at Hawke AI (http://www.hawke-ai.com)
# 2009-01-28

$strCharSet             = 'UTF-8';
$strName                = 'Ýsim';
$strAddress             = 'Adress';
$strEmail               = 'ePosta adresi';
$strTown                = 'Þehir';
$strPostcode            = 'Posta kodu';
$strSubscribeInfo       = 'Hangi ePosta Listelerine abone olmak istediðinizi seçin';
$strRequired            = 'Doldurulmasý zorunlu alan';
$strSubscribeTitle      = 'ePosta Listemize üye olunuz';
$strPleaseSelect        = 'Lütfen abone olmak istediðiniz ePosta Listemizi seçiniz';
$strSubmit              = 'ePosta Listeye Abone Ol';
$strNotAvailable        = 'Üzgünüz þu an abone olacaðýnýz ePosta Listemiz yoktur';
$strEnterName           = 'Lütfen isminizi giriniz';
$strEnterEmail          = 'Lütfen ePosta adresinizi giriniz';
$strConfirmEmail        = 'Lütfen ePosta adresinizi ikinci bir kere giriniz';
$strInvalidHostInEmail  = 'Üzgünüz, ePosta mesajýný gönderecek sunucu belirlenmedi veya sunucuya baðlantý kurulamadý, lütfen ePosta adresinizi kontrol ediniz';
$strEnterList           = 'Abone olmak istediðiniz ePosta Listemizi seçiniz';
$strPleaseEnter         = 'Lütfen giriniz';
# Teþekkür mesajýnýn içinde placeholder mevcut olabilir
#$strThanks             = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Listemize üye olduðunuz için teþekkürler';
# ePost adresi doðrulama mesajýnda placeholder mevcut olabilir
#$strEmailConfirmation   = 'Listemize aboneliðinizi doðrulamanýz için [email] ePosta adresinize bir mesaj gönderildi. aboneliðinizi doðrulamak için, lütfen mesajdaki linki týklayýnýz. Bu linki týklamazsanýz, listeden size mesaj gelmez.';
$strEmailConfirmation  = 'Listemize aboneliðinizi doðrulamanýz için girdiðiniz ePosta adresine bir mesaj gönderildi. aboneliðinizi doðrulamak için, lütfen mesajdaki linki týklayýnýz. Bu linki týklamazsanýz, listeden size mesaj gelmez.';
$strUnsubscribeTitle    = 'Listemizden çýkmak için buraya týklayýnýz';
$strUnsubscribeDone     = 'Listemizden çýktýnýz. ePosta adresinide bunu doðrlayan bir mesaj alacaksýnýz.';
$strBack                = 'Geri';
$strUnsubscribeInfo     = 'Listemiz veya listelerimizden çýkmak için buraya týklayýnýz';
$strContinue            = 'Devam';
$strAllLists            = 'Tüm Listeler';
$strNoLists             = 'Hiçbir Liste';
$strUnsubscribeRequestForReason = 'Listelerimizden çýkmak istediðiniz için üzgünüz. Sunduðumuz hizmetlerin kalitesini arttýrabilmemiz için, listemizden niye çýktýðnýzý açýklar mýsýnýz?';
$strUnsubscribeFinalInfo = '<br/><b>Lütfen dikkat</b>: Bu sayfayý onaylarsanýz, listemizden <b>temelli olarak</b> çýkmýþ olacaksýnýz. Yalnýzca ePosta adresiniz deðiþtirmek veya abone olduðunuz listeleri deðiþtirmek niyetindeyseniz <a href="[PREFERENCESURL]">kiþisel seçeneklerinizi güncelleyin</a>.';
$strNoListsFound        = 'Üzgünüz, bu ePosta adresi ile hiç bir listemize abone deðilsiniz';
$strResubmit            = 'ePosta adresinizi tekrar giriniz';
$strUnsubscribeSubmit   = 'Seçtiðiniz liste(ler)den çýkmak için buraya týklayýnýz';
$strValuesMissing       = 'Aþaðýdaki gerekli veriler eksik';
$strConfirmInfo         = 'Listemize aboneliðinizi doðruladýðýnýz için teþekkürler. Abone olduðunuz listeler aþaðýdadýr';
$strConfirmTitle        = 'Liste aboneliðinizi doðrulama sayfasý';
$strUserNotFound        = 'Kullanýcý bulunamadý';
$strUserAlreadyInitialised = 'Þifreniz zaten belirlenmiþtir.';
$strConfirmFailInfo     = 'Üzgünüz, aboneliðinizi doðrularken bir hata oluþtu. Lütfen aldýðýnýz e-maildeki linki kontrol edin. Bazen linkler ikinci satýra geçebilir. Detaylý bir hata mesajý aþaðýdadýr.';
$strPreferHTMLEmail     = 'Zengin metin (HTML) formatýndak mesajlarý tercih ederim.';
$strPreferTextEmail     = 'Düz metin formatýndak mesajlarý tercih ederim.';
$strPreferredFormat      = 'ePosta mesajlarý için tercih ettiðiniz format:';
$strText                 = 'Düz metin';
$strHTML                = 'Zengin metin (HTML)';
$strPreferencesTitle    = 'Ayarlarý Güncelleme';
$strPreferencesInfo     = 'Lütfen aþaðýdaki bilgilerin doðruluðunu kontrol edin ve güncelleyin.';
$strUpdatePreferences   = 'Güncelle';
$strPreferencesEmailChanged = 'ePosta adresiniz deðiþtirildi. Lütfen yeni ePosta adresinizin deðiþikliðini doðrulamanýz için gönderilen mesaja cevap veriniz';
$strYouAreBlacklisted   = 'ePosta adresiniz "kara liste"mize eklenmiþtir, yani bizden hiçbir zaman mesaj almamayý talebinde bulundunuz.<br/> Bizden mesaj alabilmeniz için Yöneticilerimizin müdahalesi gerekiyor. Listelerimize abone olabilmek için, Yöneticilerimiz ile doðrudan irtibata geçip, açýkça listelerimize abone olmak talebinde bulunun. Böylece Yöneticilerimiz sizi kara listemizden silecekler.';
$strPreferencesNotificationSent = 'Deðiþiklikleri içeren bir mesaj alacaksýnýz';
$strPreferencesUpdated  = 'Teþekkürler. Verileriniz güncellendi';
$strClickHere           = 'Lütfen burayý týklayýnýz';
$strToUnsubscribe       = 'Bu listeye aboneliðinizi iptal etmek için týklayýn';
$strToUpdate            = 'Ayarlarýnýzý deðiþtirmek için týklayýn';
$strSendHTML            = 'Zengin metin (HTML) ePosta mesajlarý gönder';
$strYes                 = 'Evet';
$strNo                  = 'Hayýr';
$strUnsubscribe         = 'ePosta listesinden çýk';
$strAllMailinglists     = 'Tüm listeler';
$strAttachmentIntro     = 'Bu mesaj Ýnternet tarayacýnýzda izleyebileceðiniz eklentiler içerir:';
$strLocation            = 'Konumunuz';
$strFrequency           = 'Size ne kadar sýk mesaj gönderiyoruz:';
$strHourly              = 'Her saat';
$strDaily               = 'Her gün';
$strWeekly              = 'Her hafta';
$strMonthly             = 'Her ay';
$strChoosePassword      = 'Lütfen bir parola giriniz';
$strConfirmPassword     = 'Parolayý doðrulayýnýz';
$strEnterPassword       = 'Parolanýzý giriniz';
$strForgotPassword      = 'Parolamý unuttum';
$strPassword            = 'Parola';
$strPassword2           = 'Parolayý doðrulayýnýz';
$strPasswordsNoMatch    = 'Girdiðiniz parolalar ayný deðil.';
$strEmailsNoMatch       = 'Girdiðiniz ePosta adresleri ayný deðil';
$strInvalidPassword     = 'Hata: ePosta adresi veya parola geçersiz';
$strPasswordSent        = 'Þifreniz ePosta adresinize gönderildi. Bir kaç dakika içinde varmýþ olmasý gerekir.';
$strPasswordRemindSubject = 'Listelerimize girmek için parolanýz';
$strPasswordRemindMessage = 'Parolanýz: ';
$strPasswordRemindInfo  = 'Parolanýzýn ePosta adresine yollanmasý için "'.$strForgotPassword.'" düðmesini týklayýn.';
$strLogin               = 'Gir';
$strLoginTitle          = 'ePosta adresinizi ve parolanýzý girin.';
$strLoginInfo           = 'Bu sayfayý görebilmeniz için bir parola girmelisiniz. Lütfen ePosta adresinizi ve parolanýzý giriniz.';
$strPersonalLocationInfo = '
  <p>Bu sayfayi açabilmeniz için size her ePosta mesajýnda gönderdiðimiz þahsi taným kodu gereklidir.<br/>
  ePosta mesajýnýzdaki linki týkladýktan sonra bu hata mesajýný görüyorsanýz, lütfen mesajdaki bulununan linkin tümünü
  kopyalayýp Ýnternet tarayýcýnýzýn adres çubuðuna yapýþtýrýn. Bazý ePosta programlarý linkleri bir kaç satýra katlayabilir.</p>
  <p>Þahsi taným kodunuzu bilmiyorsanýz, aþaðýdaki formu kullanarak kodunuzun ePosta adresinize gönderilmesini talep
  edebilirsiniz.</p>
  <p>ePosta adresinizi kutuya girip "Devam" tuþunu týklayýn.
';
$strPersonalLocationSent = '<h1>Talebiniz alýnmýþtýr. En kýsa zamanda þahsi taným kodunuzu içeren bir mesaj alacaksýnýz.</h1>';
$strUserExists = '<br/>Bu ePosta adresine sahip olan bir abonemiz mevcuttur, ama bizde kayýtlý olan parola farklýdýr.';
$strUserExistsExplanationStart = '<br/>Parolanýzý öðrenmek için þahsi taným kodunuzu istemek için ';
$strUserExistsExplanationLink = 'týklayýn';
$strUserExistsExplanationEnd = '.';
$strExplainBlacklist = 'Buraya girdiðiniz ePosta adresi kara listemize kaydedilecektir. Bu bizden mesaj almamýzý kesinlikle engellemek için yapýlacaktýr.';
$strForwardTitle = 'Mesajý tanýdýðýma ilet';
$strForwardSubtitle = 'Þu mesaj tanýdýðýnýza iletilecektir: ';
$strForwardEnterEmail = 'Ýletmek istediðiniz kiþinin geçerli ePosta adresini giriniz:';
$strForwardInvalidEmail = '%s geçerli bir ePosta adresi deðildir.';
$strForwardBlacklistedEmail = 'Bu þahýs bizden mesaj almama talebinde bulunmuþtur.';
$strForwardEnterEmails = 'Bu mesajý iletmek istediðiniz en fazla %s ePosta adresi giriniz. Her satýrda yalnýzca bir adres olmalý.';
$strForwardPersonalNote = 'Gönderilecek mesajýn baþýna en fazla %d harf uzunluðunda bir düz metin mesajý ekleyebilirsiniz ';
$strForwardSuccessInfo ='Mesaj iletidi.';
$strForwardFailInfo = 'Mesaj iletilemedi.';
$strForwardAlreadyDone = 'Bu mesaj zaten girdiðiniz ePosta adresine iletilmiþtir.';
$strForwardCountReached = 'Ýletebileceðiniz mesajlar sayýsý dolmuþtur.';
$strForwardNoteLimitReached = 'Özel mesaj dolmuþtur.';
$strForwardFooter = 'Bu mesaj size [FORWARDEDBY] tarafýndan gönderildi.
  Siz bu listeye abone deðilsiniz. Bu liseye abone olmak için þuraya gidiniz:';
$strForward = 'Ýlet';
$strFwd = 'Gnd'; # short version of forward for email subject

?>