<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strName                = 'Ім`я';
$strAddress             = 'Адреса';
$strEmail               = 'Email';
$strTown                = 'Місто';
$strPostcode            = 'Поштовий код';
$strSubscribeInfo       = 'Підпишіться на наші розсилки використовуючи форму внизу';
$strRequired            = 'обов`язкове поле';
$strSubscribeTitle      = 'Підписатися на розсилки';
$strPleaseSelect        = 'Будь-ласка, оберіть розсилки, на які Ви б хотіли підписатися';
$strSubmit              = 'Підписатися на обрані розсилки';
$strNotAvailable        = 'Вибачте, зараз немає доступних розсилок';
$strEnterName           = 'Будь-ласка, вкажіть своє ім`я';
$strEnterEmail          = 'Будь-ласка, вкажіть свою email адресу';
$strInvalidHostInEmail  = 'Вибачте, неможливо доставити email до цього домену, перевірте правильність написання email адреси';
$strEnterList           = 'Будь-ласка, оберіть розсилку для підписки';
$strPleaseEnter         = 'Будь-ласка, введіть';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Дякуємо, що підписалися на нашу розсилку.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Ваш email було додано до нашої бази. Скоро Ви отримаєте по емейлу запит для підтвердження Вашої участі. Вам треба буде лише натиснути на посилання, щоб підтвердити свою підписку.';
$strEmailFailed          = 'Вибачте, не вдалося надіслати листа для запиту вашого підтвердження. Натисніть "Reload" щоб спробувати ще раз. Якщо нічого не виходить, можливо, Ваша адреса в "чорному списку" і Ви не можете отримувати наші інформаційні повідомлення. У такому разі, сконтактуйте з адміністратором.';
$strUnsubscribeTitle    = 'Відписатися від наших розсилок';
$strUnsubscribeDone     = 'Ви відписалися від наших розсилок і скоро отримаєте підтвердження електронною поштою.';
$strBack                = 'Назад';
$strUnsubscribeInfo     = 'Відписатися від наших розсилок';
$strContinue            = 'Далі';
$strUnsubscribeSelect   = 'Будь-ласка, оберіть розсилки, від яких Ви хочете відмовитися';
$strAllLists            = 'Всі розсилки';
$strNoLists             = 'Жодна з них';
$strUnsubscribeRequestForReason = 'Нам шкода, що Вам більше не цікава наша розсилка. Ми були б вдячні, якби Ви повідомили чому. :';
$strUnsubscribeFinalInfo = '<br/><b>Увага</b>: ця сторінка призначена для того, аби припинити отримання листів від нашої розсилки <b>назавжди</b>. Якщо Ви хочете змінити свій email, або якщо хочете змінити розсилку, будь-ласка <a href="[PREFERENCESURL]">оновіть персональну інформацію</a>';
$strNoListsFound        = 'Вибачте, але Ви не підписані на жодну з наших розсилок з такою адресою електронної пошти';
$strResubmit            = 'Ще раз надати Email';
$strUnsubscribeSubmit   = 'Відписатися від вказаних розсилок';
$strValuesMissing       = 'Відсутні наступні обов`язкові дані';
$strConfirmInfo         = 'Дякуємо, що підтвердили підписку на наші розсилки. Нижче перераховано розсилки, на які Ви підписані';
$strConfirmTitle        = 'Сторінка підтвердження участі PHPlist ';
$strUserNotFound        = 'Користувача не знайдено';
$strUserAlreadyInitialised = 'Вибачте, але Ваш пароль вже визначено';
$strConfirmFailInfo     = 'Вибачте, Ваш запит на підтвердження не розпізнано. Важливо, щоб веб-адреса була вказана повністю, як у листі, що Ви отримали. Інколи ця адреса розбивається на кілька рядків.';
$strPreferHTMLEmail     = 'Я хочу отримувати листи в HTML форматі';
$strPreferTextEmail     = 'Я хочу отримувати листи в текстовому форматі';
$strPreferredFormat      = 'Бажаний формат для емейлів:';
$strText                 = 'Текст';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Оновити Ваші дані';
$strPreferencesInfo     = 'Будь-ласка, підтвердіть, що нижченаведена інформація правильна та натисніть кнопку "Оновити"';
$strUpdatePreferences   = 'Оновити';
$strPreferencesEmailChanged = 'Ваш email змінено. Будь-ласка, перейдіть по лінку, який Ви отримаєте для підтвердження Вашого нового email-а';
$strYouAreBlacklisted = 'Ваш email - в "Чорному списку", а це означає, що Ви попросили нас ніколи більше не надсилати Вам ніяких листів.<br/>
Для того, щоб Ви знову отримували листи, потрібне безпосереднє втручання нашого адміністратора. Будь-ласка, сконтактуйте з нами, і недвозначно вкажіть, що хочете знову отримувати від нас листи, і ми повернемо Вас до бази отримувачів.';
$strPreferencesNotificationSent = 'Вам надіслано листа зі змінами';
$strPreferencesUpdated = 'Дякуємо за інформацію. Ми оновили Ваші дані.';
$strClickHere          = 'Натисніть тут';
$strThisLink           = 'цей лінк';
$strToUnsubscribe      = 'Якщо Ви не хочете більше отримувати розсилки, ';
$strToUpdate           = 'Для оновлення Ваших даних та для того, щоб відписатися, перейдіть на';
$strSendHTML           = 'Надіслати HTML email';
$strYes                = 'Так';
$strNo                 = 'Ні';
$strUnsubscribe        = 'Відписатися';
$strAllMailinglists    = 'Всі розсилки';
$strAttachmentIntro     = 'Це повідомлення містить вкладення, які можна переглянути у веб-браузері:';
$strLocation           = 'Локація';
$strFrequency           = 'Як часто надсилати Вам повідомлення';
$strHourly             = 'Щогодини';
$strDaily               = 'Щодня';
$strWeekly             = 'Щотижня';
$strMonthly             = 'Щомісяця';
$strChoosePassword      = 'Будь-ласка, оберіть пароль';
$strConfirmPassword    = 'Підтвердіть свій пароль';
$strEnterPassword       = 'Будь-ласка, введіть свій пароль';
$strForgotPassword     = 'Забули пароль';
$strPassword           = 'Пароль';
$strPassword2           = 'Підтвердити пароль';
$strPasswordsNoMatch    = 'Паролі не співпадають';
$strEmailsNoMatch     = 'Email-адреси, які Ви ввели, не співпадають';
$strInvalidPassword     = 'Помилка: невірний email або пароль';
$strPasswordSent        = 'Ваш пароль надіслано електронною поштою. Ви маєте отримати його протягом наступних кількох хвилин';
$strPasswordRemindSubject = 'Ваш пароль для наших розсилок';
$strPasswordRemindMessage = 'Ваш пароль ';
$strPasswordRemindInfo = 'Для отримання паролю електронною поштою, будь-ласка, введіть свій email та натисніть кнопку "'.$strForgotPassword.'" ';
$strLogin               = 'Логін';
$strLoginTitle          = 'Будь-ласка, введіть свій email address та password';
$strLoginInfo           = 'Ця сторінка запаролена. Будь-ласка, введіть свій email та пароль';
$strPersonalLocationInfo = '
  <p>Ця сторінка потребує персонального ідентифікатора, який вказано у кожному повідомленні, яке ми Вам надсилаємо.<br/>
  Якщо Ви клікнули на лінк, і бачите це повідомлення про помилку, упевніться, що ви повністю скопіювали весь рядок
  у поле адреси Вашого браузера. Інколи посилання розбивається в листах на кілька рядків.</p>
  <p>Якщо Ви не знаєте конкретної адреси, Ви можете надіслати запит і ви отримаєте листа, що повідомить Вам її.
  Будь-ласка, введіть свій email у форму та натисніть "Далі"
';
$strPersonalLocationSent = '<h1>Ура! Ви скоро отримаєте листа з Вашою персональною адресою (локацією)</h1>';
$strUserExists   = '<br/>Користувач з таким email-ом вже існує, і в нашій базі він зареєстрований під іншим паролем';
$strUserExistsExplanationStart = '<br/>Для тут, щоб отримати Ваш пароль, натисніть ';
$strUserExistsExplanationLink = 'тут';
$strUserExistsExplanationEnd = ', щоб перейти до сторінки де Ви зможете запитати про Вашу персональну локацію (адресу)';
$strForwardTitle = 'Переслати повідомлення комусь';
$strForwardSubtitle = 'Пересилаю повідомлення з темою ';
$strForwardEnterEmail = 'Будь-ласка, вкажіть коректний email, щоб переслати';
$strForwardSuccessInfo ='Це повідомлення переслано';
$strForwardFailInfo = 'Переслати повідомлення не вдалося';
$strForwardAlreadyDone = 'Це повідломлення ми вже успішно пересилали на вказану адресу';
$strForwardFooter = 'Це повідомлення Вам переслав(ла) [FORWARDEDBY].
  Вас не була автоматично підписано на цю розсилку.
  Аби підписатися на розсилку, перейдіть';
$strForward = 'Forward';
$strFwd = 'Fwd'; # short version of forward for email subject
?>