<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strName                = 'Name';
$strAddress             = 'Address';
$strEmail               = 'Email';
$strTown                = 'City';
$strPostcode            = 'ZIP Code';
$strSubscribeInfo       = 'Subscribe to one or more of our newsletters using the form below';
$strRequired            = 'required field';
$strSubscribeTitle      = 'Subscribe to our Newsletters';
$strPleaseSelect        = 'Please select the newsletters you want to sign up to';
$strSubmit              = 'Subscribe to the Selected Newsletters';
$strNotAvailable        = 'Sorry there are currently no newsletters available';
$strEnterName           = 'Please enter your name';
$strEnterEmail          = 'Please enter your email address';
$strInvalidHostInEmail  = 'Sorry, email to that domain is undeliverable, please check that you typed the correct email address';
$strEnterList           = 'Please select a newsletter to subscribe to';
$strPleaseEnter         = 'Please enter your';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Thank you for subscribing to our newsletters.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Your email has been added to our system. You will be e-mailed shortly with a request to confirm your membership. Please make sure to click the link in that message to confirm your subscription.';
$strEmailFailed          = 'Sorry, sending the email to request your confirmation failed, please click "Reload" to try again. If it still does not work, it may be because you are listed on our "Black List", which means that you cannot receive emails from our newsletter system. In that case, please contact the administrator.';
$strUnsubscribeTitle    = 'Unsubscribe from our Newsletters';
$strUnsubscribeDone     = 'You have been unsubscribed from our newsletters and you will receive confirmation by email soon.';
$strBack                = 'Back';
$strUnsubscribeInfo     = 'Unsubscribe from our newsletters';
$strContinue            = 'Continue';
$strUnsubscribeSelect   = 'Please select the newsletters you want to unsubscribe from';
$strAllLists            = 'All Lists';
$strNoLists             = 'None of them';
$strUnsubscribeRequestForReason = 'We are sorry to find you are not any longer interested in our newsletter. To help us improve our services, we would be grateful if you could tell us why:';
$strUnsubscribeFinalInfo = '<br/><b>Please note</b>: this page is to stop receiving emails from our newsletter system <b>forever</b>. If you want to change your email, or if you want to change which newsletters you receive, please <a href="[PREFERENCESURL]">update your preferences</a> instead';
$strNoListsFound        = 'Sorry, you are not subscribed to any of our newsletters with this email';
$strResubmit            = 'Re-Submit Email';
$strUnsubscribeSubmit   = 'Unsubscribe from the Selected Newsletters';
$strValuesMissing       = 'The following required values are missing';
$strConfirmInfo         = 'Thank you for confirming your subscription to our newsletters. The newsletters you are subscribed to are listed below';
$strConfirmTitle        = 'PHPlist membership confirmation page';
$strUserNotFound        = 'User not found';
$strUserAlreadyInitialised = 'Sorry, your password has already been set';
$strConfirmFailInfo     = 'Sorry, your request for confirmation was not recognized. Please make sure to use the full web address as mentioned in the email that you received. Sometimes this web address wraps onto multiple lines.';
$strPreferHTMLEmail     = 'I prefer to receive emails in HTML format';
$strPreferTextEmail     = 'I prefer to receive emails in Text format';
$strPreferredFormat      = 'Preferred format for emails:';
$strText                 = 'Text';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Update your preferences';
$strPreferencesInfo     = 'Please confirm that the information below is correct and click the "Update" button';
$strUpdatePreferences   = 'Update';
$strPreferencesEmailChanged = 'Your email has changed. Please visit the link in the email you will receive to confirm your new email address';
$strYouAreBlacklisted = 'Your email is listed in our "Black List", which means that you have requested us never to send you any more newsletters. <br/>
In order to receive emails again, manual intervention is required by our administrator. Please contact us stating explicitly that you want to receive newsletters again, and we will
take you off our black list. ';
$strPreferencesNotificationSent = 'You will receive an email with the changes';
$strPreferencesUpdated = 'Thank you for your submission. We have updated your information.';
$strClickHere          = 'Click Here';
$strThisLink           = 'this link';
$strToUnsubscribe      = 'If you do not want to receive any more newsletters, ';
$strToUpdate           = 'To update your preferences and to unsubscribe visit';
$strSendHTML           = 'Send HTML email';
$strYes                = 'Yes';
$strNo                 = 'No';
$strUnsubscribe        = 'Unsubscribe';
$strAllMailinglists    = 'All newsletters';
$strAttachmentIntro     = 'This message contains attachments that can be viewed with a web browser:';
$strLocation           = 'Location';
$strFrequency           = 'How often do we send you messages';
$strHourly             = 'Hourly';
$strDaily               = 'Daily';
$strWeekly             = 'Weekly';
$strMonthly             = 'Monthly';
$strChoosePassword      = 'Please choose a password';
$strConfirmPassword    = 'Confirm your password';
$strEnterPassword       = 'Please enter your password';
$strForgotPassword     = 'Forgot Password';
$strPassword           = 'Password';
$strPassword2           = 'Confirm Password';
$strPasswordsNoMatch    = 'Passwords are not the same';
$strEmailsNoMatch     = 'Email Addresses you entered do not match';
$strInvalidPassword     = 'Error: invalid email or password';
$strPasswordSent        = 'Your password has been sent to your by email. You should receive it in the next few minutes';
$strPasswordRemindSubject = 'Your password for our newsletters';
$strPasswordRemindMessage = 'Your password is ';
$strPasswordRemindInfo = 'To receive your password by email, please enter your email and click the "'.$strForgotPassword.'" button.';
$strLogin               = 'Login';
$strLoginTitle          = 'Please enter your email address and password';
$strLoginInfo           = 'This page requires a password. Please enter your email address and password';
$strPersonalLocationInfo = '
  <p>This page requires a personal identification that can be found on each email that we send you.<br/>
  If you have clicked this location, and you get this error, please make sure to paste the entire line into the
  location box of your browser. Sometimes the location is wrapped over several lines.</p>
  <p>If you do not know the location, you can request an email that will tell you what it is.
  Please enter your email in the box and click "Continue"
';
$strPersonalLocationSent = '<h1>Success! You should receive a message with your personal location shortly</h1>';
$strUserExists   = '<br/>A user with that email already exists, and our records contain a different password';
$strUserExistsExplanationStart = '<br/>In order to obtain your password, click ';
$strUserExistsExplanationLink = 'here';
$strUserExistsExplanationEnd = ' to go to the page where you can request your personal location';
$strForwardTitle = 'Forward a Message to Someone';
$strForwardSubtitle = 'Forwarding the message with subject ';
$strForwardEnterEmail = 'Please enter a valid email address to forward to';
$strForwardSuccessInfo ='The message has been forwarded';
$strForwardFailInfo = 'Forwarding the message failed';
$strForwardAlreadyDone = 'This message has already been successfully forwarded to that email address';
$strForwardFooter = 'This message has been forwarded to you by [FORWARDEDBY].
  You have not been automatically subscribed to this newsletter.
  To subscribe to this newsletter go to';
$strForward = 'Forward';
$strFwd = 'Fwd'; # short version of forward for email subject
?>
