<?php

# language dependent text used in the interface for users (not admin)
  $strCharSet = 'utf-8';
  $strName = 'T&ecirc;n';
  $strAddress = '&#272;&#7883;a ch&#7881;';
  $strEmail = 'Email';
  $strTown = 'Th&agrave;nh ph&#7889;';
  $strPostcode = 'M&atilde; b&#432;u &#273;i&#7879;n';
  $strSubscribeInfo = 'Xin h&atilde;y &#273;&#259;ng k&yacute; &#273;&#7875; nh&#7853;n c&aacute;c b&#7843;n tin c&#7911;a ch&uacute;ng t&ocirc;i';
  $strRequired = 'th&ocirc;ng tin b&#7855;t bu&#7897;c c&oacute; ti&ecirc;u &#273;&#7873; m&#7847;u &#273;&#7887;';
  $strSubscribeTitle = '&#272;ang k&yacute; nh&#7853;n b&#7843;n tin &#273;&#7883;nh k&#7923;';
  $strPleaseSelect = 'Xin hay ch&#7885;n b&#7843;n tin b&#7841;n y&ecirc;u th&iacute;ch';
  $strSubmit = '&#272;&#259;ng k&yacute; nh&#7853;n b&#7843;n tin &#273;&atilde; ch&#7885;n';
  $strNotAvailable = 'Xin l&#7895;i, hi&#7879;n kh&ocirc;ng c&oacute; b&#7843;n tin n&agrave;o &#273;&#7875; &#273;&#259;ng k&yacute;';
  $strEnterName = 'Xin h&atilde;y nh&#7853;p t&ecirc;n';
  $strEnterEmail = 'Xin h&atilde;y nh&#7853;p &#273;&#7883;a ch&#7881; email';
  $strInvalidHostInEmail = 'Xin l&#7895;i, email kh&ocirc;ng h&#7907;p l&#7879;, xin hay ki&#7875;m tra l&#7841;i &#273;&#7883;a ch&#7881; email c&#7911;a b&#7841;n';
  $strEnterList = 'Xin h&atilde;y ch&#7885;n m&#7897;t B&#7843;n tin';
  $strPleaseEnter = 'Xin h&atilde;y nh&#7853;p ';# Please enter your';
  # the thanks message can contain placeholders
  #$strThanks = 'Dear [FIRSTNAME], <br/>Thank you for subscribing to our lists.';
  $strThanks = 'C&#7843;m &#417;n b&#7841;n &#273;&atilde; &#273;&#259;ng k&yacute; nh&#7853;n b&#7843;n tin d8&#7883;nh k&#7923; c&#7911;a ch&uacute;ng t&ocirc;i';
  # the EmailConfirmation message can contain placeholders
  #$strEmailConfirmation = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
  $strEmailConfirmation = '&#272;&#7883;a ch&#7881; email c&#7911;a b&#7841;n &#273;&atilde; &#273;&#432;&#7907;c ch&#7845;p nh&#7853;n. B&#7841;n s&#7869; nh&#7853;n &#273;&#432;&#7907;c th&#432; y&ecirc;u c&#7847;u x&aacute;c nh&#7853;n c&#7911;a ch&uacute;ng t&ocirc;i. Xin h&atilde;y b&#7845;m chu&#7897;t v&agrave;o li&ecirc;n k&#7871;t trong th&#432; &#273;&#7875; k&iacute;ch ho&#7841;t email c&#7911;a b&#7841;n';
  $strEmailFailed = 'Sorry, sending the email to request your confirmation failed, please click &quot;Reload&quot; to try again. If it still does not work, it may be because you are listed on our &quot;Black List&quot;, which means that you cannot receive emails from our newsletter system. In that case, please contact the administrator.';
  $strUnsubscribeTitle = 'X&oacute;a t&ecirc;n kh&#7887;i danh s&aacute;ch nh&#7853;n b&#7843;n tin &#273;&#7883;nh k&#7923;';
  $strUnsubscribeDone = 'Email c&#7911;a b&#7841;n &#273;&atilde; &#273;&#432;&#7907;c xo&aacute; kh&#7887;i danh s&aacute;ch c&#7911;a ch&uacute;ng t&ocirc;i.<br /> B&#7841;n s&#7869; nh&#7853;n &#273;&#432;&#7907;c th&#432; x&aacute;c nh&#7853;n qua email';
  $strBack = 'Quay l&#7841;i';
  $strUnsubscribeInfo = 'X&oacute;a t&ecirc;n kh&#7887;i danh s&aacute;ch nh&#7853;n b&#7843;n tin &#273;&#7883;nh k&#7923;';
  $strContinue = 'Ti&#7871;p t&#7909;c';
  $strUnsubscribeSelect = 'Xin h&atilde;y ch&#7885;n B&#7843;n tin b&#7841;n kh&ocirc;ng mu&#7889;n nh&#7853;n n&#7919;a';
  $strAllLists = 'T&#7845;t c&#7843;';
  $strNoLists = 'Kh&ocirc;ng ch&#7885;n m&#7909;c n&agrave;o';
  $strUnsubscribeRequestForReason = 'Ch&uacute;ng t&ocirc;i r&#7845;t l&#7845;y l&agrave;m ti&#7871;c n&#7871;u b&#7841;n kh&ocirc;ng mu&#7889;n nh&#7853;n b&#7843;n tin &#273;&#7883;nh k&#7923; c&#7911;a ch&uacute;ng t&ocirc;i. &#272;&#7875; n&acirc;ng cao h&#417;n n&#361;a d&#7883;ch v&#7909;, xin b&#7841;n h&atilde;y cho bi&#7871;t l&yacute; do:<br />';
  $strUnsubscribeFinalInfo = '<br/><br /><b>L&#432;u &yacute;</b>: sau khi x&oacute;a t&ecirc;n b&#7841;n s&#7869; <b>kh&ocirc;ng bao gi&#7901;</b> nh&#7853;n &#273;&#432;&#7907;c b&#7843;n tin &#273;&#7883;nh k&#7923; c&#7911;a ch&uacute;ng t&ocirc;i n&#7919;a. <br /><br />N&#7871;u b&#7841;n mu&#7889;n thay &#273;&#7893;i &#273;&#7883;a ch&#7881; email, ho&#7863;c n&#7871;u b&#7841;n mu&#7889;n thay &#273;&#7893;i B&#7843;n tin &#273;&#7883;nh k&#7923;, xin h&atilde;y <a href=&quot;[PREFERENCESURL]&quot;>c&#7853;p nh&#7853;t t&#7841;i &#273;&acirc;y</a>';
  $strResubmit = 'G&#7917;i l&#7841;i &#273;&#7883;a ch&#7881; email';
  $strNoListsFound = 'Xin l&#7895;i, b&#7841;n ch&#432;a &#273;&#259;ng k&yacute; nh&#7853;n B&#7843;n tin n&agrave;o c&#7911;a ch&uacute;ng t&ocirc;i v&#7899;i email n&agrave;y.<br /><br /> H&atilde;y ki&#7875;m tra l&#7841;i r&#7891;i b&#7845;m v&agrave;o n&uacute;t &quot;' . $strResubmit . '&quot;';
  $strUnsubscribeSubmit = 'X&oacute;a t&ecirc;n kh&#7887;i B&#7843;n tin &#273;&#7883;nh k&#7923; &#273;&atilde; ch&#7885;n';# Unsubscribe from the Selected Newsletters';
  $strValuesMissing = 'Nh&#7919;ng th&ocirc;ng tin sau b&#7883; thi&#7871;u';# The following required values are missing';
  $strConfirmInfo = 'C&aacute;m &#417;n b&#7841;n &#273;&atilde; x&aacute;c nh&#7853;n. D&#432;&#7899;i &#273;&acirc;y l&agrave; danh s&aacute;ch c&aacute;c B&#7843;n tin b&#7841;n &#273;&atilde; &#273;&#259;ng k&yacute;';
  $strConfirmTitle = 'Trang x&aacute;c nh&#7853;n th&agrave;nh vi&ecirc;n';
  $strUserNotFound = 'Kh&ocirc;ng t&igrave;m th&#7845;y email c&#7911;a b&#7841;n';
  $strUserAlreadyInitialised = 'Xin l&#7895;i, m&#7853;t kh&#7849;u &#273;&atilde; &#273;&#432;&#7907;c x&aacute;c l&#7853;p';# Sorry, your password has already been set';
  $strConfirmFailInfo = 'Xin l&#7895;i, y&ecirc;u c&#7847;u x&aacute;c nh&acirc;n kh&ocirc;ng h&#7907;p l&#7879;. Xin h&atilde;y &#273;&#7843;m b&#7843;o r&#7857;ng b&#7841;n d&ugrave;ng &#273;&uacute;ng li&ecirc;n k&#7871;t trong email. Nhi&#7873;u khi li&ecirc;n k&#7871;t b&#7883; ng&#7855;t th&agrave;nh hai hay nhi&#7873;u d&ograve;ng';# Sorry, your request for confirmation was not recognised. Please make sure to use the full web address as mentioned in the email that you received. Sometimes this web address wraps onto multiple lines.';
  $strPreferHTMLEmail = 'T&ocirc;i mu&#7889;n nh&#7853;n B&#7843;n tin theo &#273;&#7883;nh d&#7841;ng HTML';
  $strPreferTextEmail = 'T&ocirc;i mu&#7889;n nh&#7853;n B&#7843;n tin theo &#273;&#7883;nh d&#7841;ng Text';
  $strPreferredFormat = '&#272;&#7883;nh d&#7841;ng email:';
  $strText = 'Text';
  $strHTML = 'HTML';
  $strPreferencesTitle = 'C&#7853;p nh&#7853;t th&ocirc;ng tin c&aacute; nh&acirc;n';# Update your preferences';
  $strPreferencesInfo = 'N&#7871;u th&ocirc;ng tin d&#432;&#7899;i &#273;&acirc;y l&agrave; &#273;&uacute;ng, xin h&atilde;y b&#7845;m v&agrave;o n&uacute;t &quot;C&#7853;p nh&#7853;t&quot;';
  # Please confirm that the information below is correct and click the &quot;Update&quot; button';
  $strUpdatePreferences = 'C&#7853;p nh&#7853;t';
  $strPreferencesEmailChanged = '&#272;&#7883;a ch&#7881; email c&#7911;a b&#7841;n thay &#273;&atilde; thay &#273;&#7893;i. Xin hay b&#7845;m v&agrave;o li&ecirc;n k&#7871;t trong email b&#7841;n s&#7869; nh&#7853;n &#273;&#432;&#7907;c &#273;&#7875; x&aacute;c nh&#7853;n s&#7921; thay &#273;&#7893;i';
  $strYouAreBlacklisted = '&#272;&#7883;a ch&#7881; email c&#7911;a b&#7841;n hi&#7879;n &#7903; trong &quot;Danh s&aacute;ch &#272;en&quot;, c&oacute; ngh&#297;a l&agrave; b&#7841;n &#273;&atilde; y&ecirc;u c&#7847;u ch&uacute;ng t&ocirc;i kh&ocirc;ng g&#7917;i b&#7843;n tin cho b&#7841;n. <br />&#272;&#7875; ti&#7871;p t&#7909;c nh&#7853;n B&#7843;n tin, xin h&atilde;y li&ecirc;n h&#7879; v&#7899;i ch&uacute;ng t&ocirc;i &#273;&#7875; x&oacute;a t&ecirc;n b&#7841;n kh&#7887;i &quot;Danh s&aacute;ch &#272;en&quot;';
  $strPreferencesNotificationSent = 'B&#7841;n s&#7869; nh&#7853;n &#273;&#432;&#7907;c email v&#7899;i nh&#7919;ng thay &#273;&#7893;i c&#7911;a b&#7841;n';# You will receive an email with the changes';
  $strPreferencesUpdated = 'C&#7843;m &#417;n b&#7841;n &#273;&atilde; g&#7917;i th&ocirc;ng tin c&#7853;p nh&#7853;t';# Thank you for your submission. We have updated your information.';
  $strClickHere = 'B&#7845;m v&agrave;o &#273;&acirc;y';
  $strThisLink = 'v&agrave;o &#273;&acirc;y';
  $strToUnsubscribe = 'N&#7871;u b&#7841;n kh&ocirc;ng mu&#7889;n nh&#7853;n b&#7841;n tin c&#7911;a ch&uacute;ng t&ocirc;i';# If you do not want to receive any more newsletters, ';
  $strToUpdate = '&#272;&#7875; thay &#273;&#7893;i th&ocirc;ng tin c&aacute; nh&acirc;n v&agrave; thay &#273;&#7893;i B&#7843;n tin b&#7845;m';# To update your preferences and to unsubscribe visit';
  $strSendHTML = 'G&#7917;i HTML email';
  $strYes = '&#272;&#7891;ng &yacute;';
  $strNo = 'Kh&ocirc;ng';
  $strUnsubscribe = 'X&oacute;a t&ecirc;n kh&#7887;i danh s&aacute;ch';
  $strAllMailinglists = 'T&#7845;t c&#7843; c&aacute;c B&#7843;n tin';
  $strAttachmentIntro = 'This message contains attachments that can be viewed with a webbrowser:';
  $strLocation = 'V&#7883; tr&iacute;';
  $strFrequency = 'B&#7841;n mu&#7889;n nh&#7853;n B&#7843;n tin theo';# How often do we send you messages';
  $strHourly = 'Theo gi&#7901;';
  $strDaily = 'Theo ng&agrave;y';
  $strWeekly = 'Theo tu&#7847;n';
  $strMonthly = 'Theo th&aacute;ng';
  $strChoosePassword = 'Xin h&atilde;y ch&#7885;n m&#7853;t kh&#7849;u';
  $strConfirmPassword = 'X&aacute;c nh&#7853;n l&#7841;i m&#7853;t kh&#7849;u';
  $strEnterPassword = 'Xin h&atilde;y nh&#7853;p m&#7853;t kh&#7849;u';
  $strForgotPassword = 'Qu&ecirc;n m&#7853;t kh&#7849;u';
  $strPassword = 'M&#7853;t kh&#7849;u';
  $strPassword2 = 'X&aacute;c nh&#7853;n l&#7841;i';
  $strPasswordsNoMatch = 'M&#7853;t kh&#7849;u ph&#7843;i tr&ugrave;ng nhau';
  $strEmailsNoMatch = '&#272;&#7883;a ch&#7881; email b&#7841;n nh&#7853;p v&agrave;o kh&ocirc;ng &#273;&uacute;ng';
  $strInvalidPassword = 'L&#7895;i: sai email ho&#7863;c m&#7853;t kh&#7849;u';
  $strPasswordSent = 'M&#7853;t kh&#7849;u &#273;&atilde; &#273;&#432;&#7907;c g&#7917;i cho b&#7843;n qua email. H&atilde;y ki&#7875;m tra h&#7897;p th&#432; c&#7911;a b&#7841;n trong v&agrave;i ph&uacute;t t&#7899;i';
  $strPasswordRemindSubject = 'M&#7853;t kh&#7849;u d&ugrave;ng cho B&#7843;n tin &#273;&#7883;nh k&#7923; c&#7911;a ch&uacute;ng t&ocirc;i';
  $strPasswordRemindMessage = 'M&#7853;t kh&#7849;u c&#7911;a b&#7841;n l&agrave;';
  $strPasswordRemindInfo = '&#272;&#7875; kh&ocirc;i ph&#7909;c m&#7853;t kh&#7849;u, h&atilde;y nh&#7853;p &#273;&#7883;a ch&#7881; email v&agrave; b&#7845;m n&uacute;t&quot;'.$strForgotPassword;
  $strLogin = '&#272;&#259;ng nh&#7853;p';
  $strLoginTitle = 'Xin h&atilde;y nh&#7853;p email v&agrave; m&#7853;t kh&#7849;u';
  $strLoginInfo = 'Trang n&agrave;y y&ecirc;u c&#7847;u m&#7853;t kh&#7849;u. Xin h&atilde;y nh&#7853;p email v&agrave; m&#7853;t kh&#7849;u';
  $strPersonalLocationInfo = '
<p>Trang n&agrave;y y&ecirc;u c&#7847;u m&atilde; hi&#7879;u c&aacute; nh&acirc;n. B&#7841;n c&oacute; th&#7875; t&igrave;m th&#7845;y trong m&#7893;i b&#7843;n tin nh&#7853;n &#273;&#432;&#7907;c c&#7911;a ch&uacute;ng t&ocirc;i.<br/>
  N&#7871;u b&#7841;n &#273;&atilde; s&#7917; d&#7909;ng &#273;&uacute;ng &#273;&#432;&#7901;ng d&#7851;n, h&atilde;y &#273;&#7843;m b&#7843;o r&#7857;ng b&#7841;n &#273;&atilde; c&#7855;t d&aacute;n to&agrave;n b&#7897; &#273;&#432;&#7901;ng d&#7851;n trong b&#7843;n tin v&agrave;o tr&igrave;nh duy&#7879;t c&#7911;a b&#7841;n. &#272;&ocirc;i khi &#273;&#432;&#7901;ng d&#7851;n b&#7883; ng&#7855;t l&agrave;m nhi&#7873;u d&ograve;ng.</p>
<p>N&#7871;u b&#7841;n kh&ocirc;ng bi&#7871;t &#273;&#432;&#7901;ng d&#7851;n, b&#7841;n c&oacute; th&#7875; g&#7917;i y&ecirc;u c&#7847;u b&#7857;ng c&aacute;ch nh&#7853;p &#273;&#7883;a ch&#7881; email v&agrave;o h&#7897;p tho&#7841;i v&agrave; b&#7845;m v&agrave;o n&uacute;t &quot;Ti&#7871;p t&#7909;c&quot;';
  $strPersonalLocationSent = '<h1>&#272;&atilde; ch&#7845;p nh&#7853;n y&ecirc;u c&#7847;u! B&#7841;n s&#7869; nh&#7853;n &#273;&#432;&#7907;c &#273;&#432;&#7901;ng d&#7851;n qua email trong v&agrave;i ph&uacute;t t&#7899;i</h1>';
  $strUserExists = '<br/>Email &#273;&atilde; &#273;&#259;ng k&yacute; nh&#432;ng m&#7853;t kh&#7849;u kh&ocirc;ng &#273;&uacute;ng';
  $strUserExistsExplanationStart = '<br/>&#272;&#7875; kh&ocirc;i ph&#7909;c m&#7853;t kh&#7849;u, b&#7845;m';
  $strUserExistsExplanationLink = 'v&agrave;o &#273;&acirc;y';
  $strUserExistsExplanationEnd = ' &#273;&#7875; v&agrave;o trang b&#7841;n y&ecirc;u c&#7847;u &#273;&#432;&#7901;ng d&#7851;n';
  $strForwardTitle = 'Chuy&#7875;n m&#7897;t th&ocirc;ng &#273;i&#7879;p t&#7899;i ng&#432;&#7901;i kh&aacute;c';
  $strForwardSubtitle = 'Chuy&#7875;n th&ocirc;ng &#273;i&#7879;p v&#7899;i ti&ecirc;u &#273;&#7873; ';
  $strForwardEnterEmail = '&#272;&#7875; chuy&#7875;n th&ocirc;ng &#273;i&#7879;p xin h&atilde;y nh&#7853;p email h&#7907;p l&#7879;';
  $strForwardSuccessInfo ='Th&ocirc;ng &#273;i&#7879;p &#273;&atilde; &#273;&#432;&#7907;c chuy&#7875;n';
  $strForwardFailInfo = 'Kh&ocirc;ng chuy&#7875;n &#273;&#432;&#7907;c th&ocirc;ng &#273;i&#7879;p';
  $strForwardAlreadyDone = 'Th&ocirc;ng &#273;i&#7879;p n&agrave;y &#273;&atilde; &#273;&#432;&#7907;c chuy&#7875;n th&agrave;nh c&ocirc;ng t&#7899;i &#273;&#7883;a ch&#7881; email &#273;&oacute;';
  $strForwardFooter = ' Th&ocirc;ng &#273;i&#7879;p g&#7917;i t&#7899;i b&#7903;i [FORWARDEDBY]. B&#7841;n ch&#432;a &#273;&#259;ng k&yacute; v&#7899;i ch&uacute;ng t&ocirc;i. To subscribe to this newsletter go to';
  $strForward = 'Forward';
  $strFwd = 'Fwd'; # short version of forward for email subject

?>